package abi

import (
	"encoding/json"
	"path/filepath"
	"runtime"
	"testing"

	"daal/core/budget"
	"daal/core/diagnostics"
	"daal/core/pathmanager"
	"daal/core/routestore"
)

// samplesDir is generated by Phase 1A's sample harness. The path is
// derived from this test file's own location so the tests work
// regardless of where the repo is checked out (CI workspaces are not
// /home/daal).
var samplesDir = filepath.Join(testRepoRoot(), "specs", "test-vectors", "bundles", "samples")

func testRepoRoot() string {
	_, file, _, _ := runtime.Caller(0)
	// .../core/abi/abi_test.go → repo root.
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func TestEndToEndImportConnectDisconnect(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	if VersionString() == "" {
		t.Fatal("empty version")
	}

	// Import → trust prompt expected.
	verdict, _ := ImportSBP(filepath.Join(samplesDir, "signed-A.sbp"))
	if verdict == "" || !contains(verdict, "VerdictTrustPromptNeeded") && !contains(verdict, `"Kind":1`) {
		// Verdict is JSON of the importer.Verdict struct; Kind=1 means
		// VerdictTrustPromptNeeded.
	}
	// Resolve via fingerprint hex (parse it out of the JSON).
	fp := extractField(verdict, "Fingerprint")
	if fp == "" {
		t.Fatalf("could not parse fingerprint from verdict: %s", verdict)
	}
	if _, err := ResolveTrustPrompt(fp, 0); err != nil {
		t.Fatalf("resolve trust: %v", err)
	}

	// Now connect to the imported route.
	if err := SetRoute("sample-route-1"); err != nil {
		t.Fatalf("set route: %v", err)
	}
	if err := ClearRoute(); err != nil {
		t.Fatalf("clear route: %v", err)
	}

	if err := SetMode("lifeline"); err != nil {
		t.Fatal(err)
	}
	if Mode() != "lifeline" {
		t.Fatal("mode not applied")
	}

	if _, err := ExportDiagnostics(); err != nil {
		t.Fatal(err)
	}
}

func contains(s, sub string) bool {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return true
		}
	}
	return false
}

// extractField is a tiny no-deps JSON peeker for the test.
func extractField(jsonBlob, name string) string {
	key := `"` + name + `":"`
	i := indexOf(jsonBlob, key)
	if i < 0 {
		return ""
	}
	rest := jsonBlob[i+len(key):]
	end := indexOf(rest, `"`)
	if end < 0 {
		return ""
	}
	return rest[:end]
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

// === Phase 2A-Polish: session boundary across Init/Shutdown cycles ===

// TestSessionBoundaryAcrossInits verifies that two engine_init calls
// bracket a budget-session boundary. After the first Init, the budget
// engine instantiated via SetRouteBudget gets a fresh session
// (epoch=1). After Shutdown + Init, the engine is re-instantiated and
// the per-session counter is zero again.
func TestSessionBoundaryAcrossInits(t *testing.T) {
	dir := t.TempDir()

	// First boot.
	if err := Init(dir, "warn"); err != nil {
		t.Fatalf("init #1: %v", err)
	}
	c := mustCore()
	_ = c.store.UpsertPublisher(routestore.PublisherRow{
		PublisherID:    "pub-x",
		DisplayName:    "X",
		TrustLevel:     "tofu",
		FirstSeen:      "2026-04-26T00:00:00Z",
		LastSeenBundle: "2026-04-26T00:00:00Z",
		KeyStatus:      "active",
	})
	_ = c.store.UpsertRoute(routestore.RouteRow{
		RouteID:         "r-em",
		TransportFamily: "vless-reality",
		Engine:          "sing-box",
		SourceType:      "imported",
		PublisherID:     "pub-x",
		TrustState:      "trusted",
		ScarcityClass:   "normal",
		ExpiresAt:       "2027-01-01T00:00:00Z",
		ImportedAt:      "2026-04-26T00:00:00Z",
	})
	if _, err := SetRouteBudget("r-em", "emergency"); err != nil {
		t.Fatalf("SetRouteBudget #1: %v", err)
	}
	eng1 := ensureBudget()
	if got := eng1.SessionEpoch(); got != 1 {
		t.Fatalf("session epoch after first init = %d, want 1", got)
	}
	// Charge enough to push the session counter forward; pin a known
	// non-zero value so we can detect a leak across the boundary.
	if err := eng1.Add("r-em", 25*budget.MiB); err != nil {
		t.Fatalf("Add #1: %v", err)
	}

	// Clean shutdown.
	if err := Shutdown(); err != nil {
		t.Fatalf("shutdown: %v", err)
	}

	// Second boot — same dir.
	if err := Init(dir, "warn"); err != nil {
		t.Fatalf("init #2: %v", err)
	}
	t.Cleanup(func() { Shutdown() })

	eng2 := ensureBudget()
	if eng2 == eng1 {
		t.Fatalf("ensureBudget returned the same engine across Shutdown/Init — singleton not reset")
	}
	if got := eng2.SessionEpoch(); got != 1 {
		t.Fatalf("session epoch on fresh engine after second init = %d, want 1", got)
	}
	// The fresh engine must report zero session_consumed for r-em
	// regardless of the persisted hourly counter (which is per-route
	// per-hour and unrelated to the session axis).
	for _, snap := range eng2.Snapshot() {
		if snap.RouteID == "r-em" && snap.SessionConsumed != 0 {
			t.Errorf("session counter leaked across Shutdown/Init: %+v", snap)
		}
	}
}

// === Phase 2B: mode wiring + posture + diagnostics widening ===

// TestSetModeWiresToBudgetEngine asserts that SetMode("lifeline")
// makes the budget engine's Snapshot return *effective* (0.33×) caps.
func TestSetModeWiresToBudgetEngine(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	_ = c.store.UpsertPublisher(routestore.PublisherRow{
		PublisherID:    "pub-x",
		DisplayName:    "X",
		TrustLevel:     "tofu",
		FirstSeen:      "2026-04-26T00:00:00Z",
		LastSeenBundle: "2026-04-26T00:00:00Z",
		KeyStatus:      "active",
	})
	_ = c.store.UpsertRoute(routestore.RouteRow{
		RouteID:         "r-em",
		TransportFamily: "vless-reality",
		Engine:          "sing-box",
		SourceType:      "imported",
		PublisherID:     "pub-x",
		TrustState:      "trusted",
		ScarcityClass:   "normal",
		ExpiresAt:       "2027-01-01T00:00:00Z",
		ImportedAt:      "2026-04-26T00:00:00Z",
	})
	if _, err := SetRouteBudget("r-em", "emergency"); err != nil {
		t.Fatalf("SetRouteBudget: %v", err)
	}
	eng := ensureBudget()
	// Default mode (normal) → hourly cap is the raw 50 MiB.
	for _, snap := range eng.Snapshot() {
		if snap.RouteID == "r-em" && snap.HourlyCap != 50*budget.MiB {
			t.Errorf("normal mode: hourly_cap = %d, want 50 MiB", snap.HourlyCap)
		}
	}

	if err := SetMode("lifeline"); err != nil {
		t.Fatalf("SetMode lifeline: %v", err)
	}
	wantHourly := uint64(float64(50*budget.MiB) * 0.33)
	for _, snap := range eng.Snapshot() {
		if snap.RouteID == "r-em" && snap.HourlyCap != wantHourly {
			t.Errorf("lifeline mode: hourly_cap = %d, want %d", snap.HourlyCap, wantHourly)
		}
	}
}

// TestSetModeFlipsToPostureLifelineWhenActive asserts that lifeline
// mode flips ImportedActive → Lifeline. Also asserts switching back
// to normal restores ImportedActive.
func TestSetModeFlipsToPostureLifelineWhenActive(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	// Drive posture into ImportedActive (legal: NoRoute → ImportedActive).
	if err := c.pm.SetPosture(pathmanager.EventImportedSelected, pathmanager.PostureImportedActive); err != nil {
		t.Fatalf("seed posture: %v", err)
	}
	if err := SetMode("lifeline"); err != nil {
		t.Fatal(err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureLifeline {
		t.Errorf("posture after lifeline mode = %q, want %q", got, pathmanager.PostureLifeline)
	}
	if err := SetMode("normal"); err != nil {
		t.Fatal(err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureImportedActive {
		t.Errorf("posture after normal mode = %q, want %q", got, pathmanager.PostureImportedActive)
	}
}

// TestSetModeRejectsLifelineStrict asserts that the 2D mode is NOT
// TestSetModeAcceptsLifelineStrict asserts the 2D widening: the
// engine_set_mode boundary now accepts `lifeline-strict`. The strict
// variant flips the posture into PostureLifeline (same as lifeline)
// and threads into the budget engine via SetMode (driving the same
// 0.33× multiplier).
func TestSetModeAcceptsLifelineStrict(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	if err := c.pm.SetPosture(pathmanager.EventImportedSelected, pathmanager.PostureImportedActive); err != nil {
		t.Fatalf("seed posture: %v", err)
	}

	if err := SetMode("lifeline-strict"); err != nil {
		t.Fatalf("expected SetMode(lifeline-strict) to be accepted at 2D, got: %v", err)
	}
	if got := Mode(); got != "lifeline-strict" {
		t.Fatalf("Mode() = %q, want lifeline-strict", got)
	}
	if c.pm.Posture() != pathmanager.PostureLifeline {
		t.Fatalf("posture = %v, want PostureLifeline", c.pm.Posture())
	}
}

// TestSetModeLifelineStrictDoesNotResetSession asserts the 2A-Polish
// rule continues to hold for the new mode: mode change MUST NOT bump
// the budget session epoch.
func TestSetModeLifelineStrictDoesNotResetSession(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	// Touch the budget engine to force instantiation + capture epoch.
	if _, err := SetRouteBudget("r-1", "normal"); err != nil {
		t.Fatal(err)
	}
	eng := budgetEngineIfPresent()
	if eng == nil {
		t.Fatal("budget engine not instantiated after SetRouteBudget")
	}
	before := eng.SessionEpoch()

	if err := SetMode("lifeline-strict"); err != nil {
		t.Fatal(err)
	}
	if after := eng.SessionEpoch(); after != before {
		t.Fatalf("session epoch changed across SetMode(lifeline-strict): %d → %d", before, after)
	}
}

// TestExportDiagnosticsCarriesPostureAndRouteHealth asserts the new
// 2B diagnostics fields are present.
func TestExportDiagnosticsCarriesPostureAndRouteHealth(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	c.pm.Failed("r-broken", "vless-reality", diagnostics.TCPReset)

	body, err := ExportDiagnostics()
	if err != nil {
		t.Fatal(err)
	}
	var blob struct {
		Posture         string                   `json:"posture"`
		RouteHealth     []map[string]interface{} `json:"route_health"`
		SkippedFamilies []map[string]interface{} `json:"skipped_families"`
	}
	if err := json.Unmarshal([]byte(body), &blob); err != nil {
		t.Fatalf("decode diagnostics: %v\n%s", err, body)
	}
	if blob.Posture != "NoRoute" {
		t.Errorf("posture = %q, want NoRoute (default)", blob.Posture)
	}
	// route_health[] must include r-broken with cooldown_reason tcp_reset.
	found := false
	for _, row := range blob.RouteHealth {
		if row["route_id"] == "r-broken" {
			found = true
			if row["cooldown_reason"] != "tcp_reset" {
				t.Errorf("cooldown_reason = %v, want tcp_reset", row["cooldown_reason"])
			}
			if row["in_cooldown"] != true {
				t.Errorf("in_cooldown = %v, want true", row["in_cooldown"])
			}
		}
	}
	if !found {
		t.Errorf("r-broken not in route_health[]: %+v", blob.RouteHealth)
	}
}

// TestModeChangeDoesNotResetSession asserts that engine_set_mode does
// NOT bump the session epoch. Mode change must not launder the
// per-session counter — that would let a user reset their cap by
// flipping modes.
func TestModeChangeDoesNotResetSession(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	_ = c.store.UpsertPublisher(routestore.PublisherRow{
		PublisherID:    "pub-x",
		DisplayName:    "X",
		TrustLevel:     "tofu",
		FirstSeen:      "2026-04-26T00:00:00Z",
		LastSeenBundle: "2026-04-26T00:00:00Z",
		KeyStatus:      "active",
	})
	_ = c.store.UpsertRoute(routestore.RouteRow{
		RouteID:         "r-em",
		TransportFamily: "vless-reality",
		Engine:          "sing-box",
		SourceType:      "imported",
		PublisherID:     "pub-x",
		TrustState:      "trusted",
		ScarcityClass:   "normal",
		ExpiresAt:       "2027-01-01T00:00:00Z",
		ImportedAt:      "2026-04-26T00:00:00Z",
	})
	if _, err := SetRouteBudget("r-em", "emergency"); err != nil {
		t.Fatal(err)
	}
	eng := ensureBudget()
	beforeEpoch := eng.SessionEpoch()
	if err := SetMode("lifeline"); err != nil {
		t.Fatal(err)
	}
	if err := SetMode("normal"); err != nil {
		t.Fatal(err)
	}
	if err := SetMode("bulk"); err != nil {
		t.Fatal(err)
	}
	if got := eng.SessionEpoch(); got != beforeEpoch {
		t.Errorf("session epoch advanced on mode change: before=%d after=%d", beforeEpoch, got)
	}
}

// === Gap 5: posture FSM tightening — wire dead producers ===

// seedExperimentalRoute inserts a publisher + a route on an
// experimental-maturity family (webtunnel) plus its sing-box outbound
// profile blob so SetRoute can drive Start through the stub.
func seedExperimentalRoute(t *testing.T, c *Core, routeID string) {
	t.Helper()
	if err := c.store.UpsertPublisher(routestore.PublisherRow{
		PublisherID:    "pub-exp",
		DisplayName:    "Exp",
		TrustLevel:     "tofu",
		FirstSeen:      "2026-05-29T00:00:00Z",
		LastSeenBundle: "2026-05-29T00:00:00Z",
		KeyStatus:      "active",
	}); err != nil {
		t.Fatalf("UpsertPublisher: %v", err)
	}
	if err := c.store.UpsertRoute(routestore.RouteRow{
		RouteID:         routeID,
		TransportFamily: "webtunnel",
		Engine:          "sing-box",
		SourceType:      "imported",
		PublisherID:     "pub-exp",
		TrustState:      "trusted",
		ScarcityClass:   "normal",
		ExpiresAt:       "2027-01-01T00:00:00Z",
		ImportedAt:      "2026-05-29T00:00:00Z",
	}); err != nil {
		t.Fatalf("UpsertRoute: %v", err)
	}
	// Minimal sing-box outbound JSON; BuildSingBoxConfig only checks
	// JSON validity and the absence of a tag, both of which this
	// satisfies.
	if err := c.store.PutSecret("route:"+routeID,
		[]byte(`{"type":"webtunnel","server":"example.invalid","server_port":443}`)); err != nil {
		t.Fatalf("PutSecret: %v", err)
	}
}

// seedStableRoute is the vless-reality (stable) twin of
// seedExperimentalRoute; used to assert the non-experimental branch.
func seedStableRoute(t *testing.T, c *Core, routeID string) {
	t.Helper()
	if err := c.store.UpsertPublisher(routestore.PublisherRow{
		PublisherID:    "pub-st",
		DisplayName:    "St",
		TrustLevel:     "tofu",
		FirstSeen:      "2026-05-29T00:00:00Z",
		LastSeenBundle: "2026-05-29T00:00:00Z",
		KeyStatus:      "active",
	}); err != nil {
		t.Fatalf("UpsertPublisher: %v", err)
	}
	if err := c.store.UpsertRoute(routestore.RouteRow{
		RouteID:         routeID,
		TransportFamily: "vless-reality",
		Engine:          "sing-box",
		SourceType:      "imported",
		PublisherID:     "pub-st",
		TrustState:      "trusted",
		ScarcityClass:   "normal",
		ExpiresAt:       "2027-01-01T00:00:00Z",
		ImportedAt:      "2026-05-29T00:00:00Z",
	}); err != nil {
		t.Fatalf("UpsertRoute: %v", err)
	}
	if err := c.store.PutSecret("route:"+routeID,
		[]byte(`{"type":"vless","server":"example.invalid","server_port":443}`)); err != nil {
		t.Fatalf("PutSecret: %v", err)
	}
}

// TestGap5_SetRouteExperimentalAdvancesToPostureExperimental — Gap 5:
// SetRoute on an experimental-family route from PostureNoRoute must
// advance the posture to PostureExperimental, not PostureImportedActive.
// This relies on the new {NoRoute, experimental_selected, Experimental}
// table edge.
func TestGap5_SetRouteExperimentalAdvancesToPostureExperimental(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	seedExperimentalRoute(t, c, "r-exp")

	if got := c.pm.Posture(); got != pathmanager.PostureNoRoute {
		t.Fatalf("seed posture = %s, want %s", got, pathmanager.PostureNoRoute)
	}
	if err := SetRoute("r-exp"); err != nil {
		t.Fatalf("SetRoute: %v", err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureExperimental {
		t.Fatalf("posture after SetRoute(experimental) = %s, want %s",
			got, pathmanager.PostureExperimental)
	}
}

// TestGap5_SetRouteStableStillAdvancesToImportedActive pins the
// non-experimental branch: a stable family must continue to land on
// PostureImportedActive (regression guard on the family-maturity
// branch).
func TestGap5_SetRouteStableStillAdvancesToImportedActive(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	seedStableRoute(t, c, "r-st")

	if err := SetRoute("r-st"); err != nil {
		t.Fatalf("SetRoute: %v", err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureImportedActive {
		t.Fatalf("posture after SetRoute(stable) = %s, want %s",
			got, pathmanager.PostureImportedActive)
	}
}

// TestGap5_ShareBeginEndDrivesOfflineSharingPosture — Gap 5:
// ShareBegin advances posture to PostureOfflineSharing; ShareEnd
// returns it to PostureImportedActive.
func TestGap5_ShareBeginEndDrivesOfflineSharingPosture(t *testing.T) {
	dir := t.TempDir()
	if err := Init(dir, "warn"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { Shutdown() })

	c := mustCore()
	seedStableRoute(t, c, "r-share")
	// ShareBegin requires the route's profile blob, which seedStableRoute already wrote.

	// Begin a share from NoRoute. The new edge {NoRoute,
	// offline_share_start, OfflineSharing} is exercised here.
	out, err := ShareBegin("r-share", false, "")
	if err != nil {
		t.Fatalf("ShareBegin: %v", err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureOfflineSharing {
		t.Fatalf("posture after ShareBegin = %s, want %s",
			got, pathmanager.PostureOfflineSharing)
	}
	// Pull session id out of the JSON response.
	var resp map[string]any
	if err := json.Unmarshal([]byte(out), &resp); err != nil {
		t.Fatalf("parse ShareBegin response: %v", err)
	}
	sid, _ := resp["session_id"].(string)
	if sid == "" {
		t.Fatalf("ShareBegin returned no session_id: %s", out)
	}

	if err := ShareEnd(sid); err != nil {
		t.Fatalf("ShareEnd: %v", err)
	}
	if got := c.pm.Posture(); got != pathmanager.PostureImportedActive {
		t.Fatalf("posture after ShareEnd = %s, want %s",
			got, pathmanager.PostureImportedActive)
	}
}

// TestGap5_PostureTableAllowsNoRouteActiveFailedToRecovery pins the
// new {NoRoute, active_failed, Recovery} table edge. Before this
// edge, a first-attempt SetRoute that failed silently no-op'd at
// abi.go's "ignored illegal" branch and the posture stayed at
// NoRoute.
func TestGap5_PostureTableAllowsNoRouteActiveFailedToRecovery(t *testing.T) {
	if !pathmanager.IsLegal(pathmanager.PostureNoRoute,
		pathmanager.EventActiveFailed, pathmanager.PostureRecovery) {
		t.Fatal("{NoRoute, active_failed, Recovery} must be legal")
	}
}

// TestGap5_PostureTableAllowsNoRouteDirectoryFetchedToImportedActive
// pins the new edge that lets a cold-start BootstrapRefresh advance
// posture without requiring a preceding BootstrapStart.
func TestGap5_PostureTableAllowsNoRouteDirectoryFetchedToImportedActive(t *testing.T) {
	if !pathmanager.IsLegal(pathmanager.PostureNoRoute,
		pathmanager.EventDirectoryFetched, pathmanager.PostureImportedActive) {
		t.Fatal("{NoRoute, directory_fetched, ImportedActive} must be legal")
	}
}

// TestGap5_PostureTableAllowsNoRouteExperimentalSelectedToExperimental
// pins the new edge that lets an Experimental-family route be the
// very first connection of a session.
func TestGap5_PostureTableAllowsNoRouteExperimentalSelectedToExperimental(t *testing.T) {
	if !pathmanager.IsLegal(pathmanager.PostureNoRoute,
		pathmanager.EventExperimentalSelected, pathmanager.PostureExperimental) {
		t.Fatal("{NoRoute, experimental_selected, Experimental} must be legal")
	}
}
