// Command relaypack-fixtures generates the FRP-1 seed test-vector
// corpus for the RelayPack profile validator.
//
// Output goes to specs/test-vectors/relaypack/. Each vector is a
// pair: <name>.sbp (the sealed archive) and <name>.expected.json
// (the per-phase expected validator outcome, generated by
// replaying Validate against the just-built bundle). These two
// files are the FRP-1 spec contract and ARE tracked in git.
//
// A pretty-printed <name>.manifest.json companion is written ONLY
// when -emit-manifest-json is passed. Those files are review-only
// helpers, regenerable on demand, NOT part of the FRP-1 spec
// contract, NOT tracked in git (see .gitignore), and trigger
// spurious secret-scanner alerts on the test publisher key
// fingerprint, which is why they default to off.
//
// Determinism: the binary uses a fixed seed-derived publisher
// keypair and fixed RFC3339 timestamps so the output bytes are
// stable across runs. Ed25519 signatures are deterministic per
// (key, message); pinning the timestamps in the manifest pins the
// message and therefore pins the signature.
//
// Usage (from repo root):
//
//	cd publisher && go run ./cmd/relaypack-fixtures
//	cd publisher && go run ./cmd/relaypack-fixtures -emit-manifest-json
package main

import (
	"bytes"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"daal/bundle-go/bundle"
	relaypack "daal/bundle-go/relaypackvalidate"
)

var emitManifestJSON = flag.Bool(
	"emit-manifest-json",
	false,
	"also write <name>.manifest.json (pretty-printed manifest, review-only, untracked, not part of the FRP-1 spec contract)",
)

const (
	pinnedValidFrom  = "2026-01-01T00:00:00Z"
	pinnedValidUntil = "2027-01-01T00:00:00Z"
	pinnedCreatedAt  = "2026-01-01T00:00:00Z"
	pinnedExpiresAt  = "2027-01-01T00:00:00Z"
)

// outDir resolves to specs/test-vectors/relaypack relative to the
// publisher module root (the binary is run from publisher/).
func outDir() string {
	wd, err := os.Getwd()
	if err != nil {
		log.Fatalf("cwd: %v", err)
	}
	return filepath.Join(wd, "..", "specs", "test-vectors", "relaypack")
}

// deterministicKeypair derives a pinned Ed25519 keypair from a
// fixed seed. NEVER use this key for anything but test fixtures.
func deterministicKeypair() (ed25519.PublicKey, ed25519.PrivateKey) {
	seed := sha256.Sum256([]byte("daal-frp-1-fixture-seed"))
	priv := ed25519.NewKeyFromSeed(seed[:])
	pub := priv.Public().(ed25519.PublicKey)
	return pub, priv
}

func mustMarshal(v any) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		log.Fatalf("marshal: %v", err)
	}
	return b
}

type expectedOutcome struct {
	Phase    string   `json:"phase"`
	Pass     bool     `json:"pass"`
	ErrCode  string   `json:"error_code,omitempty"`
	Warnings []string `json:"warnings,omitempty"` // codes only, sorted
}

type expectedFile struct {
	Vector   string            `json:"vector"`
	Purpose  string            `json:"purpose"`
	Outcomes []expectedOutcome `json:"outcomes"`
}

func writeFile(path string, body []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		log.Fatalf("mkdir %s: %v", path, err)
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
}

// buildVector seals a manifest into a .sbp, runs the validator
// against each phase, and writes all three artefacts.
func buildVector(name, purpose string, m bundle.Manifest, profiles map[string][]byte) {
	pub, priv := deterministicKeypair()
	m.Publisher.KeyFingerprintHex = bundle.PublisherFingerprint(pub).Hex
	if profiles == nil {
		profiles = map[string][]byte{
			"profiles/route.json": []byte(`{"type":"direct"}`),
		}
	}

	dir := outDir()

	// 1. Sealed .sbp (the FRP-1 spec contract; tracked in git).
	//    Use the deterministic builder: ZIP entries are sorted by
	//    name, mtime is zeroed, and Store (no compression) is used,
	//    which makes the output byte-stable across regenerations.
	data, err := bundle.BuildSignedBundleDeterministic(m, profiles, nil, pub, priv)
	if err != nil {
		log.Fatalf("%s: build sealed: %v", name, err)
	}
	writeFile(filepath.Join(dir, name+".sbp"), data)

	// 2. Optional pretty-printed manifest for human review.
	//    Off by default (see -emit-manifest-json). Untracked.
	if *emitManifestJSON {
		manifestJSON, err := json.MarshalIndent(m, "", "  ")
		if err != nil {
			log.Fatalf("%s: marshal: %v", name, err)
		}
		writeFile(filepath.Join(dir, name+".manifest.json"), manifestJSON)
	}

	// 3. Expected outcomes per phase.
	expected := expectedFile{Vector: name, Purpose: purpose}
	phases := []relaypack.Phase{relaypack.PhaseV15, relaypack.PhaseV16, relaypack.PhasePostV2}
	for _, ph := range phases {
		opts := relaypack.ValidateOpts{Phase: ph}
		if ph == relaypack.PhasePostV2 {
			// Allow client_desync at PostV2 so the modifier-rejected
			// vector flips to OK.
			opts.AllowedModifierKinds = map[string]bool{
				"client_desync": true,
				"tls_fragment":  true,
			}
		}
		// Re-parse from the sealed bytes so we exercise the full
		// flow, not the in-memory struct.
		b, err := bundle.ParseSBP(bytes.NewReader(data), int64(len(data)))
		if err != nil {
			log.Fatalf("%s: parse sealed: %v", name, err)
		}
		report, vErr := relaypack.Validate(b, opts)
		out := expectedOutcome{Phase: string(ph), Pass: vErr == nil}
		if vErr != nil {
			if ve, ok := vErr.(*relaypack.ValidationError); ok {
				out.ErrCode = string(ve.Code)
			} else {
				out.ErrCode = vErr.Error()
			}
		}
		for _, w := range report.Warnings {
			out.Warnings = append(out.Warnings, string(w.Code))
		}
		expected.Outcomes = append(expected.Outcomes, out)
	}
	body, err := json.MarshalIndent(expected, "", "  ")
	if err != nil {
		log.Fatalf("%s: marshal expected: %v", name, err)
	}
	writeFile(filepath.Join(dir, name+".expected.json"), body)
	fmt.Printf("ok  %s\n", name)
}

func basePub() bundle.PublisherInfo {
	return bundle.PublisherInfo{
		Name:         "Daal FRP-1 Fixture Publisher",
		KeyCreatedAt: pinnedCreatedAt,
		TrustClass:   "unknown",
	}
}

func baseBundle(id string) bundle.BundleInfo {
	return bundle.BundleInfo{
		ID:             id,
		Type:           "provider",
		CreatedAt:      pinnedCreatedAt,
		ExpiresAt:      pinnedExpiresAt,
		SupersedesKeys: []string{},
	}
}

// route returns a base RouteManifestEntry; callers patch
// FamilySpecificConfig and TransportFamily as needed.
func route(id, family string) bundle.RouteManifestEntry {
	return bundle.RouteManifestEntry{
		ID:              id,
		ScarcityClass:   "normal",
		TransportFamily: family,
		ConfigPath:      "profiles/route.json",
		ValidFrom:       pinnedValidFrom,
		ValidUntil:      pinnedValidUntil,
	}
}

// rpEntry packs a RelayPackEntry into a FamilySpecificConfig blob,
// optionally adding sibling keys (e.g. legacy shared_risk_tags).
//
// FRP-8: cdn_fronted entries auto-include a passing
// _cdn_attestation unless the test supplied one in `extras`. This
// preserves the V1.6 positive-path corpus across the RP022/RP023
// validator widening landed in commit 4/8.
func rpEntry(e bundle.RelayPackEntry, extras map[string]any) json.RawMessage {
	m := map[string]any{"_relaypack": e}
	if _, hasAtt := extras["_cdn_attestation"]; !hasAtt && e.ExposureMode == "cdn_fronted" {
		m["_cdn_attestation"] = bundle.CDNAttestation{
			OriginCAFingerprint: "abababababababababababababababababababababababababababababababab",
			AOPEnabled:          true,
			FirewallID:          "fw-frp1-fixture",
			DNSOnlyPresent:      false,
		}
	}
	for k, v := range extras {
		m[k] = v
	}
	return mustMarshal(m)
}

// ---- vectors ---------------------------------------------------

func directVPSMinimal() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-direct-vps-minimal"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID: "rp-frp1-direct-vps-minimal",
			SharedRiskGraph: []bundle.SharedRiskEdge{
				{Tag: "public_ip:5.75.0.1", Members: []string{"r1", "r2"}},
				{Tag: "public_port:tcp443", Members: []string{"r1", "r2"}},
			},
		},
	}
	buildVector("direct-vps-minimal",
		"Two direct_vps vps-native candidates with no public-surface diversity.",
		m, nil)
}

func directVPSWithSNI() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags: []string{
			"public_ip:5.75.0.1",
			"public_port:tcp443",
			"public_domain:host.example.com",
			"host:host.example.com",
			"sni:www.microsoft.com",
		},
		OriginRiskTags: []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	r2 := route("r2", "websocket-tls")
	rp2 := rp
	rp2.PublicRiskTags = []string{"public_ip:1.2.3.4", "public_port:tcp443", "public_domain:other.example.com"}
	r2.FamilySpecificConfig = rpEntry(rp2, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-direct-vps-with-sni"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp1-direct-vps-with-sni",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("direct-vps-with-sni",
		"direct_vps candidates carrying public_domain:, host:, and sni: tags (legitimate visible domain on own VPS).",
		m, nil)
}

func cdnFrontedMinimal() {
	cdn := bundle.RelayPackEntry{
		ExposureMode:     "cdn_fronted",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"cdn:cloudflare", "public_domain:e.example.com"},
		OriginRiskTags:   []string{"origin_ip:5.75.0.1"},
	}
	direct := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "websocket-tls")
	r1.FamilySpecificConfig = rpEntry(cdn, nil)
	r2 := route("r2", "vless-reality")
	r2.FamilySpecificConfig = rpEntry(direct, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-cdn-fronted-minimal"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp1-cdn-fronted-minimal",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("cdn-fronted-minimal",
		"One cdn_fronted + one direct_vps with minimal cdn:* and origin_* tags. Rejected at V15 (RP004), accepted at V16+.",
		m, nil)
}

func cdnFrontedWithOrigin() {
	cdn := bundle.RelayPackEntry{
		ExposureMode:     "cdn_fronted",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags: []string{
			"cdn:cloudflare",
			"public_domain:e.example.com",
			"sni:e.example.com",
			"host:e.example.com",
			"ws_path_fp:sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
		},
		OriginRiskTags: []string{
			"origin_ip:5.75.0.1",
			"origin_asn:24940",
			"origin_provider:hetzner",
			"origin_dc:fsn1",
			"origin_cert:cloudflare_origin_ca",
		},
	}
	direct := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443", "public_provider:hetzner"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "websocket-tls")
	r1.FamilySpecificConfig = rpEntry(cdn, nil)
	r2 := route("r2", "vless-reality")
	r2.FamilySpecificConfig = rpEntry(direct, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-cdn-fronted-with-origin"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID: "rp-frp1-cdn-fronted-with-origin",
			SharedRiskGraph: []bundle.SharedRiskEdge{
				{Tag: "cdn:cloudflare", Members: []string{"r1"}},
				{Tag: "public_provider:hetzner", Members: []string{"r2"}},
				{Tag: "origin_ip:5.75.0.1", Members: []string{"r1"}},
			},
		},
	}
	buildVector("cdn-fronted-with-origin",
		"cdn_fronted candidate with full origin_risk_tags array. Rejected at V15 (RP004), accepted at V16+.",
		m, nil)
}

func modifierRejected() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
		Modifiers: []bundle.Modifier{
			{Kind: "client_desync", Platform: "linux_desktop_only", ProbingRiskClass: "high"},
		},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)

	rp2 := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp2, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-modifier-rejected"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp1-modifier-rejected",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("modifier-rejected",
		"Candidate with non-empty modifiers[client_desync]. Rejected at V15/V16 (RP013); accepted at PostV2 only when client_desync is in AllowedModifierKinds.",
		m, nil)
}

func legacyFlatTagsRejected() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, map[string]any{
		"shared_risk_tags": []string{"legacy:hetzner", "legacy:fsn1"},
	})
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp, nil)

	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp1-legacy-flat-tags-rejected"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp1-legacy-flat-tags-rejected",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("legacy-flat-tags-rejected",
		"Candidate with pre-v2.3.4 flat shared_risk_tags array. Always rejected with RP017.",
		m, nil)
}

// ---- FRP-2 expansion (10 new vectors; total 16) ---------------

// legacyNonRelayPack: bundle with no _relaypack and no
// Manifest.RelayPack slot. Validator is inert; importer takes
// the legacy path with sentinel-empty RouteRow columns.
func legacyNonRelayPack() {
	r1 := route("r1", "vless-reality")
	r2 := route("r2", "naive")
	m := bundle.Manifest{
		SpecVersion: 1, // pre-FRP-1
		Publisher:   basePub(),
		Bundle:      baseBundle("frp2-legacy-non-relaypack"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		// RelayPack: nil — no slot.
	}
	buildVector("legacy-non-relaypack",
		"Bundle with no _relaypack and no Manifest.relay_pack slot. Validator is inert; importer takes legacy path with sentinel-empty RouteRow columns.",
		m, nil)
}

// mixedRelayPackDirectOnly: three direct_vps siblings on one VPS.
// V1.5-positive; demonstrates the single-VPS-multiple-candidates
// shape FRP-2 unblocks.
func mixedRelayPackDirectOnly() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp, nil)
	r3 := route("r3", "websocket-tls")
	r3.FamilySpecificConfig = rpEntry(rp, nil)
	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp2-mixed-relaypack-direct-only"),
		Routes:      []bundle.RouteManifestEntry{r1, r2, r3},
		RelayPack: &bundle.RelayPack{
			RelayPackID: "rp-frp2-mixed-direct-only",
			SharedRiskGraph: []bundle.SharedRiskEdge{
				{Tag: "public_ip:5.75.0.1", Members: []string{"r1", "r2", "r3"}},
				{Tag: "public_port:tcp443", Members: []string{"r1", "r2", "r3"}},
			},
		},
	}
	buildVector("mixed-relaypack-direct-only",
		"Three direct_vps siblings on a single VPS. V1.5-positive single-VPS multi-candidate shape.",
		m, nil)
}

// mixedRelayPackDirectAndCDN: V1.6 candidate alongside a direct.
// V1.5 importer rejects with RP004 (the cdn_fronted candidate
// fails phase gate).
func mixedRelayPackDirectAndCDN() {
	cdn := bundle.RelayPackEntry{
		ExposureMode:     "cdn_fronted",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"cdn:cloudflare", "public_domain:e.example.com"},
		OriginRiskTags:   []string{"origin_ip:5.75.0.1"},
	}
	d1 := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	d2 := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:1.2.3.4", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "websocket-tls")
	r1.FamilySpecificConfig = rpEntry(cdn, nil)
	r2 := route("r2", "vless-reality")
	r2.FamilySpecificConfig = rpEntry(d1, nil)
	r3 := route("r3", "naive")
	r3.FamilySpecificConfig = rpEntry(d2, nil)
	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp2-mixed-relaypack-direct-and-cdn"),
		Routes:      []bundle.RouteManifestEntry{r1, r2, r3},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-mixed-direct-and-cdn",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("mixed-relaypack-direct-and-cdn",
		"Mixed cdn_fronted + 2 direct_vps. V1.5 rejects (RP004). V1.6 accepts.",
		m, nil)
}

// idempotentReimport: byte-equivalent to direct-vps-minimal but
// labelled separately. Importer-side proves re-import yields equal
// rows. Validator outcome is the same as direct-vps-minimal.
func idempotentReimport() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp, nil)
	m := bundle.Manifest{
		SpecVersion: 3,
		Publisher:   basePub(),
		Bundle:      baseBundle("frp2-idempotent-reimport"),
		Routes:      []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID: "rp-frp2-idempotent",
			SharedRiskGraph: []bundle.SharedRiskEdge{
				{Tag: "public_ip:5.75.0.1", Members: []string{"r1", "r2"}},
			},
		},
	}
	buildVector("idempotent-reimport",
		"Direct-vps minimal twin. Importer-side proves re-import yields equal rows.",
		m, nil)
}

// cdnFrontedNoCDNTagRejected: V1.6 RP005 (no cdn:* tag).
// V1.5 hits RP004 first (cdn_fronted phase gate).
func cdnFrontedNoCDNTagRejected() {
	cdn := bundle.RelayPackEntry{
		ExposureMode:     "cdn_fronted",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		// missing cdn:* tag → RP005 at V1.6
		PublicRiskTags: []string{"public_domain:e.example.com"},
		OriginRiskTags: []string{"origin_ip:5.75.0.1"},
	}
	d := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "websocket-tls")
	r1.FamilySpecificConfig = rpEntry(cdn, nil)
	r2 := route("r2", "vless-reality")
	r2.FamilySpecificConfig = rpEntry(d, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-cdn-fronted-no-cdn-tag-rejected"),
		Routes: []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-cdn-no-cdn-tag",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("cdn-fronted-no-cdn-tag-rejected",
		"cdn_fronted candidate missing cdn:* tag. V1.5 rejects RP004; V1.6 rejects RP005.",
		m, nil)
}

// cdnFrontedNoOriginTagRejected: V1.6 RP006 (no origin_* tag).
// V1.5 hits RP004 first.
func cdnFrontedNoOriginTagRejected() {
	cdn := bundle.RelayPackEntry{
		ExposureMode:     "cdn_fronted",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"cdn:cloudflare", "public_domain:e.example.com"},
		OriginRiskTags:   []string{}, // missing origin_* → RP006 at V1.6
	}
	d := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "websocket-tls")
	r1.FamilySpecificConfig = rpEntry(cdn, nil)
	r2 := route("r2", "vless-reality")
	r2.FamilySpecificConfig = rpEntry(d, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-cdn-fronted-no-origin-tag-rejected"),
		Routes: []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-cdn-no-origin-tag",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("cdn-fronted-no-origin-tag-rejected",
		"cdn_fronted candidate missing origin_* tag. V1.5 rejects RP004; V1.6 rejects RP006.",
		m, nil)
}

// directVPSWithCDNTagRejected: RP009 — direct_vps must NOT carry
// cdn:* tag. Hits at all phases.
func directVPSWithCDNTagRejected() {
	bad := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "cdn:cloudflare"},
		OriginRiskTags:   []string{},
	}
	good := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:1.2.3.4"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(bad, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(good, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-direct-vps-with-cdn-tag-rejected"),
		Routes: []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-direct-with-cdn-tag",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("direct-vps-with-cdn-tag-rejected",
		"direct_vps candidate carrying cdn:* tag (mode mismatch). RP009 at all phases.",
		m, nil)
}

// directVPSWithOriginTagRejected: RP010 — direct_vps must NOT
// carry origin_* tag. All phases.
func directVPSWithOriginTagRejected() {
	bad := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1"},
		OriginRiskTags:   []string{"origin_ip:5.75.0.1"},
	}
	good := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:1.2.3.4"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(bad, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(good, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-direct-vps-with-origin-tag-rejected"),
		Routes: []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-direct-with-origin-tag",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("direct-vps-with-origin-tag-rejected",
		"direct_vps candidate carrying origin_* tag (in direct mode the origin IS the public surface). RP010 at all phases.",
		m, nil)
}

// singleCandidateRelayPackRejected: RP014 — bundle must contain
// >= 2 vps-native candidates. All phases.
func singleCandidateRelayPackRejected() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-single-candidate-relaypack-rejected"),
		Routes: []bundle.RouteManifestEntry{r1},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-single",
			SharedRiskGraph: []bundle.SharedRiskEdge{},
		},
	}
	buildVector("single-candidate-relaypack-rejected",
		"One vps-native candidate. RP014 at all phases (>=2 required).",
		m, nil)
}

// bundleWithFreshnessURLV15Rejected: RP021 — non-empty
// freshness_url at V1.5 is rejected. V1.6 + PostV2 accept.
func bundleWithFreshnessURLV15Rejected() {
	rp := bundle.RelayPackEntry{
		ExposureMode:     "direct_vps",
		FamilyClass:      "vps-native",
		ProbingRiskClass: "low",
		PublicRiskTags:   []string{"public_ip:5.75.0.1", "public_port:tcp443"},
		OriginRiskTags:   []string{},
	}
	r1 := route("r1", "vless-reality")
	r1.FamilySpecificConfig = rpEntry(rp, nil)
	r2 := route("r2", "naive")
	r2.FamilySpecificConfig = rpEntry(rp, nil)
	m := bundle.Manifest{
		SpecVersion: 3, Publisher: basePub(),
		Bundle: baseBundle("frp2-bundle-with-freshness-url-v15-rejected"),
		Routes: []bundle.RouteManifestEntry{r1, r2},
		RelayPack: &bundle.RelayPack{
			RelayPackID:     "rp-frp2-freshness-url",
			FreshnessURL:    "https://frp.example.com/relaypack.json",
			SharedRiskGraph: []bundle.SharedRiskEdge{{Tag: "public_ip:5.75.0.1", Members: []string{"r1", "r2"}}},
		},
	}
	buildVector("bundle-with-freshness-url-v15-rejected",
		"Non-empty Manifest.relay_pack.freshness_url at V1.5. Rejected RP021; V1.6 accepts (FRP-8 lifts).",
		m, nil)
}

func main() {
	flag.Parse()
	// FRP-1 seeds (6).
	directVPSMinimal()
	directVPSWithSNI()
	cdnFrontedMinimal()
	cdnFrontedWithOrigin()
	modifierRejected()
	legacyFlatTagsRejected()
	// FRP-2 expansion (10).
	legacyNonRelayPack()
	mixedRelayPackDirectOnly()
	mixedRelayPackDirectAndCDN()
	idempotentReimport()
	cdnFrontedNoCDNTagRejected()
	cdnFrontedNoOriginTagRejected()
	directVPSWithCDNTagRejected()
	directVPSWithOriginTagRejected()
	singleCandidateRelayPackRejected()
	bundleWithFreshnessURLV15Rejected()
	fmt.Println("done")
}
