package relaypack

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"daal/publisher/deploy/relayports"
)

// -update-family-matrix regenerates testdata/client_outbounds.json.
// Regenerating is meant to be a deliberate act with a diff to read: the
// file is the contract two OTHER modules check themselves against, and a
// change to it is a change to the wire.
var updateFamilyMatrix = flag.Bool("update-family-matrix", false,
	"rewrite testdata/client_outbounds.json from the current renderer")

// familyMatrixPath is also hard-coded, relative to their own package
// directories, in:
//
//	core/engine/client_outbound_matrix_singbox_test.go   (does sing-box parse it?)
//	cmd/daal-relay-mgmt/box_client_agreement_test.go     (does the box agree with it?)
//
// If this file moves, both break loudly, which is the intent — a
// silently unread cross-check is worse than none.
const familyMatrixPath = "testdata/client_outbounds.json"

// matrixEntry is one family's rendered client half.
type matrixEntry struct {
	Port     int             `json:"port"`
	UDP      bool            `json:"udp"`
	Outbound json.RawMessage `json:"outbound"`
}

type familyMatrix struct {
	Doc      string                 `json:"doc"`
	Params   ClientConnParams       `json:"params"`
	Families map[string]matrixEntry `json:"families"`
}

const familyMatrixDoc = "Generated by publisher/deploy/relaypack TestClientOutboundMatrixIsCurrent " +
	"(go test ./deploy/relaypack -run TestClientOutboundMatrixIsCurrent -update-family-matrix). " +
	"Every entry is the REAL output of ClientOutboundForFamily for the fixed params below, at the " +
	"port relayports.For reports. It exists because the three halves of a transport family live in " +
	"three Go modules that cannot import each other: the publisher mints the client outbound, " +
	"cmd/daal-relay-mgmt serves the box inbound, and core/engine dials it. This file is the seam " +
	"they all check themselves against, so a family cannot mint a config the box does not serve or " +
	"sing-box will not parse. Do not hand-edit."

// familyMatrixParams are the fixed inputs. Every credential is a
// structurally VALID value for its family — SS-2022 PSKs really are
// padded base64-std of 16 bytes, the anytls password really is the
// box's per-recipient secret shape — because a placeholder that is only
// the right length proves the renderer wired a string through, while a
// structurally valid one also proves the consumers agree on the format.
func familyMatrixParams() ClientConnParams {
	return ClientConnParams{
		Server:           "78.47.152.16",
		Name:             "r1",
		VLESSUUID:        "11111111-2222-3333-4444-555555555555",
		RealityShortID:   "deadbeef",
		RealityPublicKey: "0vmceLH_-1xDCVW1dKhUKNw0mof6qoIGLOhMyF6eN28",
		Hy2Password:      "hy2secretpassword22ch",
		NaivePassword:    "naivesecretpassword22",
		WSPath:           "/r1/cafebabe",
		TLSCertSHA256:    "c3BraS1zaGEyNTYtcGluLWJhc2U2NC12YWx1ZS14eHg=",
		TLSCertPEM:       testCertPEM,
		CoverSNI:         "cdn.example-host.net",
		TUICUUID:         "99999999-8888-7777-6666-555555555555",
		TUICPassword:     "tuicsecretpassword22c",
		// "<box iPSK>:<recipient uPSK>", assembled by the box and
		// carried verbatim; both halves are padded base64-std of 16
		// bytes, which is what 2022-blake3-aes-128-gcm requires.
		SSPassword:     "bW9jay1ib3gtaXBzay0xNg==:bW9jay11c2VyLXVwc2sxNg==",
		SSMethod:       "2022-blake3-aes-128-gcm",
		AnyTLSPassword: "YW55dGxzLXBlci1yZWNpcGllbnQtcGFzc3dvcmQtMzJi",
		Multiplex: map[string]MuxPolicy{
			"vless-reality": {Enabled: true, MaxStreams: 64},
			"websocket-tls": {Enabled: true, MaxStreams: 64},
		},
	}
}

// relayServedFamilies is the box's side of the contract: the families a
// provisioned Daal relay actually stands a listener up for. vless-reality
// and hysteria2 come from cloud-init, naive/websocket-tls/shadowsocks/
// anytls are created by cmd/daal-relay-mgmt on first recipient, and tuic
// is cloud-init when the toolbox profile selects it.
//
// It is spelled out rather than derived so that adding a family is a
// decision someone made on purpose. The test below asserts it matches
// exactly the set of families this renderer can mint — in BOTH
// directions, because both failures are real:
//
//   - a family the relay serves but nothing can mint is a listener with
//     no users, i.e. an open port that only helps a scanner;
//   - a family this renderer mints but the relay does not serve is the
//     outcome this wave forbids outright — a route the recipient will
//     select and lose.
var relayServedFamilies = []string{
	"anytls",
	"hysteria2",
	"naive",
	"shadowsocks",
	"tuic",
	"vless-reality",
	"websocket-tls",
}

// TestClientOutboundMatrixIsCurrent renders every servable family and
// asserts the checked-in matrix still matches byte for byte.
func TestClientOutboundMatrixIsCurrent(t *testing.T) {
	p := familyMatrixParams()

	// Everything relayports declares, so a new family joins this matrix
	// the moment it has both a port and a renderer — no second edit.
	mintable := map[string]matrixEntry{}
	for _, f := range relayports.Declared() {
		ep := relayports.For(f)
		raw, err := ClientOutboundForFamily(f, ep.Port, p)
		if err != nil {
			continue // no client renderer for this family
		}
		var canon any
		if err := json.Unmarshal(raw, &canon); err != nil {
			t.Fatalf("%s: renderer emitted invalid JSON: %v", f, err)
		}
		pretty, err := json.Marshal(canon)
		if err != nil {
			t.Fatalf("%s: %v", f, err)
		}
		mintable[f] = matrixEntry{Port: ep.Port, UDP: ep.UDP, Outbound: pretty}
	}

	got := make([]string, 0, len(mintable))
	for f := range mintable {
		got = append(got, f)
	}
	sort.Strings(got)
	want := append([]string(nil), relayServedFamilies...)
	sort.Strings(want)
	if len(got) != len(want) {
		t.Errorf("mintable families %v != served families %v", got, want)
	} else {
		for i := range got {
			if got[i] != want[i] {
				t.Errorf("mintable families %v != served families %v", got, want)
				break
			}
		}
	}

	body, err := json.MarshalIndent(familyMatrix{
		Doc:      familyMatrixDoc,
		Params:   p,
		Families: mintable,
	}, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	body = append(body, '\n')

	if *updateFamilyMatrix {
		if err := os.MkdirAll(filepath.Dir(familyMatrixPath), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(familyMatrixPath, body, 0o644); err != nil {
			t.Fatal(err)
		}
		t.Logf("wrote %s", familyMatrixPath)
		return
	}

	onDisk, err := os.ReadFile(familyMatrixPath)
	if err != nil {
		t.Fatalf("read %s: %v (regenerate with -update-family-matrix)", familyMatrixPath, err)
	}
	if !bytes.Equal(bytes.TrimSpace(onDisk), bytes.TrimSpace(body)) {
		t.Errorf("%s is stale.\n\nThe client outbound renderer changed and two other modules "+
			"check themselves against this file: core/engine parses it with the real sing-box "+
			"decoder, and cmd/daal-relay-mgmt asserts the box inbound agrees with it. Regenerate "+
			"with:\n\n  go test ./deploy/relaypack -run TestClientOutboundMatrixIsCurrent "+
			"-update-family-matrix\n\nand READ the diff — a change here is a change to the wire.",
			familyMatrixPath)
	}
}

// TestClientOutboundPortsComeFromRelayPorts pins the other half of the
// port seam. The matrix records a port per family; it must be the port
// relayports declares, or the client dials somewhere the firewall never
// opened and the box never bound.
func TestClientOutboundPortsComeFromRelayPorts(t *testing.T) {
	raw, err := os.ReadFile(familyMatrixPath)
	if err != nil {
		t.Fatalf("read %s: %v", familyMatrixPath, err)
	}
	var m familyMatrix
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse %s: %v", familyMatrixPath, err)
	}
	if len(m.Families) == 0 {
		t.Fatal("matrix has no families")
	}
	for family, e := range m.Families {
		ep := relayports.For(family)
		if e.Port != ep.Port || e.UDP != ep.UDP {
			t.Errorf("%s: matrix says %d (udp=%v), relayports says %d (udp=%v)",
				family, e.Port, e.UDP, ep.Port, ep.UDP)
		}
		var ob map[string]any
		if err := json.Unmarshal(e.Outbound, &ob); err != nil {
			t.Fatalf("%s: %v", family, err)
		}
		port, ok := ob["server_port"].(float64)
		if !ok {
			t.Errorf("%s: outbound has no numeric server_port", family)
			continue
		}
		if int(port) != ep.Port {
			t.Errorf("%s: outbound dials %d but relayports declares %d", family, int(port), ep.Port)
		}
		if tag, _ := ob["tag"].(string); tag != "active" {
			t.Errorf("%s: tag = %q, want \"active\" (route.final expects it)", family, tag)
		}
	}
}
