package fountain

import (
	"bytes"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// The golden fixture is the sender/receiver compatibility contract for
// the QR-fountain lane. It is produced by the REAL encoder here and
// consumed by two independent decoders:
//
//	Go: TestGoldenFramesDecodeToPayload below, via the real Decoder.
//	TS: client-ui/src/recipient/frames.test.ts, which base64url-decodes
//	    every frame in JS and asserts the bytes match frames_hex.
//
// Together those prove that what the publisher's encoder emits is
// byte-for-byte what the recipient UI forwards to the engine — without
// a camera, a second phone, or a running app.
const goldenPath = "testdata/fountain_frames_v1.json"

type goldenFixture struct {
	Comment      []string `json:"_comment"`
	PayloadHex   string   `json:"payload_hex"`
	BlockSize    int      `json:"block_size"`
	Seed         int64    `json:"seed"`
	SourceBlocks int      `json:"source_blocks"`
	FramesB64URL []string `json:"frames_b64url"`
	FramesHex    []string `json:"frames_hex"`
}

var updateGolden = flag.Bool("update-golden", false, "rewrite testdata/fountain_frames_v1.json")

// deterministicPayload builds a payload without math/rand so the
// fixture is reproducible across Go versions and platforms forever.
// (A plain LCG; this is test data, not key material.)
func deterministicPayload(n int) []byte {
	out := make([]byte, n)
	x := uint32(0x9E3779B9)
	for i := range out {
		x = x*1664525 + 1013904223
		out[i] = byte(x >> 24)
	}
	return out
}

const (
	goldenPayloadLen = 512
	goldenBlockSize  = 64
	goldenSeed       = int64(20260817)
)

// buildGolden runs the real encoder and collects exactly the frames the
// real decoder needs to finish.
func buildGolden(t *testing.T) goldenFixture {
	t.Helper()
	payload := deterministicPayload(goldenPayloadLen)
	enc := NewEncoder(payload, goldenBlockSize, goldenSeed)
	dec := NewDecoder()

	var b64s, hexes []string
	for i := 0; i < 500; i++ {
		frame := enc.NextFrame()
		b64s = append(b64s, base64.RawURLEncoding.EncodeToString(frame))
		hexes = append(hexes, hex.EncodeToString(frame))
		out, done, err := dec.Add(frame)
		if err != nil {
			t.Fatalf("encoder produced a frame the decoder rejected at %d: %v", i, err)
		}
		if done {
			if !bytes.Equal(out, payload) {
				t.Fatalf("decode mismatch while building golden fixture")
			}
			return goldenFixture{
				Comment: []string{
					"GOLDEN FIXTURE — real bundle/go/fountain frames, v1.",
					"Generated by `go test ./fountain -run Golden -update-golden`.",
					"frames_b64url is exactly what a QR carries (base64url, NO padding),",
					"i.e. exactly the string the recipient UI must forward VERBATIM to",
					"recipient_qr_feed_frame. frames_hex is the same frame as raw bytes.",
					"Consumed by Go (golden_frames_test.go) and TS (frames.test.ts).",
				},
				PayloadHex:   hex.EncodeToString(payload),
				BlockSize:    goldenBlockSize,
				Seed:         goldenSeed,
				SourceBlocks: enc.SourceBlocks(),
				FramesB64URL: b64s,
				FramesHex:    hexes,
			}
		}
	}
	t.Fatalf("golden payload did not decode within 500 frames")
	return goldenFixture{}
}

func loadGolden(t *testing.T) goldenFixture {
	t.Helper()
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("read golden fixture (regenerate with -update-golden): %v", err)
	}
	var g goldenFixture
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("golden fixture is not valid JSON: %v", err)
	}
	return g
}

func TestGoldenFixtureUpdate(t *testing.T) {
	if !*updateGolden {
		t.Skip("pass -update-golden to rewrite the fixture")
	}
	g := buildGolden(t)
	out, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(goldenPath, append(out, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d frames, k=%d)", goldenPath, len(g.FramesB64URL), g.SourceBlocks)
}

// The compatibility proof: the committed frames, decoded by the real
// decoder, reconstruct the exact payload.
func TestGoldenFramesDecodeToPayload(t *testing.T) {
	g := loadGolden(t)
	want, err := hex.DecodeString(g.PayloadHex)
	if err != nil {
		t.Fatalf("payload_hex: %v", err)
	}
	if len(g.FramesB64URL) == 0 {
		t.Fatal("fixture has no frames")
	}
	if len(g.FramesB64URL) != len(g.FramesHex) {
		t.Fatalf("frames_b64url (%d) and frames_hex (%d) disagree",
			len(g.FramesB64URL), len(g.FramesHex))
	}

	dec := NewDecoder()
	for i, s := range g.FramesB64URL {
		// Decode exactly the way the engine does
		// (core/abi/share.go FountainFeedFrame).
		frame, err := base64.RawURLEncoding.DecodeString(s)
		if err != nil {
			t.Fatalf("frame %d is not base64url-no-pad: %v", i, err)
		}
		if got := hex.EncodeToString(frame); got != g.FramesHex[i] {
			t.Fatalf("frame %d: b64url and hex disagree", i)
		}
		out, done, err := dec.Add(frame)
		if err != nil {
			t.Fatalf("frame %d rejected: %v", i, err)
		}
		if done {
			if !bytes.Equal(out, want) {
				t.Fatalf("decoded payload does not match payload_hex")
			}
			if i != len(g.FramesB64URL)-1 {
				t.Fatalf("decoded at frame %d but fixture carries %d frames; "+
					"the fixture must hold exactly the frames needed",
					i, len(g.FramesB64URL))
			}
			return
		}
	}
	t.Fatalf("committed frames (%d) never completed a decode", len(g.FramesB64URL))
}

// The frames a QR actually carries must survive the alphabet the QR
// lane uses: base64url with NO padding. A standard-base64 encoder
// (JS btoa()) emits '+', '/' and '=' and the engine rejects it — this
// asserts the fixture is genuinely in the wire alphabet.
func TestGoldenFramesUseTheURLAlphabetWithoutPadding(t *testing.T) {
	g := loadGolden(t)
	for i, s := range g.FramesB64URL {
		if bytes.ContainsAny([]byte(s), "+/=") {
			t.Fatalf("frame %d contains a standard-base64 character: %q", i, s)
		}
		if _, err := base64.StdEncoding.DecodeString(s); err == nil && len(s)%4 == 0 {
			continue // coincidentally also valid std base64; harmless
		}
	}
}

func TestGoldenFixtureIsReproducible(t *testing.T) {
	got := buildGolden(t)
	want := loadGolden(t)
	if got.PayloadHex != want.PayloadHex {
		t.Errorf("payload drifted; regenerate with -update-golden")
	}
	if got.SourceBlocks != want.SourceBlocks {
		t.Errorf("source_blocks: got %d want %d", got.SourceBlocks, want.SourceBlocks)
	}
	if len(got.FramesB64URL) != len(want.FramesB64URL) {
		t.Fatalf("frame count drifted: got %d want %d (regenerate with -update-golden)",
			len(got.FramesB64URL), len(want.FramesB64URL))
	}
	for i := range got.FramesB64URL {
		if got.FramesB64URL[i] != want.FramesB64URL[i] {
			t.Fatalf("frame %d drifted; regenerate with -update-golden", i)
		}
	}
}
