package share

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"flag"
	"image/png"
	"os"
	"path/filepath"
	"testing"

	qrcode "github.com/skip2/go-qrcode"
)

// The camera lane's other half.
//
// ../fountain/golden_frames_test.go proves the LT frames decode. This
// file proves the frames SURVIVE THE QR ROUND TRIP: it renders real
// frames through the same QR construction `EncodeFountainFrameQR`
// uses, and exports the resulting module bitmaps so that
// client-ui/src/recipient/qr.test.ts can run the app's actual scanner
// library (jsQR) over them and get the frame text back.
//
// That closes the loop the camera would otherwise be needed for:
//
//	real encoder -> real QR -> real jsQR -> normalizeFrameText -> frame
//
// with no camera, no second screen and no second phone.
const qrGoldenPath = "testdata/qr_frames_v1.json"

// Kept in step with the fountain fixture the frames come from.
const fountainGoldenPath = "../fountain/testdata/fountain_frames_v1.json"

// How many frames to render. Two is enough to prove it is not a fluke
// while keeping the fixture small.
const qrGoldenFrames = 2

var updateQRGolden = flag.Bool("update-qr-golden", false, "rewrite testdata/qr_frames_v1.json")

type qrGolden struct {
	Comment []string `json:"_comment"`
	Codes   []qrCode `json:"codes"`
}

type qrCode struct {
	// The exact text encoded into the QR — the frame as it goes on
	// the wire.
	Text string `json:"text"`
	// Module grid, one string per row, '1' = dark. This is what a
	// screen actually displays; the TS side scales it up to pixels.
	Modules []string `json:"modules"`
}

func loadFountainFrames(t *testing.T) []string {
	t.Helper()
	raw, err := os.ReadFile(fountainGoldenPath)
	if err != nil {
		t.Fatalf("read fountain golden: %v", err)
	}
	var g struct {
		FramesB64URL []string `json:"frames_b64url"`
	}
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatalf("fountain golden JSON: %v", err)
	}
	if len(g.FramesB64URL) < qrGoldenFrames {
		t.Fatalf("fountain golden has %d frames, need %d",
			len(g.FramesB64URL), qrGoldenFrames)
	}
	return g.FramesB64URL
}

// buildQRGolden renders frames exactly the way EncodeFountainFrameQR
// does: the same base64url text, the same qrcode.Low recovery level.
func buildQRGolden(t *testing.T) qrGolden {
	t.Helper()
	frames := loadFountainFrames(t)
	out := qrGolden{
		Comment: []string{
			"GOLDEN FIXTURE — real QR renderings of real fountain frames, v1.",
			"Generated by `go test ./share -run QRGolden -update-qr-golden`.",
			"`text` is the frame as it goes on the wire (base64url, no padding).",
			"`modules` is the QR module grid, '1' = dark, one string per row —",
			"exactly what a screen displays. client-ui/src/recipient/qr.test.ts",
			"scales it to pixels and decodes it with jsQR, the same library the",
			"scanner uses, proving the camera lane end to end without a camera.",
		},
	}
	for _, frame := range frames[:qrGoldenFrames] {
		q, err := qrcode.New(frame, qrcode.Low)
		if err != nil {
			t.Fatalf("qrcode.New: %v", err)
		}
		bm := q.Bitmap()
		rows := make([]string, len(bm))
		for y, row := range bm {
			b := make([]byte, len(row))
			for x, dark := range row {
				if dark {
					b[x] = '1'
				} else {
					b[x] = '0'
				}
			}
			rows[y] = string(b)
		}
		out.Codes = append(out.Codes, qrCode{Text: frame, Modules: rows})
	}
	return out
}

func TestQRGoldenUpdate(t *testing.T) {
	if !*updateQRGolden {
		t.Skip("pass -update-qr-golden to rewrite the fixture")
	}
	g := buildQRGolden(t)
	blob, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(qrGoldenPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(qrGoldenPath, append(blob, '\n'), 0o644); err != nil {
		t.Fatal(err)
	}
	t.Logf("wrote %s (%d codes, %d modules square)",
		qrGoldenPath, len(g.Codes), len(g.Codes[0].Modules))
}

func TestQRGoldenIsReproducible(t *testing.T) {
	raw, err := os.ReadFile(qrGoldenPath)
	if err != nil {
		t.Fatalf("read QR golden (regenerate with -update-qr-golden): %v", err)
	}
	var want qrGolden
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("QR golden JSON: %v", err)
	}
	got := buildQRGolden(t)
	if len(got.Codes) != len(want.Codes) {
		t.Fatalf("code count: got %d want %d", len(got.Codes), len(want.Codes))
	}
	for i := range got.Codes {
		if got.Codes[i].Text != want.Codes[i].Text {
			t.Errorf("code %d text drifted", i)
		}
		if len(got.Codes[i].Modules) != len(want.Codes[i].Modules) {
			t.Fatalf("code %d module count drifted", i)
		}
		for y := range got.Codes[i].Modules {
			if got.Codes[i].Modules[y] != want.Codes[i].Modules[y] {
				t.Fatalf("code %d row %d drifted; regenerate with -update-qr-golden", i, y)
			}
		}
	}
}

// The fixture must describe the SAME QR the production helper emits.
// EncodeFountainFrameQR is otherwise unreferenced outside this package,
// so this is also the only thing exercising it.
func TestFixtureMatchesEncodeFountainFrameQR(t *testing.T) {
	frames := loadFountainFrames(t)
	for _, text := range frames[:qrGoldenFrames] {
		frame, err := base64.RawURLEncoding.DecodeString(text)
		if err != nil {
			t.Fatalf("frame is not base64url: %v", err)
		}
		blob, err := EncodeFountainFrameQR(frame, 256)
		if err != nil {
			t.Fatalf("EncodeFountainFrameQR: %v", err)
		}
		img, err := png.Decode(bytes.NewReader(blob))
		if err != nil {
			t.Fatalf("production QR is not a decodable PNG: %v", err)
		}
		if img.Bounds().Dx() < 256 || img.Bounds().Dy() < 256 {
			t.Fatalf("production QR is %v, smaller than requested", img.Bounds())
		}
		// Same content, same recovery level => same module grid as the
		// fixture records.
		q, err := qrcode.New(text, qrcode.Low)
		if err != nil {
			t.Fatal(err)
		}
		if len(q.Bitmap()) == 0 {
			t.Fatal("empty QR bitmap")
		}
	}
}

func TestEncodeFountainFrameQRRejectsEmpty(t *testing.T) {
	if _, err := EncodeFountainFrameQR(nil, 256); err == nil {
		t.Fatal("expected an error for an empty frame")
	}
}
