package main

// address.go — the box half of L3 (the floating-IP swap).
//
// WHY THIS FILE EXISTS. A cloud floating IP is routed to the server at
// the PROVIDER's network layer. The provider API reports the attach as
// done in under a second, and it is done — the packets arrive. What
// does not happen is the guest OS answering them: Linux drops a packet
// whose destination is not an address configured on one of its
// interfaces. Measured on real hardware on 2026-08-17, an L3 swap did
// everything right at the API layer (reserved, attached, labelled,
// rewrote rec.PublicIP) and the box never answered on the new address
// while the old one kept serving. Nothing in this tree configured the
// address on the interface: cloud-init never writes it and the assign
// path is pure API.
//
// health.AddressServes already made that failure SAFE (the swap refuses
// and hands the address back). This file is what makes it WORK.
//
// NO SING-BOX CONFIG CHANGE IS NEEDED, and that is a load-bearing fact
// rather than a convenience. Every inbound this tree renders listens on
// 0.0.0.0 (profile_render.go:125,130; singbox_users.go:474,565,673,678),
// so sing-box accepts on any address the kernel holds for the host. The
// entire gap is "the OS does not hold the address". Adding it to the
// interface closes the gap completely — no inbound is touched, no
// config is rewritten, and therefore s.cfgMu is deliberately NOT taken
// on these paths (see addrMu).
//
// ---------------------------------------------------------------
// THREAT MODEL — this is root-level network configuration driven by a
// remote request, so it gets more than the signature it already sits
// behind.
//
// Who can call it: only the publisher. Both routes are wrapped in
// s.requireAuth, i.e. a per-request Ed25519 signature over
// nonce:ts:op verified against the per-deploy public key, inside a 5
// minute window, and the mgmt port is additionally shut by the cloud
// provider firewall except during an ephemeral allowlist window. That
// is the primary control and it is strong.
//
// Why we defend further anyway: the publisher's signing key lives on an
// operator's laptop, the operator is the person under pressure in this
// product's threat model, and a bug in the publisher is as dangerous
// here as a stolen key. The failure modes of an unbounded "configure
// any address on the host" primitive are severe and silent:
//
//   T1  Traffic hijack / route shadowing. Binding 127.0.0.1, a
//       link-local address, or an RFC1918 address that the box already
//       routes towards a gateway makes the host itself the destination
//       for that address. Local traffic aimed at an internal service
//       (metadata service on 169.254.169.254 is the sharpest example)
//       would be answered by this host instead of the real one.
//       MITIGATION: validateBindAddress rejects every non-public
//       unicast class by name — see the table there.
//
//   T2  Command injection. The live half shells out. A caller-supplied
//       string reaching a shell would be remote root code execution
//       behind one signature check.
//       MITIGATION, three layers: (a) a strict charset pre-filter
//       rejects anything outside hex digits, ':' and '.' before parsing
//       — no spaces, no ';', '$', '`', '|', newline, '%' zone-id or '/'
//       prefix can even reach the parser; (b) the address is parsed
//       with net.ParseIP and then RE-RENDERED from the parsed value, so
//       the bytes that leave this process are generated by Go's
//       formatter and never by the caller; (c) exec.Command is invoked
//       with an argv, never through a shell, so even a hostile argument
//       is one argv element and not a command. Any one of the three is
//       sufficient; all three are present because this is the endpoint
//       where being wrong is worst.
//
//   T3  Interface exhaustion. A buggy retry loop or a compromised
//       caller could add addresses until the interface, the netlink
//       tables or the persistence directory is unusable.
//       MITIGATION: maxBoundAddresses caps the set; the cap is checked
//       against the persisted record set, not against a counter, so a
//       restart cannot reset it.
//
//   T4  Self-eviction via unbind. `ip addr del <primary> dev eth0` on a
//       box with no SSH access is a permanent, unrecoverable outage —
//       strictly worse than anything bind can do. An unbind that
//       accepted any address would hand that button to whoever holds
//       the signing key, and to any publisher bug that passes the wrong
//       variable.
//       MITIGATION, TWO HALVES, and the second one was missing until
//       the Wave 3c repair. (a) unbind is RECORD-GATED: it will only
//       remove an address this service itself bound and still has a
//       persistence record for. An address that is not in the record
//       set is a no-op success (idempotence) and the interface is not
//       touched. (b) bind REFUSES TO ADOPT an address that is already
//       configured on the interface and is not already one of our
//       records — because adopting one is exactly how the primary
//       address would get INTO the record set, after which (a) permits
//       its removal. Two signed calls, bind(primary) then
//       unbind(primary), used to be enough to strand the relay for
//       good; see handleBindAddress. With both halves in place the
//       invariant "the primary address is never a record, so it can
//       never be removed through this API" is enforced rather than
//       merely hoped for.
//
//   T5  Stale persistence. An address released back to the provider
//       pool is re-issued to another customer. A persistence record we
//       forgot to remove would make this box claim a stranger's address
//       at the next reboot.
//       MITIGATION: bind undoes its own persistence when the live half
//       fails (see bind failure semantics below), and unbind removes
//       the live address FIRST and the record second, attempting both
//       even if the first fails, so the "still holding it" direction is
//       never the one we stop in.
//
// RESIDUAL, ACCEPTED: an authenticated caller can bind a public address
// that belongs to a neighbour on the same L2 segment and blackhole or
// ARP-hijack it. The box cannot detect this — only the provider knows
// which addresses are actually routed here, and the box has no way to
// ask. We reduce the blast radius by adding every address as a HOST
// prefix (/32, /128) so a bind can never claim a whole subnet or
// disturb the existing on-link route, and we do not reject
// same-subnet addresses because several providers legitimately hand out
// additional addresses from the server's own subnet and rejecting them
// would break the feature for those providers.

import (
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"
)

// capBindAddress is the capability token the box advertises on
// GET /health when it can ACTUALLY configure addresses on this host.
//
// It is a wire contract with publisher/deploy/mgmt, exactly like
// capRotateCredentialsScoped: the publisher fails closed on its
// absence, so the literal is the contract and not the constant name.
//
// TWO THINGS ABOUT THIS TOKEN ARE DELIBERATE.
//
// First, it is advertised CONDITIONALLY, unlike the two rotation
// tokens. Those describe what the binary does; this one describes
// something the binary cannot do alone. Configuring an address needs
// CAP_NET_ADMIN, and cloud-init decides whether this service has it.
// Older relays (and any box whose unit was hand-edited) run
// daal-relay-mgmt with `CapabilityBoundingSet=CAP_NET_BIND_SERVICE` and
// `NoNewPrivileges=true` — root, but without the capability, and unable
// to acquire it. So a box can be running this exact binary and still be
// unable to bind. Advertising the verb from the binary version alone
// would be the publisher's interlock reporting a capability that does
// not exist, and the failure would land halfway through a swap. The
// probe (probeAddressBinding) asks whether this process can ACTUALLY
// configure addresses, and only then does the token appear.
//
// ONE TOKEN COVERS BOTH VERBS, so the probe must be true of both. It
// was not: a box that could only delegate to the boot unit advertised
// the token, and the boot unit only ADDS. Every unbind on such a box
// was a guaranteed 500 — which turns a failed swap's rollback and the
// whole `floating-ip release` path into dead ends, and hands addresses
// back to the provider pool while the box still holds them. The probe
// now requires the capability this process can use for BOTH directions;
// see probeAddressBinding.
//
// Second, and following from the first: the publisher must treat this
// token as the ONLY signal for address binding. It must NOT add a
// mgmt_api_version fallback for it the way BoxCapabilities.Has does for
// the two rotation verbs, because the version says what the binary is
// and this capability is a property of how the binary was launched.
// As shipped it does exactly that — BoxCapabilities.Has has no version
// branch for CapBindAddress — and this comment is the reason it must
// stay that way.
const capBindAddress = "bind-address"

// maxBoundAddresses bounds T3.
//
// THIS NUMBER IS SHARED WITH THE PUBLISHER (mgmt.MaxBoundAddresses = 4)
// and the two must stay equal. The box is the enforcement point,
// because it is the only party that can see the interface; the
// publisher re-checks the count this box reports in bound_addresses and
// refuses a box that reports more, so a mismatch shows up as a loud
// refusal of a legitimate bind rather than as a slowly filling
// interface. Four covers a v4/v6 pair on each side of a swap and leaves
// no room for a runaway.
//
// Enforced against the PERSISTED set, not an in-memory counter, so a
// restart cannot reset it.
const maxBoundAddresses = 4

// bootUnitName is the oneshot systemd unit that re-applies the
// persisted record set after a reboot. See ensureBootUnit for why
// persistence is a unit and not a netplan file.
const bootUnitName = "daal-bound-addresses.service"

// addrCharset is the T2 pre-filter. Hex digits, ':' and '.' are
// everything any textual IP literal needs; nothing else is accepted, so
// shell metacharacters, whitespace, newlines, '%' zone identifiers and
// '/' prefix lengths are rejected before net.ParseIP is even reached.
// Length is bounded so an enormous body cannot be walked.
var addrCharset = regexp.MustCompile(`^[0-9a-fA-F:.]{2,45}$`)

// ifaceNameRe validates the interface name before it becomes an argv
// element. The name is derived from the kernel, never from the caller,
// so this is belt-and-braces against a future refactor that lets one in.
var ifaceNameRe = regexp.MustCompile(`^[A-Za-z0-9._-]{1,15}$`)

// --- validation -------------------------------------------------------

// rejectedRange is one row of the T1 validation table. `why` names the
// range in the words an operator can look up, because "invalid address"
// on a remote box with no SSH is not an actionable error.
type rejectedRange struct {
	cidr string
	why  string
	net  *net.IPNet
}

// rejectedRanges is the T1 table: every address class that must never be
// configured on this host in response to a remote request.
//
// The list is explicit rather than delegated to ip.IsGlobalUnicast()
// because that helper returns TRUE for RFC1918 and CGNAT space — it
// answers "is this a unicast address with global scope semantics", not
// "is this an address the public internet could route here". Both are
// applied: the table first (so the error names the range) and
// IsGlobalUnicast afterwards as a catch-all for anything the table
// misses.
//
// THE DOCUMENTATION RANGES ARE DELIBERATELY ABSENT (192.0.2.0/24,
// 198.51.100.0/24, 203.0.113.0/24, 2001:db8::/32), and the omission is
// a reconciliation with publisher/deploy/mgmt.BindableAddress, which
// allows them. The two validators MUST agree, and this is the direction
// they were made to agree in, for two reasons:
//
//   - Nothing this table exists to prevent is reachable through them.
//     They shadow no internal route, carry no metadata service, hijack
//     no traffic on the host, and no provider will ever issue one — so
//     the worst a bound documentation address can do is be an address
//     the relay answers on and nobody can reach.
//   - The stricter end has to be the FIRST end or its strictness buys
//     nothing. The publisher validates before it reserves or attaches
//     anything; this box validates last. A row present here and absent
//     there does not prevent a bad bind, it only moves the refusal to
//     after an address has been reserved, attached and a firewall
//     window opened — which is the failure shape this whole wave exists
//     to remove.
//
// They also have one property no real address has: a test may DIAL them
// and be certain nobody answers. Refusing them would push every
// reachability test in this tree onto some third party's real address.
//
// 192.88.99.0/24 stays rejected, and is the row that shows the rule is
// harm-based rather than "not routable": 6to4 relay anycast has real
// routing meaning, so binding it can attract or shadow traffic. The
// publisher was tightened to match it rather than the reverse.
var rejectedRanges = func() []rejectedRange {
	rows := []rejectedRange{
		// IPv4.
		{cidr: "0.0.0.0/8", why: "unspecified / \"this network\" 0.0.0.0/8"},
		{cidr: "10.0.0.0/8", why: "RFC1918 private 10.0.0.0/8"},
		{cidr: "100.64.0.0/10", why: "RFC6598 carrier-grade NAT 100.64.0.0/10"},
		{cidr: "127.0.0.0/8", why: "loopback 127.0.0.0/8"},
		{cidr: "169.254.0.0/16", why: "link-local 169.254.0.0/16 (includes the cloud metadata service at 169.254.169.254)"},
		{cidr: "172.16.0.0/12", why: "RFC1918 private 172.16.0.0/12"},
		{cidr: "192.0.0.0/24", why: "IETF protocol assignments 192.0.0.0/24"},
		{cidr: "192.88.99.0/24", why: "deprecated 6to4 relay anycast 192.88.99.0/24"},
		{cidr: "192.168.0.0/16", why: "RFC1918 private 192.168.0.0/16"},
		{cidr: "198.18.0.0/15", why: "benchmarking 198.18.0.0/15"},
		{cidr: "224.0.0.0/4", why: "multicast 224.0.0.0/4"},
		{cidr: "240.0.0.0/4", why: "reserved 240.0.0.0/4 (includes the 255.255.255.255 broadcast address)"},
		// IPv6.
		{cidr: "::/128", why: "unspecified ::"},
		{cidr: "::1/128", why: "loopback ::1"},
		// ::ffff:0:0/96 (IPv4-mapped) is deliberately NOT a row here,
		// and the omission is load-bearing rather than an oversight.
		// net.ParseCIDR renders that prefix as a value whose To4() is
		// non-nil, so IPNet.Contains reduces its /96 mask to the LAST
		// FOUR BYTES — which are all zero — and the row silently
		// becomes 0.0.0.0/0, rejecting every IPv4 address on earth.
		// The disguise is caught by the textual check in
		// validateBindAddress instead, which is the only place it is
		// actually visible: after parsing, ::ffff:127.0.0.1 and
		// 127.0.0.1 are the same 16 bytes.
		{cidr: "64:ff9b::/96", why: "NAT64 well-known prefix 64:ff9b::/96"},
		{cidr: "100::/64", why: "discard-only 100::/64"},
		{cidr: "2001::/32", why: "Teredo 2001::/32"},
		{cidr: "2002::/16", why: "deprecated 6to4 2002::/16"},
		{cidr: "fc00::/7", why: "unique-local fc00::/7"},
		{cidr: "fe80::/10", why: "link-local fe80::/10"},
		{cidr: "ff00::/8", why: "multicast ff00::/8"},
	}
	for i := range rows {
		_, n, err := net.ParseCIDR(rows[i].cidr)
		if err != nil {
			// Unreachable: the table is a compile-time constant in
			// everything but name. Panicking here beats shipping a
			// validator with a silently missing row.
			panic("address.go: bad rejectedRanges entry " + rows[i].cidr + ": " + err.Error())
		}
		rows[i].net = n
	}
	return rows
}()

// validateBindAddress is the whole of T1 and layers (a) and (b) of T2.
//
// It returns the CANONICAL address, re-rendered by Go's formatter from
// the parsed value. Callers must use the returned net.IP and must never
// carry the caller's string forward — that is the property that makes
// every downstream use (argv element, filename, JSON echo) injection
// proof by construction rather than by review.
func validateBindAddress(raw string) (net.IP, error) {
	s := strings.TrimSpace(raw)
	if s == "" {
		return nil, errors.New(`"ip" is required`)
	}
	if !addrCharset.MatchString(s) {
		// Deliberately does NOT echo the input. This error can reach a
		// log or an operator's terminal, and reflecting arbitrary bytes
		// from a rejected request is how a validator becomes an
		// injection vector for the thing reading its output.
		return nil, errors.New("malformed address: only hexadecimal digits, ':' and '.' are accepted " +
			"(no prefix length, no zone id, no whitespace)")
	}
	ip := net.ParseIP(s)
	if ip == nil {
		return nil, fmt.Errorf("not a valid IP address: %q", s)
	}
	// An IPv4-mapped literal (::ffff:127.0.0.1) parses to a 16-byte
	// value whose To4() is non-nil, so it would otherwise sail through
	// the IPv4 half of the table wearing IPv6 clothes and then be
	// rendered back as plain 127.0.0.1. Caught here by the TEXTUAL
	// form, which is the ONLY place the disguise is visible: after
	// parsing, ::ffff:127.0.0.1 and 127.0.0.1 are the same bytes. See
	// the note in rejectedRanges for why this cannot be a table row.
	if strings.Contains(s, ":") && ip.To4() != nil {
		return nil, errors.New("rejected: IPv4-mapped IPv6 ::ffff:0:0/96 — send the plain IPv4 form instead")
	}
	for _, r := range rejectedRanges {
		// Compare in the family the row was written in: a 4-byte v4
		// value and a 16-byte v6 range must not match each other.
		probe := ip
		if r.net.IP.To4() != nil {
			if probe = ip.To4(); probe == nil {
				continue
			}
		} else if ip.To4() != nil {
			continue
		}
		if r.net.Contains(probe) {
			return nil, fmt.Errorf("rejected %s: not a public unicast address (%s)", canonicalIP(ip), r.why)
		}
	}
	// Catch-all for anything the table does not enumerate.
	if !ip.IsGlobalUnicast() {
		return nil, fmt.Errorf("rejected %s: not a global unicast address", canonicalIP(ip))
	}
	if ip.To4() != nil {
		return ip.To4(), nil
	}
	return ip, nil
}

// canonicalIP renders a parsed address. Every string this file emits —
// argv elements, persistence filenames, JSON responses, error text —
// comes from here and therefore from Go's formatter.
func canonicalIP(ip net.IP) string { return ip.String() }

// prefixLen returns the HOST prefix for the family. Always /32 or /128,
// never the interface's subnet prefix: a host route claims exactly one
// address and cannot rewrite the on-link route the box needs to reach
// its gateway. See the residual-risk note in the threat model.
func prefixLen(ip net.IP) int {
	if ip.To4() != nil {
		return 32
	}
	return 128
}

// --- persistence ------------------------------------------------------

// PERSISTENCE: WHY A SYSTEMD ONESHOT AND NOT NETPLAN.
//
// The box is a cloud-init Ubuntu 24.04 image (providers/hetzner:
// "ubuntu-24.04"). Its network is described by netplan
// (/etc/netplan/50-cloud-init.yaml) rendered to systemd-networkd, so
// netplan is the image's native mechanism and the provider's own
// documentation for floating IPs says to add a netplan file. It was
// still rejected, for three reasons in increasing order of weight:
//
//  1. Netplan merges files by key, and a list-valued key in a
//     higher-numbered file REPLACES the same key from a lower-numbered
//     one rather than appending to it. Writing `addresses:` for eth0
//     works today only because the cloud-init file configures the
//     primary address by DHCP and so has no `addresses:` list to
//     replace. That is a property of one provider's image, not of the
//     format, and it is invisible until the day it changes.
//
//  2. Applying it is not free. `netplan apply` reconfigures the live
//     interface, and the one moment we run it is mid-rotation, while
//     the box MUST keep answering on the old address — the entire
//     safety property of the fail-closed swap. `ip addr add` is
//     strictly additive and cannot remove anything.
//
//  3. Blast radius, which is decisive. A malformed file in
//     /etc/netplan fails the whole configuration at boot, and this box
//     has no SSH access by design. The failure mode of a bad netplan
//     write is a relay that never comes back and can only be
//     destroyed and reprovisioned. The failure mode of a bad unit file
//     is one oneshot service that fails while the network comes up
//     normally — recoverable, visible, and no worse than not having
//     bound the address at all, which is the state health.AddressServes
//     already fails closed on.
//
// So: the record set is a directory of one file per address, and a
// systemd oneshot re-applies it after network-online.target. The unit
// runs THIS binary with -reapply-addresses, so the boot path and the
// live path are the same validated code — a record that would be
// rejected today is rejected at boot too, and there is no shell script
// to drift.
//
// The rejected alternative worth naming: a drop-in in
// /etc/systemd/network. A .network file there matching eth0 would
// SHADOW netplan's generated unit in /run/systemd/network instead of
// adding to it, taking DHCP with it. Same unrecoverable outcome as (3).
//
// KNOWN LIMIT, stated rather than papered over: an address added with
// `ip addr add` is "foreign" to systemd-networkd. A full
// `networkctl reconfigure` or a `netplan apply` run by something else
// on the box can flush it before the next reboot. Nothing on this box
// does either today, and the address is restored at the next boot;
// re-asserting it live is one `systemctl restart daal-bound-addresses`
// away, and the reapply path is idempotent precisely so that is safe.

// boundRecordFile maps an address to its persistence filename.
//
// Built from the CANONICAL rendering, not the caller's string, so no
// caller-supplied byte reaches a path. ':' becomes '_' purely to keep
// the names easy to read and type; the file's CONTENT is the
// authoritative value and readers re-parse and re-validate it, so the
// name is never trusted. The two families cannot collide: an IPv4 name
// contains '.' and never '_', an IPv6 name the reverse.
func boundRecordFile(dir string, ip net.IP) string {
	name := strings.ReplaceAll(canonicalIP(ip), ":", "_")
	return filepath.Join(dir, name+".addr")
}

// listBoundRecords returns the persisted address set, canonical and
// sorted.
//
// Every record is re-parsed and re-validated on the way out. A record
// that no longer passes validateBindAddress — a hand-edited file, a
// record written by a future version with looser rules, a corrupted
// write — is SKIPPED and named in the returned warnings rather than
// applied. The boot path uses this function too, so a record that could
// not be created through the API can never be applied by the reboot
// either.
func listBoundRecords(dir string) ([]net.IP, []string, error) {
	entries, err := os.ReadDir(dir)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil, nil
	}
	if err != nil {
		return nil, nil, err
	}
	var out []net.IP
	var warns []string
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".addr") {
			continue
		}
		body, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			warns = append(warns, fmt.Sprintf("record %s unreadable: %v", e.Name(), err))
			continue
		}
		ip, err := validateBindAddress(strings.TrimSpace(string(body)))
		if err != nil {
			warns = append(warns, fmt.Sprintf("record %s ignored: %v", e.Name(), err))
			continue
		}
		out = append(out, ip)
	}
	sort.Slice(out, func(i, j int) bool { return canonicalIP(out[i]) < canonicalIP(out[j]) })
	return out, warns, nil
}

// writeBoundRecord persists one address, temp-file-then-rename so a
// crash mid-write cannot leave a half-written record that the boot path
// would then have to interpret.
//
// 0o600 / 0o700: the record set is operational configuration for a
// privileged action. Nothing unprivileged on the box needs to read it,
// and a world-writable record directory would turn a local unprivileged
// bug into "choose which address this host claims at next boot".
func writeBoundRecord(dir string, ip net.IP) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return err
	}
	path := boundRecordFile(dir, ip)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(canonicalIP(ip)+"\n"), 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}

// removeBoundRecord deletes the record for ip. Absent is success:
// rotations are retried, and "already gone" is the outcome the caller
// asked for.
//
// It removes by CONTENT, walking the directory and comparing parsed
// values, not by recomputing the filename. Two spellings of the same
// address must not be able to leave a second file behind, and a record
// written by an older or newer naming scheme still has to be removable.
func removeBoundRecord(dir string, ip net.IP) (removed bool, err error) {
	entries, rerr := os.ReadDir(dir)
	if errors.Is(rerr, os.ErrNotExist) {
		return false, nil
	}
	if rerr != nil {
		return false, rerr
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".addr") {
			continue
		}
		p := filepath.Join(dir, e.Name())
		body, readErr := os.ReadFile(p)
		if readErr != nil {
			continue
		}
		got := net.ParseIP(strings.TrimSpace(string(body)))
		if got == nil || !got.Equal(ip) {
			continue
		}
		if delErr := os.Remove(p); delErr != nil && !errors.Is(delErr, os.ErrNotExist) {
			err = delErr
			continue
		}
		removed = true
	}
	return removed, err
}

// --- the boot unit ----------------------------------------------------

// bootUnitBody renders the oneshot unit.
//
// ExecStart names THIS executable (os.Executable, resolved at write
// time) with a fixed flag and no caller-derived content anywhere in the
// file, so the unit cannot become an injection surface even though it
// is written in response to a remote request.
//
// AmbientCapabilities=CAP_NET_ADMIN is the point of the unit beyond
// persistence: PID 1 grants it, so the boot-time apply holds the
// capability the long-running mgmt service is denied. See
// probeAddressBinding.
func bootUnitBody(exePath string) string {
	return "[Unit]\n" +
		"Description=Daal: re-apply operator-bound addresses (floating IPs) to the primary interface\n" +
		"After=network-online.target\n" +
		"Wants=network-online.target\n" +
		"\n" +
		"[Service]\n" +
		"Type=oneshot\n" +
		"RemainAfterExit=yes\n" +
		"ExecStart=" + exePath + " -reapply-addresses\n" +
		"AmbientCapabilities=CAP_NET_ADMIN\n" +
		"CapabilityBoundingSet=CAP_NET_ADMIN\n" +
		"\n" +
		"[Install]\n" +
		"WantedBy=multi-user.target\n"
}

// ensureBootUnit installs (or refreshes) the unit and its enablement
// symlink, idempotently.
//
// The symlink is created directly rather than through
// `systemctl enable`, because that is exactly what enable does for a
// WantedBy=multi-user.target unit and doing it ourselves removes a
// dependency on systemctl succeeding for the half of the operation that
// must not be best-effort. `systemctl daemon-reload` is then called
// best-effort: without it the unit is still picked up at the next boot,
// which is the only moment it runs.
//
// This is called BEFORE the record is persisted, and its failure is
// fatal to the bind. A record with no unit to re-apply it is precisely
// the "silently dies at the next reboot" outcome the persistence
// requirement exists to prevent, so a box that cannot host the unit
// must refuse to bind rather than bind and lie.
func (s *server) ensureBootUnit() error {
	if s.bootUnitPath == "" {
		return errors.New("boot unit path not configured")
	}
	exe, err := os.Executable()
	if err != nil || strings.TrimSpace(exe) == "" {
		// Fall back to the path cloud-init installs to. Better a unit
		// naming the canonical location than no persistence at all.
		exe = "/usr/local/bin/daal-relay-mgmt"
	}
	body := bootUnitBody(exe)
	if cur, rerr := os.ReadFile(s.bootUnitPath); rerr == nil && string(cur) == body {
		// Already correct; still make sure the enablement link is there.
		return s.ensureBootUnitEnabled()
	}
	if err := os.MkdirAll(filepath.Dir(s.bootUnitPath), 0o755); err != nil {
		return fmt.Errorf("boot unit dir: %w", err)
	}
	tmp := s.bootUnitPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(body), 0o644); err != nil {
		return fmt.Errorf("boot unit write: %w", err)
	}
	if err := os.Rename(tmp, s.bootUnitPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("boot unit install: %w", err)
	}
	if err := s.ensureBootUnitEnabled(); err != nil {
		return err
	}
	// The reload is NOT best-effort, and the reason is easy to get
	// wrong. systemd does not learn about a unit file that appeared
	// after its last reload, so without this:
	//
	//   - `systemctl restart daal-bound-addresses` fails with "unit not
	//     found" — and on the box as shipped that IS the apply path,
	//     because this service holds no CAP_NET_ADMIN; and
	//   - the enablement symlink we just wrote is not acted on, so the
	//     unit may not run at the next boot either, which is the
	//     persistence guarantee itself.
	//
	// A box where daemon-reload fails is a box where neither half can
	// be promised, so it refuses the bind rather than reporting
	// persisted=true over a unit systemd has never seen. Only called on
	// the path where the file actually changed, so a steady-state
	// re-bind does not pay for it.
	if s.systemdReload != nil {
		if err := s.systemdReload(); err != nil {
			return fmt.Errorf("systemd did not accept the persistence unit (it would neither run at boot nor be startable now): %w", err)
		}
	}
	return nil
}

func (s *server) ensureBootUnitEnabled() error {
	if s.bootUnitWantsPath == "" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(s.bootUnitWantsPath), 0o755); err != nil {
		return fmt.Errorf("boot unit enable dir: %w", err)
	}
	if cur, err := os.Readlink(s.bootUnitWantsPath); err == nil && cur == s.bootUnitPath {
		return nil
	}
	_ = os.Remove(s.bootUnitWantsPath)
	if err := os.Symlink(s.bootUnitPath, s.bootUnitWantsPath); err != nil && !errors.Is(err, os.ErrExist) {
		return fmt.Errorf("boot unit enable: %w", err)
	}
	return nil
}

// --- the live half ----------------------------------------------------

// detectPrimaryInterface picks the NIC the box's public traffic arrives
// on.
//
// Preference order: an up, non-loopback, non-point-to-point interface
// that already holds a PUBLIC address (that is the WAN NIC by
// definition); failing that, one holding any global unicast address (a
// box behind provider NAT). Virtual and container interfaces are
// excluded by name because a bridge with a private address would
// otherwise win the fallback and the address would be configured
// somewhere the internet cannot reach.
//
// Ties break on the lowest interface index, which is eth0 on every
// image this tree provisions (cloud-init's own probe hardcodes eth0 —
// v2.yaml.tmpl:284 — so agreeing with it is the conservative choice).
func detectPrimaryInterface() (string, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", fmt.Errorf("enumerate interfaces: %w", err)
	}
	sort.Slice(ifaces, func(i, j int) bool { return ifaces[i].Index < ifaces[j].Index })
	fallback := ""
	for _, ifc := range ifaces {
		if ifc.Flags&net.FlagUp == 0 || ifc.Flags&net.FlagLoopback != 0 {
			continue
		}
		if ifc.Flags&net.FlagPointToPoint != 0 {
			continue // tun/wg/ppp: not where a provider routes a floating IP
		}
		if isVirtualIfaceName(ifc.Name) || !ifaceNameRe.MatchString(ifc.Name) {
			continue
		}
		addrs, err := ifc.Addrs()
		if err != nil {
			continue
		}
		for _, a := range addrs {
			n, ok := a.(*net.IPNet)
			if !ok || n.IP == nil || !n.IP.IsGlobalUnicast() {
				continue
			}
			if _, verr := validateBindAddress(n.IP.String()); verr == nil {
				return ifc.Name, nil // holds a public address: this is the WAN NIC
			}
			if fallback == "" {
				fallback = ifc.Name
			}
		}
	}
	if fallback != "" {
		return fallback, nil
	}
	return "", errors.New("no candidate interface: no up, non-loopback interface holds a global unicast address")
}

// isVirtualIfaceName excludes the usual container/virtual plumbing so it
// cannot win the private-address fallback in detectPrimaryInterface.
func isVirtualIfaceName(name string) bool {
	for _, p := range []string{"docker", "veth", "br-", "virbr", "tun", "tap", "wg", "cni", "flannel", "kube", "lo"} {
		if strings.HasPrefix(name, p) {
			return true
		}
	}
	return false
}

// defaultAddrList reads the addresses currently configured on an
// interface. Pure Go, read-only, needs no capability — which is what
// lets this process VERIFY the outcome of an apply it may have had to
// delegate. "Did it work" is answered by looking, never by trusting the
// exit status of the thing we asked to do it.
func defaultAddrList(iface string) ([]net.IP, error) {
	ifc, err := net.InterfaceByName(iface)
	if err != nil {
		return nil, err
	}
	addrs, err := ifc.Addrs()
	if err != nil {
		return nil, err
	}
	out := make([]net.IP, 0, len(addrs))
	for _, a := range addrs {
		switch v := a.(type) {
		case *net.IPNet:
			out = append(out, v.IP)
		case *net.IPAddr:
			out = append(out, v.IP)
		}
	}
	return out, nil
}

// defaultAddrAdd runs `ip addr add <ip>/<hostprefix> dev <iface>`.
//
// exec.Command takes an argv and does NOT go through a shell (T2 layer
// c). Both variable elements are generated here: the address from
// canonicalIP over a parsed net.IP, the interface from the kernel via
// ifaceNameRe. No caller byte is present in this command line.
//
// "File exists" is success. Idempotence has to hold at this layer too,
// not only at the layer above, because the presence check and the add
// are not atomic and a retried rotation is the normal case.
func defaultAddrAdd(iface string, ip net.IP) error {
	if !ifaceNameRe.MatchString(iface) {
		return fmt.Errorf("refusing to use interface name %q", iface)
	}
	cidr := canonicalIP(ip) + "/" + strconv.Itoa(prefixLen(ip))
	out, err := exec.Command("ip", "addr", "add", cidr, "dev", iface).CombinedOutput()
	if err == nil {
		return nil
	}
	if strings.Contains(strings.ToLower(string(out)), "file exists") {
		return nil
	}
	return fmt.Errorf("ip addr add %s dev %s: %w (%s)", cidr, iface, err, strings.TrimSpace(string(out)))
}

// defaultAddrDel runs `ip addr del`. Same argv discipline. "Cannot
// assign requested address" / "not exist" is success for the same
// idempotence reason.
func defaultAddrDel(iface string, ip net.IP) error {
	if !ifaceNameRe.MatchString(iface) {
		return fmt.Errorf("refusing to use interface name %q", iface)
	}
	cidr := canonicalIP(ip) + "/" + strconv.Itoa(prefixLen(ip))
	out, err := exec.Command("ip", "addr", "del", cidr, "dev", iface).CombinedOutput()
	if err == nil {
		return nil
	}
	low := strings.ToLower(string(out))
	if strings.Contains(low, "cannot assign requested address") || strings.Contains(low, "not exist") {
		return nil
	}
	return fmt.Errorf("ip addr del %s dev %s: %w (%s)", cidr, iface, err, strings.TrimSpace(string(out)))
}

// defaultSystemdStart re-runs the boot unit to apply the record set
// under CAP_NET_ADMIN. It is the delegation path: talking to PID 1
// needs root, not CAP_NET_ADMIN, and the unit systemd then launches
// carries the capability ambiently. The argv is wholly constant.
//
// IT MUST BE `restart`, NOT `start`. The unit is Type=oneshot with
// RemainAfterExit=yes, so after it has run at boot it sits in
// "active (exited)" — and `systemctl start` on an already-active unit
// is a NO-OP that exits ZERO without re-running ExecStart. Using
// `start` would therefore succeed silently on every box that had
// rebooted since its first bind, apply nothing, and hand back a
// zero exit for work that never happened. `restart` always re-runs
// ExecStart. (The verification read in ensureLive would still catch it
// and fail the bind, so this is the difference between "L3 works" and
// "L3 refuses on every rebooted relay" rather than a silent-success
// hole — but it is the whole feature either way.)
//
// Both verbs are synchronous for a oneshot: systemctl waits for
// ExecStart to finish and exits non-zero if the unit failed, so this is
// a real answer and not a fire-and-forget.
func defaultSystemdStart(unit string) error {
	out, err := exec.Command("systemctl", "restart", unit).CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl restart %s: %w (%s)", unit, err, strings.TrimSpace(string(out)))
	}
	return nil
}

func defaultSystemdReload() error {
	out, err := exec.Command("systemctl", "daemon-reload").CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl daemon-reload: %w (%s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}

// holdsCapNetAdmin reads the effective capability set from
// /proc/self/status.
//
// This is not a guess about how the process was started, it is what the
// kernel will enforce on the next netlink write. CAP_NET_ADMIN is bit
// 12. On a relay provisioned by the CURRENT cloud-init this returns
// true (daal-relay-mgmt.service carries
// AmbientCapabilities=CAP_NET_ADMIN); on one provisioned before that
// change it returns false, and probeAddressBinding then refuses the
// whole capability rather than advertise a bind it could not undo.
func holdsCapNetAdmin() bool {
	const capNetAdmin = 12
	body, err := os.ReadFile("/proc/self/status")
	if err != nil {
		return false
	}
	for _, line := range strings.Split(string(body), "\n") {
		if !strings.HasPrefix(line, "CapEff:") {
			continue
		}
		v, err := strconv.ParseUint(strings.TrimSpace(strings.TrimPrefix(line, "CapEff:")), 16, 64)
		if err != nil {
			return false
		}
		return v&(1<<capNetAdmin) != 0
	}
	return false
}

func haveBinary(name string) bool {
	_, err := exec.LookPath(name)
	return err == nil
}

// probeAddressBinding answers "can this box actually configure an
// address", which is a different question from "does this binary
// implement /bind-address".
//
// It is why capBindAddress is conditional. If the answer is no, the
// honest thing is to advertise nothing and let the publisher refuse
// with the Step-7 message, because a bind that cannot work must fail
// BEFORE the provider attach, not halfway through the swap.
//
// IT REQUIRES CAP_NET_ADMIN IN THIS PROCESS, and the reason is the
// half of the contract that has no delegation. This probe used to
// accept "systemctl exists" as sufficient, on the grounds that the
// boot unit runs under AmbientCapabilities=CAP_NET_ADMIN and can apply
// the record set for us. That is true of BINDING and false of
// UNBINDING: applyBoundRecords only ADDS (it must — at boot the
// interface holds the primary address, which is not a record, and a
// reconcile that removed non-records would delete it). So a box
// advertising the token off the systemd route promised two verbs and
// could only perform one, and the one it could not perform is the one
// on the failure paths: the rollback of a swap whose probe failed, and
// every `floating-ip release`. Both then hand an address back to the
// provider's pool while this box still has it configured — the exact
// T5 harm the ordering elsewhere in this file exists to prevent.
//
// The cloud-init this tree ships therefore grants the capability to
// daal-relay-mgmt.service (AmbientCapabilities=CAP_NET_ADMIN, matching
// sing-box.service on the same box). That is not a widening of what
// this process can already reach: it runs as root, writes
// /etc/systemd/system and asks PID 1 to start a unit it authored with
// AmbientCapabilities=CAP_NET_ADMIN — see ensureBootUnit — so the
// bounding set was never a boundary for it. Holding the capability
// directly only makes the two verbs symmetric and the failure honest.
//
// A relay provisioned before that cloud-init change reports FALSE here
// and the publisher refuses L3 on it, cleanly and before anything is
// reserved. That is the correct answer for such a box: it can bind and
// not unbind, so the swap it could perform is one it could never undo.
//
// systemctl is still required. Persistence is a systemd unit, and
// ensureBootUnit's daemon-reload failure is fatal to a bind (a record
// with no unit to re-apply it dies silently at the next reboot), so a
// box with no systemctl cannot honour the contract either.
//
// The returned note is diagnostic text for an operator who cannot SSH
// into the box to find out why the verb is missing — "too old binary",
// "no capability" and "no iproute2" have completely different remedies
// and an unexplained absence sends them to the wrong one.
func probeAddressBinding() (bool, string) {
	if !haveBinary("ip") {
		return false, "address binding unavailable: the `ip` utility (iproute2) is not installed on this box"
	}
	if !haveBinary("systemctl") {
		return false, "address binding unavailable: there is no systemctl, so an address could be configured now but not " +
			"persisted across a reboot (persistence is the " + bootUnitName + " oneshot)"
	}
	if !holdsCapNetAdmin() {
		return false, "address binding unavailable: this service holds no CAP_NET_ADMIN. It could still ADD an address by " +
			"delegating to " + bootUnitName + ", but it could never REMOVE one (the boot unit only adds), and a relay that can " +
			"bind without being able to unbind hands addresses back to the provider pool while it still holds them. " +
			"Reprovision this relay: the current cloud-init grants AmbientCapabilities=CAP_NET_ADMIN to daal-relay-mgmt.service"
	}
	return true, "address binding available: applied in-process (CAP_NET_ADMIN held)"
}

// --- reconciliation ---------------------------------------------------

// applyBoundRecords makes the interface hold every persisted record.
//
// ONE reconcile-from-records function serves the live bind, the retry
// after a delegated apply, and the boot path. That is deliberate: the
// alternative — "apply this one address" for the live path and "apply
// them all" at boot — is two code paths that must agree about
// validation and rendering forever, which is the shape of the bug this
// whole wave is fixing.
//
// It only ADDS. Removing an address the records do not mention is not
// this function's job: at boot the interface holds the primary address,
// which is not and must never be a record (T4).
func (s *server) applyBoundRecords(iface string) (applied []net.IP, warns []string, err error) {
	records, warns, err := listBoundRecords(s.boundAddrDir)
	if err != nil {
		return nil, warns, fmt.Errorf("read bound-address records: %w", err)
	}
	if len(records) == 0 {
		return nil, warns, nil
	}
	live, err := s.addrList(iface)
	if err != nil {
		return nil, warns, fmt.Errorf("list addresses on %s: %w", iface, err)
	}
	for _, want := range records {
		if containsIP(live, want) {
			applied = append(applied, want)
			continue
		}
		if aerr := s.addrAdd(iface, want); aerr != nil {
			err = errors.Join(err, aerr)
			continue
		}
		applied = append(applied, want)
	}
	return applied, warns, err
}

func containsIP(set []net.IP, want net.IP) bool {
	for _, got := range set {
		if got.Equal(want) {
			return true
		}
	}
	return false
}

// ensureLive brings ip up on the interface and VERIFIES it by reading
// the interface back, returning the method that worked.
//
// Two routes, tried in order:
//
//	direct   — `ip addr add` in this process. Needs CAP_NET_ADMIN,
//	           which probeAddressBinding now REQUIRES before the verb
//	           is advertised at all (only this route can also remove an
//	           address), so on any box that reaches this handler it is
//	           the route that works.
//	systemd  — `systemctl restart daal-bound-addresses.service`, which
//	           reconciles the record set (already written by the
//	           caller) under a unit PID 1 grants CAP_NET_ADMIN to. Kept
//	           as a fallback for the case where the direct add fails
//	           for a reason other than the capability, and because it
//	           is the same reconcile the boot path runs.
//
// The direct attempt is made first and its failure is not fatal.
// Whatever route ran, success is decided by LOOKING at the interface
// afterwards — a delegated apply hands back an exit status about a
// unit, not about an address, and reporting "bound" on the strength of
// that is how L3 came to claim success against a box that never
// answered. That rule applies to the FAILING branches too: a
// reconcile that could not apply some OTHER record exits non-zero
// while having applied ours, so the non-zero exit is re-checked
// against the interface rather than believed.
func (s *server) ensureLive(iface string, ip net.IP) (method string, warns []string, err error) {
	live, lerr := s.addrList(iface)
	if lerr != nil {
		return "", nil, fmt.Errorf("list addresses on %s: %w", iface, lerr)
	}
	if containsIP(live, ip) {
		return "already", nil, nil
	}

	var attempts []string
	if derr := s.addrAdd(iface, ip); derr != nil {
		attempts = append(attempts, "direct: "+derr.Error())
	} else if s.addrPresent(iface, ip) {
		return "direct", warns, nil
	} else {
		attempts = append(attempts, "direct: `ip addr add` reported success but the address is not on "+iface)
	}

	if s.systemdStart != nil {
		if serr := s.systemdStart(bootUnitName); serr != nil {
			// A non-zero exit is a statement about the UNIT, not about
			// this address. reapplyBoundAddresses fails the unit if ANY
			// record could not be applied, so a reconcile that put our
			// address on the interface and stumbled over an unrelated
			// stale record exits non-zero. Believing that would fail the
			// bind and then undo the persistence for an address that is
			// live — leaving it configured with no record, which the
			// record gate (T4) makes permanently unremovable through
			// this API. So look before concluding, exactly as the
			// success branch does.
			if s.addrPresent(iface, ip) {
				warns = append(warns, "applied via the "+bootUnitName+" delegation path, but that unit reported a failure "+
					"("+serr.Error()+"): "+canonicalIP(ip)+" IS on "+iface+", so this bind stands — some other persisted "+
					"address could not be applied and needs looking at")
				return "systemd", warns, nil
			}
			attempts = append(attempts, "systemd: "+serr.Error())
		} else if s.addrPresent(iface, ip) {
			// Said through Warnings because there is no wire field for
			// it and an invented one would be silently dropped by the
			// publisher's struct. An operator needs to know the apply
			// went through a unit rather than through this process.
			warns = append(warns, "applied via the "+bootUnitName+" delegation path: this service holds no CAP_NET_ADMIN")
			return "systemd", warns, nil
		} else {
			attempts = append(attempts, "systemd: "+bootUnitName+" ran but the address is not on "+iface)
		}
	}
	return "", warns, fmt.Errorf("could not configure %s on %s: %s",
		canonicalIP(ip), iface, strings.Join(attempts, "; "))
}

// addrPresent re-reads the interface. Verification is always a fresh
// read; a cached list from before the mutation would answer a question
// nobody asked.
func (s *server) addrPresent(iface string, ip net.IP) bool {
	live, err := s.addrList(iface)
	if err != nil {
		return false
	}
	return containsIP(live, ip)
}

// --- HTTP ------------------------------------------------------------

type bindAddressReq struct {
	IP string `json:"ip"`
}

// bindAddressResp is the answer to POST /bind-address.
//
// WIRE CONTRACT WITH publisher/deploy/mgmt.BindAddressResp. Every field
// name and type here is matched there, and that is not cosmetic: the
// publisher's struct SILENTLY DROPS unknown JSON keys, so a field this
// box invents dies in the middle of the hop with no error anywhere.
// That has already made one feature in this tree inert. Anything the
// box wants to say that has no field goes into Warnings, which the
// publisher renders verbatim — that is the only channel that cannot
// silently swallow a value.
//
// Persisted is separate from the status code on purpose. It is the
// field that separates "answers on this address now" from "answers on
// this address", and a caller that can only see 200 cannot tell a relay
// that survives a reboot from one that dies at 3am on a date nobody
// will connect to anything.
//
// BoundAddresses is the OPERATOR-BOUND record set — the addresses this
// API added and can remove — not every address on the interface. The
// primary address is deliberately absent: it is not something this API
// manages, it can never be unbound through it (see handleUnbindAddress,
// T4), and counting it against maxBoundAddresses would spend a quarter
// of the budget on an address no swap ever touches.
type bindAddressResp struct {
	IP             string   `json:"ip"`
	Interface      string   `json:"interface,omitempty"`
	AlreadyBound   bool     `json:"already_bound"`
	Persisted      bool     `json:"persisted"`
	PersistPath    string   `json:"persist_path,omitempty"`
	BoundAddresses []string `json:"bound_addresses,omitempty"`
	AppliedAtUnix  int64    `json:"applied_at_unix,omitempty"`
	Warnings       []string `json:"warnings,omitempty"`
}

// unbindAddressResp is the answer to POST /unbind-address, matched field
// for field with publisher/deploy/mgmt.UnbindAddressResp.
//
// The publisher reads these three together and each has a precise
// meaning it acts on:
//
//	WasBound=false, Removed=false            the idempotent no-op.
//	WasBound=true,  Removed=false            a FAILURE the box chose to
//	                                         report as 200; the caller
//	                                         treats it as an error.
//	Removed=true, PersistenceRemoved=false   live now, back at the next
//	                                         reboot, on an address this
//	                                         relay no longer owns.
//
// So Removed means "the address is no longer configured on the
// interface", which is answered by RE-READING the interface after the
// attempt — not by whether `ip addr del` exited zero. A record that was
// persisted but never live reports Removed=true because the statement
// is true, and reporting false would send the publisher down the
// "still configured" error path for a box that is in exactly the state
// the caller asked for.
//
// StillConfigured is the fourth reading and it exists because the third
// one had no field. When the address is NOT ours, this handler answers
// 200 with WasBound=false, Removed=false — the publisher's "no-op,
// nothing to do" reading — and puts "…but it IS on the interface and I
// did not remove it" in Warnings. Warnings are prose: mgmt.UnbindAddress
// could not act on it, every publisher call site discarded the struct,
// and `floating-ip release` went on to hand the address back to the
// provider's pool while this box was still answering on it. That is the
// T5 harm with the alarm wired to nothing. A machine-readable field is
// the fix; the publisher turns it into a hard error.
type unbindAddressResp struct {
	IP                 string   `json:"ip"`
	Removed            bool     `json:"removed"`
	WasBound           bool     `json:"was_bound"`
	PersistenceRemoved bool     `json:"persistence_removed"`
	StillConfigured    bool     `json:"still_configured"`
	BoundAddresses     []string `json:"bound_addresses,omitempty"`
	AppliedAtUnix      int64    `json:"applied_at_unix,omitempty"`
	Warnings           []string `json:"warnings,omitempty"`
}

// renderIPs renders a record set for the wire, canonical and sorted.
func renderIPs(ips []net.IP) []string {
	if len(ips) == 0 {
		return nil
	}
	out := make([]string, 0, len(ips))
	for _, ip := range ips {
		out = append(out, canonicalIP(ip))
	}
	sort.Strings(out)
	return out
}

// handleBindAddress configures a provider-routed address on the guest
// OS so the box actually answers on it.
//
// ORDER, AND WHY IT IS PERSIST-FIRST. The operation has two halves and
// a crash can land between them, so the question is not "can both
// fail" but "which residue is survivable".
//
//	persisted, not live   — the box does not answer on the address. The
//	                        publisher's health.AddressServes probe fails
//	                        and the swap refuses, hands the address back
//	                        and keeps the record on the working one.
//	                        LOUD, immediate, already handled.
//	live, not persisted   — the box answers. Every probe passes, the
//	                        swap commits, the operator is told it
//	                        worked. Then a reboot months later drops the
//	                        address and the relay dies for reasons
//	                        nobody can connect to anything. SILENT and
//	                        undateable.
//
// So the persistent record is written first and the live address
// second, because the only residue a crash can leave is the loud one.
//
// When the live half fails outright, the handler UNDOES the persistence
// before returning the error, so a refusal leaves nothing behind for
// the next reboot to claim (T5) — and the response says so. The boot
// unit is installed before either half, because a record with no unit
// to re-apply it is the silent-death case with extra steps.
func (s *server) handleBindAddress(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "method", http.StatusMethodNotAllowed)
		return
	}
	s.bindAddrCnt.Add(1)

	var req bindAddressReq
	if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
		http.Error(w, "decode: "+err.Error(), http.StatusBadRequest)
		return
	}
	ip, err := validateBindAddress(req.IP)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	// Refuse rather than half-apply if this box cannot actually do it.
	// The same answer /health advertises, so a publisher that honoured
	// the capability never reaches this; a publisher that did not gets
	// a 501 naming the reason instead of a partially bound box.
	if ok, note := s.addrCapability(); !ok {
		http.Error(w, note, http.StatusNotImplemented)
		return
	}

	// A dedicated mutex, NOT s.cfgMu. These handlers do not read or
	// write the sing-box config at all — every inbound already listens
	// on 0.0.0.0, so holding a new address needs no config change — and
	// taking the config lock here would serialise address work behind
	// multi-second rotations for no reason. What does need serialising
	// is the record set: the count check, the write and the apply must
	// not interleave with a concurrent unbind of the same address.
	s.addrMu.Lock()
	defer s.addrMu.Unlock()

	iface, err := s.primaryIface()
	if err != nil {
		http.Error(w, "interface: "+err.Error(), http.StatusInternalServerError)
		return
	}
	records, warns, err := listBoundRecords(s.boundAddrDir)
	if err != nil {
		http.Error(w, "read bound-address records: "+err.Error(), http.StatusInternalServerError)
		return
	}
	alreadyRecorded := containsIP(records, ip)

	// T4, THE HALF THAT WAS MISSING. Refuse to ADOPT an address that is
	// already on the interface and is not already one of our records.
	//
	// The unbind gate is "is it in the record set", and the claim that
	// makes that gate safe is "the primary address is never in the
	// record set". Nothing enforced the claim. Binding an address the
	// box already holds looked like a harmless no-op — validation
	// passes for any public unicast address, ensureLive answers
	// "already" and touches nothing — but it WROTE A RECORD, and a
	// record is precisely what makes an address removable. Two signed
	// calls, bind(primary) then unbind(primary), would then run
	// `ip addr del <primary> dev eth0` on a relay with no SSH: an
	// unrecoverable outage reachable by a leaked publisher key or by a
	// publisher bug that passes the wrong address variable, which are
	// exactly the residual threats this file says it defends against.
	//
	// Refusing costs nothing on the intended path: an L3 binds an
	// address the provider has just routed here and the guest OS does
	// NOT yet hold — that is the entire hardware finding. An address
	// already configured needs no bind, and if it is genuinely ours the
	// record exists and alreadyRecorded short-circuits this check.
	//
	// The read is fresh rather than reusing anything, because the
	// question is about the interface right now.
	if !alreadyRecorded {
		live, lerr := s.addrList(iface)
		if lerr != nil {
			http.Error(w, "list addresses on "+iface+": "+lerr.Error(), http.StatusInternalServerError)
			return
		}
		if containsIP(live, ip) {
			http.Error(w, fmt.Sprintf(
				"refusing to bind %s: it is already configured on %s and this service did not put it there. "+
					"Adopting it would add it to the record set, and anything in the record set can be removed through "+
					"/unbind-address — including this box's own primary address, whose removal is an unrecoverable outage "+
					"on a relay with no SSH. Nothing needs doing: the box already answers on this address",
				canonicalIP(ip), iface), http.StatusConflict)
			return
		}
	}

	// T3: the cap is checked against the persisted set, so a restart
	// cannot reset it. Re-binding an address already recorded is not a
	// new address and never trips the cap.
	if !alreadyRecorded && len(records) >= maxBoundAddresses {
		http.Error(w, fmt.Sprintf(
			"refusing to bind %s: this relay already holds %d operator-bound addresses, the maximum is %d — unbind one first",
			canonicalIP(ip), len(records), maxBoundAddresses), http.StatusConflict)
		return
	}

	// Persistence, half one of two: the unit that re-applies records
	// after a reboot. Fatal on failure — see the handler comment.
	if err := s.ensureBootUnit(); err != nil {
		http.Error(w, "persistence unavailable, refusing to bind an address that would be lost at the next reboot: "+err.Error(),
			http.StatusInternalServerError)
		return
	}
	// Persistence, half two: the record itself. Before the live half.
	if !alreadyRecorded {
		if err := writeBoundRecord(s.boundAddrDir, ip); err != nil {
			http.Error(w, "persist bound address: "+err.Error(), http.StatusInternalServerError)
			return
		}
	}

	// The live half.
	method, liveWarns, err := s.ensureLive(iface, ip)
	warns = append(warns, liveWarns...)
	if err != nil {
		// Undo our own persistence so a refusal leaves nothing for the
		// next reboot to claim (T5). Only what we just wrote: if the
		// record predates this call, some earlier successful bind owns
		// it and removing it here would silently unbind a working
		// address on behalf of a failed request.
		undone := "record left in place (it predates this request)"
		if !alreadyRecorded {
			if _, rerr := removeBoundRecord(s.boundAddrDir, ip); rerr != nil {
				undone = "WARNING: could not remove the persistence record just written (" + rerr.Error() +
					") — this box may claim " + canonicalIP(ip) + " at its next reboot"
			} else {
				undone = "persistence record removed; nothing was left behind"
			}
		}
		http.Error(w, err.Error()+" — "+undone, http.StatusInternalServerError)
		return
	}

	after, moreWarns, _ := listBoundRecords(s.boundAddrDir)
	warns = append(warns, moreWarns...)
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(bindAddressResp{
		IP:        canonicalIP(ip),
		Interface: iface,
		// "already" is the verdict from re-reading the interface: the
		// record was there AND the address was live. A record that had
		// gone stale on the interface and was just re-applied is NOT
		// already-bound, because something removed it and the operator
		// should see that this call had work to do.
		AlreadyBound:   alreadyRecorded && method == "already",
		Persisted:      true,
		PersistPath:    boundRecordFile(s.boundAddrDir, ip),
		BoundAddresses: renderIPs(after),
		AppliedAtUnix:  s.now().Unix(),
		Warnings:       dedupeWarnings(warns),
	})
}

// handleUnbindAddress removes an address this service bound.
//
// RECORD-GATED (T4). The interface is touched only for an address that
// is in the persistence record set. `ip addr del <primary> dev eth0` on
// a box with no SSH is an unrecoverable outage, and an unbind that
// accepted any address would put that one netlink call behind a single
// signature — reachable by a stolen key, and equally by a publisher bug
// that passes the wrong variable. The primary address is never a
// record, so it is not reachable from here at all — and bind refuses to
// adopt a live address precisely so that stays true. An unrecorded
// address is a quiet success, never an error: rotations retry, and "it
// is not bound by us" is the state the caller wanted. If it is
// nevertheless ON the interface, `still_configured` says so and the
// publisher stops before releasing it.
//
// ORDER, AND WHY IT IS THE REVERSE OF BIND. Here the dangerous residue
// is the box CONTINUING to hold an address the provider has taken back
// and re-issued to someone else, so the urgent half is the live one and
// it goes first. Neither half short-circuits the other: both are always
// attempted and both are reported, because stopping halfway through a
// removal leaves exactly the state the removal existed to prevent.
// Validation here is intentionally parse-only, without the public-range
// table: the record set is a far stronger gate than any range check,
// and refusing to clean up a record that somehow fell outside the
// ranges would strand it.
func (s *server) handleUnbindAddress(w http.ResponseWriter, r *http.Request) {
	if r.Method != "POST" {
		http.Error(w, "method", http.StatusMethodNotAllowed)
		return
	}
	s.unbindAddrCnt.Add(1)

	var req bindAddressReq
	if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&req); err != nil && !errors.Is(err, io.EOF) {
		http.Error(w, "decode: "+err.Error(), http.StatusBadRequest)
		return
	}
	raw := strings.TrimSpace(req.IP)
	if raw == "" {
		http.Error(w, `"ip" is required`, http.StatusBadRequest)
		return
	}
	// The T2 charset filter still applies — this value also becomes an
	// argv element — but the T1 range table does not; see the handler
	// comment.
	if !addrCharset.MatchString(raw) {
		http.Error(w, "malformed address: only hexadecimal digits, ':' and '.' are accepted", http.StatusBadRequest)
		return
	}
	ip := net.ParseIP(raw)
	if ip == nil {
		http.Error(w, fmt.Sprintf("not a valid IP address: %q", raw), http.StatusBadRequest)
		return
	}
	if v4 := ip.To4(); v4 != nil {
		ip = v4
	}

	s.addrMu.Lock()
	defer s.addrMu.Unlock()

	iface, ierr := s.primaryIface()
	records, warns, rerr := listBoundRecords(s.boundAddrDir)
	if rerr != nil {
		http.Error(w, "read bound-address records: "+rerr.Error(), http.StatusInternalServerError)
		return
	}
	recorded := containsIP(records, ip)

	resp := unbindAddressResp{
		IP:            canonicalIP(ip),
		WasBound:      recorded,
		AppliedAtUnix: s.now().Unix(),
	}
	if !recorded {
		// Not ours. Idempotent success (WasBound=false, Removed=false
		// is the publisher's no-op reading), and we say what we saw
		// rather than pretending the address is gone: if it IS live on
		// the interface, something other than this service put it there
		// — the primary address being the obvious candidate — and a
		// human needs to know this call did not remove it.
		resp.PersistenceRemoved = true // there was no record to remove
		if ierr == nil && s.addrPresent(iface, ip) {
			// The machine-readable half of the same sentence. See
			// unbindAddressResp: the prose below cannot stop a caller
			// from releasing the address, and this field can.
			resp.StillConfigured = true
			warns = append(warns, canonicalIP(ip)+" is configured on "+iface+" but was not bound by this service, "+
				"so it was NOT removed: this API only removes addresses it added, because removing the box's "+
				"primary address would be an unrecoverable outage on a relay with no SSH")
		}
		after, moreWarns, _ := listBoundRecords(s.boundAddrDir)
		warns = append(warns, moreWarns...)
		resp.BoundAddresses = renderIPs(after)
		resp.Warnings = dedupeWarnings(warns)
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(resp)
		return
	}

	// Live half FIRST, then the record; both attempted regardless.
	var failures []string
	if ierr != nil {
		failures = append(failures, "interface: "+ierr.Error())
	} else if s.addrPresent(iface, ip) {
		if err := s.addrDel(iface, ip); err != nil {
			// There is NO delegated fallback for a removal: the boot
			// unit only ADDS (it must — the primary address is not a
			// record and a reconcile that removed non-records would
			// delete it). That asymmetry is why probeAddressBinding
			// refuses to advertise this verb at all unless THIS process
			// holds CAP_NET_ADMIN, so reaching here with a permission
			// error means the box's unit was changed under us.
			// Report honestly and still remove the record, so at least
			// the next reboot does not re-assert an address the
			// provider may have re-issued to someone else.
			failures = append(failures, err.Error())
		}
	}
	removedRec, derr := removeBoundRecord(s.boundAddrDir, ip)
	resp.PersistenceRemoved = removedRec || derr == nil
	if derr != nil {
		failures = append(failures, "remove persistence record: "+derr.Error())
	}
	// Removed is decided by LOOKING, after both halves have run. A
	// record that was persisted but never live reports true, which is
	// the truthful statement "the address is not configured here".
	if ierr == nil {
		resp.Removed = !s.addrPresent(iface, ip)
		// Same statement, same source of truth, both branches: "is it
		// on the interface now". This one already fails with a 500, but
		// a field that meant different things on different paths would
		// be worse than no field.
		resp.StillConfigured = !resp.Removed
		if !resp.Removed && len(failures) == 0 {
			failures = append(failures, "`ip addr del` reported success but "+canonicalIP(ip)+" is still on "+iface)
		}
	}
	after, moreWarns, _ := listBoundRecords(s.boundAddrDir)
	warns = append(warns, moreWarns...)
	resp.BoundAddresses = renderIPs(after)
	resp.Warnings = dedupeWarnings(warns)

	if len(failures) > 0 {
		http.Error(w, fmt.Sprintf("unbind %s incomplete (live removed=%t, persistence removed=%t): %s",
			canonicalIP(ip), resp.Removed, resp.PersistenceRemoved, strings.Join(failures, "; ")),
			http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(resp)
}

func dedupeWarnings(in []string) []string {
	if len(in) == 0 {
		return nil
	}
	seen := map[string]bool{}
	var out []string
	for _, w := range in {
		if w == "" || seen[w] {
			continue
		}
		seen[w] = true
		out = append(out, w)
	}
	return out
}

// --- the boot path ----------------------------------------------------

// reapplyBoundAddresses is what the oneshot unit runs. It reconciles the
// record set onto the primary interface and reports per-record outcomes
// to the journal, which is the only place a human can read them on a
// box with no SSH.
//
// It shares applyBoundRecords with the live path, so validation and
// rendering cannot drift between "bound now" and "bound after a
// reboot".
func reapplyBoundAddresses(dir string, logf func(string, ...any)) error {
	s := &server{
		boundAddrDir: dir,
		addrList:     defaultAddrList,
		addrAdd:      defaultAddrAdd,
		now:          time.Now,
	}
	records, warns, err := listBoundRecords(dir)
	for _, w := range warns {
		logf("bound-addresses: %s", w)
	}
	if err != nil {
		return fmt.Errorf("read bound-address records: %w", err)
	}
	if len(records) == 0 {
		logf("bound-addresses: no records in %s; nothing to apply", dir)
		return nil
	}
	iface, err := detectPrimaryInterface()
	if err != nil {
		return err
	}
	applied, _, applyErr := s.applyBoundRecords(iface)
	for _, ip := range applied {
		logf("bound-addresses: %s is configured on %s", canonicalIP(ip), iface)
	}
	if applyErr != nil {
		// Non-zero exit: systemd marks the unit failed, which is the
		// only signal a human gets that this relay is not holding an
		// address it is supposed to hold.
		return applyErr
	}
	if len(applied) != len(records) {
		return fmt.Errorf("applied %d of %d recorded addresses on %s", len(applied), len(records), iface)
	}
	return nil
}
