package main

import (
	"encoding/base64"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// familyMatrixFile is the publisher's record of the CLIENT half of every
// transport family a Daal relay serves — the literal output of
// relaypack.ClientOutboundForFamily, regenerated by
// `go test ./deploy/relaypack -run TestClientOutboundMatrixIsCurrent
// -update-family-matrix` in the publisher module.
//
// It is read from disk rather than imported because this binary is its
// own Go module on purpose: it ships to relays as a hash-pinned artifact
// and must not carry the publisher's dependency tree. A file is the only
// seam the two halves share.
const familyMatrixFile = "../../publisher/deploy/relaypack/testdata/client_outbounds.json"

type matrixEntry struct {
	Port     int             `json:"port"`
	UDP      bool            `json:"udp"`
	Outbound json.RawMessage `json:"outbound"`
}

type matrixParams struct {
	Server           string `json:"Server"`
	Name             string `json:"Name"`
	VLESSUUID        string `json:"VLESSUUID"`
	RealityShortID   string `json:"RealityShortID"`
	RealityPublicKey string `json:"RealityPublicKey"`
	Hy2Password      string `json:"Hy2Password"`
	NaivePassword    string `json:"NaivePassword"`
	WSPath           string `json:"WSPath"`
	CoverSNI         string `json:"CoverSNI"`
	TUICUUID         string `json:"TUICUUID"`
	TUICPassword     string `json:"TUICPassword"`
	SSPassword       string `json:"SSPassword"`
	SSMethod         string `json:"SSMethod"`
	AnyTLSPassword   string `json:"AnyTLSPassword"`
}

type familyMatrix struct {
	Params   matrixParams           `json:"params"`
	Families map[string]matrixEntry `json:"families"`
}

func loadFamilyMatrix(t *testing.T) familyMatrix {
	t.Helper()
	raw, err := os.ReadFile(familyMatrixFile)
	if err != nil {
		t.Fatalf("read %s: %v\n\nRegenerate from the publisher module:\n"+
			"  cd publisher && go test ./deploy/relaypack -run TestClientOutboundMatrixIsCurrent -update-family-matrix",
			familyMatrixFile, err)
	}
	var m familyMatrix
	if err := json.Unmarshal(raw, &m); err != nil {
		t.Fatalf("parse %s: %v", familyMatrixFile, err)
	}
	if len(m.Families) == 0 {
		t.Fatalf("%s lists no families", familyMatrixFile)
	}
	return m
}

// boxSide is what this binary is expected to stand up for one family.
type boxSide struct {
	tag        string
	inboundTyp string
	clientTyp  string
	// udp is the transport the LISTENER binds. It must equal the
	// matrix's udp flag, which is what relayports declares and what both
	// firewalls open. A tcp rule in front of a udp listener is a family
	// that mints and cannot be dialled, and the two halves are written
	// in different modules, so nothing else compares them.
	udp bool
}

// boxSides is the box's half of the contract, family by family. Every
// entry is asserted against the publisher's real output below; the map
// exists so a family added to one side and not the other fails loudly
// instead of being skipped.
var boxSides = map[string]boxSide{
	"vless-reality": {tagVLESS, "vless", "vless", false},
	"hysteria2":     {tagHy2, "hysteria2", "hysteria2", true},
	"naive":         {tagNaive, "naive", "naive", false},
	"websocket-tls": {tagWS, "vless", "vless", false},
	"shadowsocks":   {tagSS, "shadowsocks", "shadowsocks", false},
	"anytls":        {tagAnyTLS, "anytls", "anytls", false},
	"tuic":          {tagTUIC, "tuic", "tuic", true},
}

// agreementScaffold is the config cloud-init writes for a relay whose
// profile enabled every family cloud-init owns (vless-in, hy2-in,
// tuic-in). The rest are created by this binary on first provision, which
// is exactly what the test then exercises.
//
// The REALITY server_name is taken from the matrix params rather than
// invented, because the cover host is one of the values the two halves
// have to agree on byte for byte.
func agreementScaffold(t *testing.T, coverSNI string) string {
	t.Helper()
	body, err := json.Marshal(map[string]any{
		"log": map[string]any{"level": "info"},
		"inbounds": []any{
			map[string]any{
				"type": "vless", "tag": tagVLESS, "listen_port": float64(443),
				"users": []any{},
				"tls": map[string]any{"enabled": true, "server_name": coverSNI,
					"reality": map[string]any{"enabled": true, "short_id": []any{},
						"handshake": map[string]any{"server": coverSNI, "server_port": float64(443)}}},
			},
			map[string]any{"type": "hysteria2", "tag": tagHy2, "listen_port": float64(443), "users": []any{}},
			map[string]any{
				"type": "tuic", "tag": tagTUIC, "listen_port": float64(tuicListenPort),
				"users": []any{}, "congestion_control": "bbr",
				"tls": map[string]any{"enabled": true, "alpn": []any{"h3"},
					"certificate_path": tlsCertPath, "key_path": tlsKeyPath},
			},
		},
		"outbounds": []any{map[string]any{"type": "direct"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "config.json")
	if err := os.WriteFile(path, body, 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// TestBoxAndClientAgreePerFamily is the cross-check no single owner of
// this wave could run.
//
// Every transport family in Daal has three halves in three Go modules
// that cannot import one another: the publisher mints the client
// outbound, this binary serves the box inbound, and core/engine dials
// it. Each half is internally consistent and tested, so a disagreement
// BETWEEN them is invisible everywhere — it shows up on the wire, as a
// route the recipient selects and loses, with nothing in the UI able to
// say why. Wave 5 added four families across four parallel owners, which
// is four chances to spell a port, a type, a user-list key or a
// credential differently on the two sides.
//
// So: feed this binary the same inputs the publisher was rendered from,
// then compare the resulting box config against the publisher's actual
// output, family by family, on the four things that have to match —
// type, port, protocol, credentials.
func TestBoxAndClientAgreePerFamily(t *testing.T) {
	m := loadFamilyMatrix(t)
	p := m.Params

	// The box's shadowsocks uPSK is the second half of the password the
	// client presents; the join rule lives in exactly one place
	// (ssClientPassword) and this is the test reading it from the other
	// side. Deriving it here rather than hard-coding a value is the
	// point: if the publisher ever emitted a password in a different
	// shape, this split would produce a key the box refuses.
	ssUPSK := ""
	if i := strings.LastIndex(p.SSPassword, ":"); i >= 0 {
		ssUPSK = p.SSPassword[i+1:]
	}

	creds := userCreds{
		Name:           p.Name,
		VLESSUUID:      p.VLESSUUID,
		RealityShortID: p.RealityShortID,
		Hy2Password:    p.Hy2Password,
		NaivePassword:  p.NaivePassword,
		WSPath:         p.WSPath,
		TUICUUID:       p.TUICUUID,
		TUICPassword:   p.TUICPassword,
		SSUserPSK:      ssUPSK,
		AnyTLSPassword: p.AnyTLSPassword,
	}

	path := agreementScaffold(t, p.CoverSNI)
	if _, err := addUserToSingbox(path, creds, nil); err != nil {
		t.Fatalf("addUserToSingbox: %v", err)
	}
	doc, err := loadSingboxDoc(path)
	if err != nil {
		t.Fatal(err)
	}

	// Neither side may carry a family the other does not.
	var haveMatrix, haveBox []string
	for f := range m.Families {
		haveMatrix = append(haveMatrix, f)
	}
	for f := range boxSides {
		haveBox = append(haveBox, f)
	}
	sort.Strings(haveMatrix)
	sort.Strings(haveBox)
	if strings.Join(haveMatrix, ",") != strings.Join(haveBox, ",") {
		t.Fatalf("the publisher mints %v but this binary claims to serve %v; one side has a "+
			"family the other does not, which is either a listener nobody can use or a route "+
			"nobody can dial", haveMatrix, haveBox)
	}

	for family, e := range m.Families {
		side := boxSides[family]
		t.Run(family, func(t *testing.T) {
			var client map[string]any
			if err := json.Unmarshal(e.Outbound, &client); err != nil {
				t.Fatal(err)
			}
			in := findInboundByTag(doc, side.tag)
			if in == nil {
				t.Fatalf("the publisher mints a %s route but this binary left no %q inbound in the config",
					family, side.tag)
			}

			// --- type -------------------------------------------------
			if got, _ := in["type"].(string); got != side.inboundTyp {
				t.Errorf("box inbound type = %q, want %q", got, side.inboundTyp)
			}
			if got, _ := client["type"].(string); got != side.clientTyp {
				t.Errorf("client outbound type = %q, want %q", got, side.clientTyp)
			}

			// --- port -------------------------------------------------
			boxPort, ok := numericPort(in["listen_port"])
			if !ok {
				t.Fatalf("box inbound %q has no numeric listen_port: %v", side.tag, in["listen_port"])
			}
			clientPort := 0
			if f, ok := client["server_port"].(float64); ok {
				clientPort = int(f)
			}
			if boxPort != e.Port || clientPort != e.Port {
				t.Errorf("port disagreement: relayports says %d, box binds %d, client dials %d",
					e.Port, boxPort, clientPort)
			}

			// --- protocol ---------------------------------------------
			if side.udp != e.UDP {
				t.Errorf("this binary serves %s over udp=%v but relayports declares udp=%v; the "+
					"firewall rule follows relayports, so one of them opens the wrong socket",
					family, side.udp, e.UDP)
			}
			// shadowsocks is the one family whose inbound narrows the
			// protocol explicitly. It must stay TCP-only: the client
			// compensates with udp_over_tcp and only 8446/tcp is opened,
			// so a udp listener here would bind a socket no packet
			// reaches.
			if family == "shadowsocks" {
				if net, _ := in["network"].(string); net != "tcp" {
					t.Errorf("ss-in network = %q, want \"tcp\"", net)
				}
				uot, _ := client["udp_over_tcp"].(map[string]any)
				if uot == nil || uot["enabled"] != true {
					t.Error("client shadowsocks outbound has no udp_over_tcp; on a tcp-only " +
						"inbound that route has no DNS and no QUIC")
				}
			}

			// --- credentials ------------------------------------------
			assertCredentialsAgree(t, family, in, client, p, ssUPSK)
		})
	}
}

// assertCredentialsAgree compares the secret material on the two sides.
// Every family authenticates differently, so this is per-family by
// necessity; what it must never become is a check that both sides are
// merely non-empty.
func assertCredentialsAgree(t *testing.T, family string, in, client map[string]any, p matrixParams, ssUPSK string) {
	t.Helper()
	users := boxUsers(t, in)

	switch family {
	case "vless-reality", "websocket-tls":
		u := boxUserNamed(t, users, p.Name)
		if got, _ := u["uuid"].(string); got != p.VLESSUUID {
			t.Errorf("box uuid = %q, want %q", got, p.VLESSUUID)
		}
		if got, _ := client["uuid"].(string); got != p.VLESSUUID {
			t.Errorf("client uuid = %q, want %q", got, p.VLESSUUID)
		}
		if family == "vless-reality" {
			// The cover host is not a credential but it fails the same
			// way: REALITY refuses a ClientHello whose SNI is not the
			// name the inbound advertises, before authentication.
			boxTLS, _ := in["tls"].(map[string]any)
			clientTLS, _ := client["tls"].(map[string]any)
			boxSNI, _ := boxTLS["server_name"].(string)
			clientSNI, _ := clientTLS["server_name"].(string)
			if boxSNI == "" || boxSNI != clientSNI {
				t.Errorf("cover host disagreement: box advertises %q, client sends %q", boxSNI, clientSNI)
			}
		} else {
			// The ws path is chosen by the box (shared across
			// recipients) and echoed to the publisher. A mismatch is a
			// 404 on every request.
			boxTr, _ := in["transport"].(map[string]any)
			clientTr, _ := client["transport"].(map[string]any)
			boxPath, _ := boxTr["path"].(string)
			clientPath, _ := clientTr["path"].(string)
			if boxPath == "" || boxPath != clientPath {
				t.Errorf("ws path disagreement: box serves %q, client requests %q", boxPath, clientPath)
			}
		}

	case "hysteria2":
		u := boxUserNamed(t, users, p.Name)
		if got, _ := u["password"].(string); got != p.Hy2Password {
			t.Errorf("box password = %q, want %q", got, p.Hy2Password)
		}
		if got, _ := client["password"].(string); got != p.Hy2Password {
			t.Errorf("client password = %q, want %q", got, p.Hy2Password)
		}

	case "naive":
		// naive's user key is "username", not "name" — the one family
		// that spells it differently, and the reason this check reads
		// the real key rather than a shared helper.
		var u map[string]any
		for _, raw := range users {
			m, _ := raw.(map[string]any)
			if n, _ := m["username"].(string); n == p.Name {
				u = m
			}
		}
		if u == nil {
			t.Fatalf("no naive user with username=%q in %v", p.Name, users)
		}
		if got, _ := u["password"].(string); got != p.NaivePassword {
			t.Errorf("box password = %q, want %q", got, p.NaivePassword)
		}
		if got, _ := client["username"].(string); got != p.Name {
			t.Errorf("client username = %q, want %q — naive auth is on the pair", got, p.Name)
		}
		if got, _ := client["password"].(string); got != p.NaivePassword {
			t.Errorf("client password = %q, want %q", got, p.NaivePassword)
		}

	case "tuic":
		// tuic authenticates on BOTH halves; a row carrying one is a row
		// that never authenticates.
		u := boxUserNamed(t, users, p.Name)
		if got, _ := u["uuid"].(string); got != p.TUICUUID {
			t.Errorf("box uuid = %q, want %q", got, p.TUICUUID)
		}
		if got, _ := u["password"].(string); got != p.TUICPassword {
			t.Errorf("box password = %q, want %q", got, p.TUICPassword)
		}
		if got, _ := client["uuid"].(string); got != p.TUICUUID {
			t.Errorf("client uuid = %q, want %q", got, p.TUICUUID)
		}
		if got, _ := client["password"].(string); got != p.TUICPassword {
			t.Errorf("client password = %q, want %q", got, p.TUICPassword)
		}
		if p.TUICUUID == p.VLESSUUID {
			t.Error("the tuic uuid must be minted independently of the vless one: one leaked " +
				"pack would otherwise link the recipient across two tiers")
		}

	case "anytls":
		u := boxUserNamed(t, users, p.Name)
		if got, _ := u["password"].(string); got != p.AnyTLSPassword {
			t.Errorf("box password = %q, want %q", got, p.AnyTLSPassword)
		}
		if got, _ := client["password"].(string); got != p.AnyTLSPassword {
			t.Errorf("client password = %q, want %q", got, p.AnyTLSPassword)
		}
		// The scheme is per-relay and negotiated in band, so the client
		// must NOT carry one. A padding_scheme in the outbound is not a
		// harmless extra key — option.AnyTLSOutboundOptions has no such
		// field and the strict parser rejects the whole config.
		if _, has := client["padding_scheme"]; has {
			t.Error("client anytls outbound carries padding_scheme; the outbound options have no " +
				"such field and sing-box would reject the route")
		}
		if _, has := in["padding_scheme"]; !has {
			t.Error("anytls-in has no padding_scheme; every unconfigured anytls deployment then " +
				"shares one record-size distribution")
		}

	case "shadowsocks":
		// The method is a wire contract: both sides derive keys from it,
		// and a mismatch is a relay that refuses to start or a route
		// that never authenticates.
		boxMethod, _ := in["method"].(string)
		clientMethod, _ := client["method"].(string)
		if boxMethod != clientMethod {
			t.Errorf("method disagreement: box serves %q, client presents %q", boxMethod, clientMethod)
		}
		if boxMethod != ssMethod {
			t.Errorf("box method = %q, want the one method this binary serves (%q)", boxMethod, ssMethod)
		}
		// The client's password is "<box iPSK>:<recipient uPSK>", and the
		// box is the only place that join rule lives. Check the shape
		// the box produces and the shape the publisher shipped are the
		// same, and that the uPSK half really is this recipient's row.
		u := boxUserNamed(t, users, p.Name)
		if got, _ := u["password"].(string); got != ssUPSK {
			t.Errorf("box uPSK = %q, want the second half of the client password (%q)", got, ssUPSK)
		}
		assertSSPasswordShape(t, "client", p.SSPassword)
		assertSSPasswordShape(t, "box", ssClientPassword(mustDoc(t, in), p.Name))
		if p.SSMethod != ssMethod {
			t.Errorf("the matrix advertises method %q but this binary serves %q", p.SSMethod, ssMethod)
		}

	default:
		t.Fatalf("no credential comparison for family %q — add one rather than letting it pass", family)
	}
}

// assertSSPasswordShape pins the encoding contract that cost this family
// a landmine already: the halves are PADDED base64-STD (not the
// RawURLEncoding hy2/naive use), and each decodes to exactly the key
// length the method requires. sing-shadowsocks2 refuses any other
// length at service construction, which on the box is a FATAL at start.
func assertSSPasswordShape(t *testing.T, side, password string) {
	t.Helper()
	if password == "" {
		t.Fatalf("%s shadowsocks password is empty", side)
	}
	parts := strings.Split(password, ":")
	if len(parts) != 2 {
		t.Fatalf("%s shadowsocks password has %d colon-separated parts, want 2 (iPSK:uPSK)", side, len(parts))
	}
	for i, half := range parts {
		raw, err := base64.StdEncoding.DecodeString(half)
		if err != nil {
			t.Errorf("%s shadowsocks password half %d is not padded base64-std: %v", side, i, err)
			continue
		}
		if len(raw) != ssKeyBytes {
			t.Errorf("%s shadowsocks password half %d decodes to %d bytes, want %d for %s",
				side, i, len(raw), ssKeyBytes, ssMethod)
		}
	}
}

// mustDoc wraps a single inbound back into a config-shaped document so
// ssClientPassword — which reads the live config, exactly as the
// provision handler does — can be exercised against it.
func mustDoc(t *testing.T, in map[string]any) map[string]any {
	t.Helper()
	return map[string]any{"inbounds": []any{in}}
}

func boxUsers(t *testing.T, in map[string]any) []any {
	t.Helper()
	users, _ := in["users"].([]any)
	if len(users) == 0 {
		t.Fatalf("inbound %v has no users; the recipient cannot authenticate", in["tag"])
	}
	return users
}

func boxUserNamed(t *testing.T, users []any, name string) map[string]any {
	t.Helper()
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			return u
		}
	}
	t.Fatalf("no user named %q in %v", name, users)
	return nil
}

// TestEveryFamilyTogetherLoadsInRealSingBox is the box-side complement
// of core/engine's TestEveryMintedOutboundParses, and it closes the gap
// that made it worth writing.
//
// TestGeneratedConfigLoadsInRealSingBox already runs the shipped binary
// over a config this service produces — but it provisions recipients
// with no SSUserPSK, no AnyTLSPassword and no tuic pair, so appendSSUser,
// appendAnyTLSUser and appendTUICUser all return early and the real
// parser has never once seen ss-in, anytls-in or tuic-in in the same
// document. Wave 5 added three inbounds that no `sing-box check` in this
// repo covers.
//
// That matters more here than on the client. A client outbound sing-box
// refuses is one dead tier; a BOX config sing-box refuses does not start
// the process at all, so every family on that relay goes dark at once —
// and the failure lands at first boot on a machine nobody can log into
// yet. `check` is the only oracle for the class of bug that has actually
// hit this file: a key in the wrong encoding, a block on an inbound that
// does not define it, a padding scheme that marshals as one line.
//
// Two recipients, because the multi-user paths are where the shared
// inbounds (ss-in's users[], anytls-in's users[], ws-in's one path) are
// exercised rather than just created.
//
// WHAT `check` DOES NOT COVER, measured rather than assumed. It DECODES
// the config; it does not CONSTRUCT the services. Both of these were
// tried against this test and both passed it:
//
//   - a shadowsocks PSK of the wrong length. shadowaead_2022 refuses it
//     at service construction ("bad key length"), which is a FATAL at
//     `run` and therefore a relay that boots nowhere — but `check`
//     never gets there.
//   - an anytls padding_scheme emitted as one newline-joined string
//     instead of an array. badoption.Listable accepts a bare string, so
//     it decodes; it then fails to parse into a scheme at runtime.
//
// So this is an oracle for the shape/unknown-field/wrong-nesting class
// (verified: an unknown key on ss-in does fail it) and for nothing
// beyond. The length and encoding contracts are held by the unit tests
// in singbox_shadowsocks_test.go and by assertSSPasswordShape above.
func TestEveryFamilyTogetherLoadsInRealSingBox(t *testing.T) {
	bin := singboxBinaryForTest(t)
	if bin == "" {
		t.Skip("dist-release sing-box artifact not present; skipping real-parser check")
	}
	tmp := t.TempDir()
	certPath := filepath.Join(tmp, "tls-cert.pem")
	keyPath := filepath.Join(tmp, "tls-key.pem")
	if _, err := ensureSelfSignedCert(certPath, keyPath, filepath.Join(tmp, "fpr")); err != nil {
		t.Fatal(err)
	}

	// cloud-init's scaffold for a relay whose profile enabled tuic, with
	// a genuine REALITY private key (the parser validates its length).
	path := filepath.Join(tmp, "config.json")
	scaffold := `{
  "log": {"level":"info"},
  "inbounds": [
    {"type":"vless","tag":"` + tagVLESS + `","listen":"0.0.0.0","listen_port":443,"users":[],
     "tls":{"enabled":true,"server_name":"news.example.org",
            "reality":{"enabled":true,"private_key":"YAoRLRs2r1PUyGZmSMOoGuFo9UbnrxWiCPMEjZoQdmc",
                       "short_id":[],"handshake":{"server":"news.example.org","server_port":443}}}},
    {"type":"hysteria2","tag":"` + tagHy2 + `","listen":"0.0.0.0","listen_port":443,"users":[],
     "tls":{"enabled":true,"certificate_path":"` + certPath + `","key_path":"` + keyPath + `"}},
    {"type":"tuic","tag":"` + tagTUIC + `","listen":"0.0.0.0","listen_port":` + itoa(tuicListenPort) + `,
     "users":[],"congestion_control":"bbr",
     "tls":{"enabled":true,"alpn":["h3"],"certificate_path":"` + certPath + `","key_path":"` + keyPath + `"}}
  ],
  "outbounds":[{"type":"direct"}]
}`
	if err := os.WriteFile(path, []byte(scaffold), 0o644); err != nil {
		t.Fatal(err)
	}

	// mintCreds is the real minter, so the shadowsocks uPSK and the
	// anytls password are the real shapes rather than test strings —
	// which is the point for SS, whose key length is checked at service
	// construction and whose base64 alphabet has already cost this file
	// a bug.
	for _, name := range []string{"r1", "r2"} {
		c, err := mintCreds(name, 1700000000)
		if err != nil {
			t.Fatalf("mintCreds(%s): %v", name, err)
		}
		if c.SSUserPSK == "" || c.AnyTLSPassword == "" || c.TUICUUID == "" || c.TUICPassword == "" {
			t.Fatalf("mintCreds(%s) left a Wave 5 credential empty: %+v", name, c)
		}
		if _, err := addUserToSingbox(path, c, nil); err != nil {
			t.Fatalf("addUserToSingbox(%s): %v", name, err)
		}
		// The data-plane cert paths are compile-time constants under
		// /etc/daal; retarget them at the temp leaf so the parser can
		// load them here.
		retargetCertPaths(t, path, certPath, keyPath)
	}

	doc, err := loadSingboxDoc(path)
	if err != nil {
		t.Fatal(err)
	}
	for family, side := range boxSides {
		in := findInboundByTag(doc, side.tag)
		if in == nil {
			t.Fatalf("%s: no %q inbound — this test would then be checking a config that does "+
				"not contain the thing it exists to check", family, side.tag)
		}
		users, _ := in["users"].([]any)
		if len(users) != 2 {
			t.Errorf("%s (%s): %d users, want 2 — the shared-inbound path is what this test is for",
				family, side.tag, len(users))
		}
	}

	out, err := exec.Command(bin, "check", "-c", path).CombinedOutput()
	if err != nil {
		t.Fatalf("sing-box 1.13.12 rejected a config carrying every family this relay serves: %s\n\nconfig: %s",
			out, mustReadFile(t, path))
	}
}

func itoa(n int) string { return strconv.Itoa(n) }

func mustReadFile(t *testing.T, p string) string {
	t.Helper()
	b, err := os.ReadFile(p)
	if err != nil {
		return "<unreadable: " + err.Error() + ">"
	}
	return string(b)
}
