// FRP-14: surgical sing-box rewriter for the users[] table.
//
// The supported transports each have a dedicated inbound
// (matched by `tag`):
//
//	tag = "vless-in"     → VLESS-Reality   (users[] + reality.short_id[])
//	tag = "hy2-in"       → Hysteria2       (users[])
//	tag = "naive-in"     → Naive           (users[])
//	tag = "ws-in"        → VLESS-over-WS   (users[])
//	tag = "tuic-in"      → TUIC            (users[]; uuid AND password)
//
// On `addUserToSingbox`, the rewriter appends the new user row to every
// inbound it finds (creating the inbound if absent — this covers the
// empty-users[] first-boot case). On `removeUserFromSingbox` the
// inverse runs, idempotently.
//
// TUIC IS OPT-IN AT PROVISION TIME, unlike the other four. vless-in and
// hy2-in are baked into cloud-init on every relay; naive-in and ws-in
// are created here on first use because they cannot exist without a
// user. tuic-in is neither: it is written into cloud-init ONLY when the
// toolbox profile enabled the tuic family (see the hetzner adapter's
// defaultSingBoxConfig), because binding 8443/udp on a relay nobody
// asked to serve tuic on would add a third fleet-wide constant port for
// nothing. So appendTUICUser follows the hy2 pattern — append if the
// inbound is there, no-op if it is not — and NEVER creates it.
//
// SHARED WS PATH — read before changing this. Every recipient shares
// ONE ws-in inbound and therefore ONE `transport.path` (see :55-68 and
// appendWSUser). The earlier design gave each recipient its own
// `ws-r<id>` inbound; that could not work, because a single port cannot
// host per-user WS inbounds — the second recipient collided on port
// 8445 and crashed sing-box.
//
// The privacy cost is real and deliberate: because the path is shared,
// one leaked pack discloses the WS path that EVERY recipient on this
// relay uses. Revoking a recipient removes their user row, not the
// path. Anything that reasons about per-recipient WS isolation is
// wrong; only the credentials are per-recipient.
//
// We work over a generic map[string]any decode of the config so
// non-Daal sections (route tables, DNS, log levels) survive
// byte-equal across rewrites except where touched.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const (
	tagVLESS = "vless-in"
	tagHy2   = "hy2-in"
	tagNaive = "naive-in"
	tagWS    = "ws-in"   // single shared VLESS-over-WS inbound (all recipients)
	tagTUIC  = "tuic-in" // optional TUIC inbound; present only when provisioned

	// Data-plane self-signed TLS cert for the hy2/naive/ws inbounds
	// (TLS families that, unlike REALITY, need a cert). Generated by
	// cloud-init at first boot; equals main.go newServer's hardcoded
	// s.tlsCertPath. Keep the two in sync.
	tlsCertPath = "/etc/daal/tls-cert.pem"
	tlsKeyPath  = "/etc/daal/tls-key.pem"

	// wsListenPort / naiveListenPort are the WS-TLS and Naive inbound
	// ports. Local copies of publisher/deploy/relayports.For(...).Port
	// ("websocket-tls"=8445, "naive"=8444): relay-mgmt is a separate
	// module and importing the publisher package here would pull the
	// whole publisher dependency tree into the on-box binary, so we
	// mirror the single values with these pointers.
	wsListenPort    = 8445
	naiveListenPort = 8444

	// tuicListenPort mirrors relayports.For("tuic").Port. It is NOT
	// 443/udp: hysteria2 owns that socket, and sing-box does not treat a
	// second UDP inbound on the same port as a soft conflict — it
	// refuses to bind and the box does not boot (BUG-14). 8443 is also
	// not whitelisted egress in the primary target country, which is
	// recorded in relayports and repeated in every user-visible label
	// this family carries.
	tuicListenPort = 8443
)

// muxInbound is the `multiplex` block written onto the two vless-family
// inbounds (vless-in, ws-in).
//
// WHY. Xue et al. (USENIX Security 2024) detect nested-TLS proxies —
// REALITY + Vision included — at >70% TPR for 0.054% FPR, and the one
// mitigation the paper measures as effective (>70% detection reduction)
// is aggressive stream multiplexing: many concurrent streams over one
// TCP connection, so the per-flow shape the classifier keys on stops
// existing. Daal ships exactly the shape that work targets.
//
// BACKWARD COMPATIBILITY — the load-bearing question, answered
// empirically against sing-box 1.13.12, not assumed. A mux-enabled
// inbound still serves clients that know nothing about mux: sing-box
// wraps the inbound router (common/mux/router.go) and hands a
// connection to the mux service ONLY when its destination equals the
// magic mux destination; every other connection falls straight through
// to the normal router. Confirmed on the wire by running a real 1.13.12
// server + client pair over loopback: mux inbound + non-mux client
// fetched the origin fine, for both the REALITY-shaped vless inbound
// and the ws one. So enabling this on a live relay does NOT break the
// packs already in recipients' hands.
//
// The reverse is NOT true and must not be assumed: a mux CLIENT against
// a relay that predates this block fails hard ("global multiplex is
// deprecated since sing-box v1.7.0" from the router, connection
// dropped). Pack minting therefore has to gate the outbound `multiplex`
// on the relay actually having it — an updated pack is not safe against
// an un-updated box.
//
// PADDING is an enforcement flag here, not a behaviour flag: with
// padding=true the server REJECTS a mux client that did not pad
// ("non-padded connection rejected", verified). Client and box must
// agree. Keep this in lockstep with the outbound renderer's
// `"padding": true`; flipping one side alone breaks every mux route.
//
// NOT hy2-in, NOT naive-in. hysteria2 is QUIC-native — smux over TCP
// would add head-of-line blocking it does not have, and sing-box does
// not define the field there anyway: both inbounds reject the key
// outright with `json: unknown field "multiplex"`, which is a FATAL at
// boot, i.e. a bricked relay. Verified.
func muxInbound() map[string]any {
	return map[string]any{"enabled": true, "padding": true}
}

// addUserToSingbox loads /etc/sing-box/config.json, appends the
// user across all four inbound types, and atomically writes it back.
// It returns the effective ws path baked into the user's WS route:
// the first recipient's minted path becomes the shared ws-in path, and
// every later recipient reuses it (a single port can't host per-user ws
// inbounds), so the caller must persist the returned path in the creds
// it hands back to the client.
// validate, when non-nil, is handed the candidate config before it
// replaces the live one; see defaultSingboxCheck. Provisioning reloads
// sing-box immediately afterwards, so an unloadable config here takes
// the relay down as surely as a bad rotation does.
func addUserToSingbox(path string, c userCreds, validate func(string) error) (string, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return "", err
	}
	// Reuse the shared ws-in path if the inbound already exists so all
	// recipients land on one inbound with one consistent path.
	if existing := wsInboundPath(doc); existing != "" {
		c.WSPath = existing
	}
	if err := appendVLESSUser(doc, c); err != nil {
		return "", err
	}
	if err := appendHy2User(doc, c); err != nil {
		return "", err
	}
	if err := appendNaiveUser(doc, c); err != nil {
		return "", err
	}
	if err := appendWSUser(doc, c); err != nil {
		return "", err
	}
	// WAVE 5. shadowsocks-2022 — the only family here with no TLS
	// handshake in it, and therefore the only one the Xue et al.
	// nested-TLS classifier cannot reach. Creates ss-in on first use
	// (see singbox_shadowsocks.go for why it must never exist empty).
	if err := appendSSUser(doc, c); err != nil {
		return "", err
	}
	// WAVE 5. anytls — the one family whose length padding and session
	// reuse are protocol features rather than add-ons. Creates anytls-in
	// on first use with THIS relay's own padding scheme; see
	// singbox_anytls.go for why the scheme is per-relay and why it needs
	// no client-side plumbing.
	if err := appendAnyTLSUser(doc, c); err != nil {
		return "", err
	}
	// No-op when the relay was not provisioned to serve tuic. The
	// publisher learns which happened from the creds it gets back, not
	// from an error here: see tuicUserPresent.
	appendTUICUser(doc, c)
	// Runs on every provision, not just the first, so a relay built
	// before multiplex existed acquires it the next time a recipient is
	// added — there is no other routine write path to this file, and the
	// alternative is a fleet that stays fingerprintable until it is
	// reprovisioned from scratch.
	ensureMultiplexInbounds(doc)
	if err := writeSingboxDoc(path, doc, validate); err != nil {
		return "", err
	}
	return c.WSPath, nil
}

// ensureMultiplexInbounds stamps the multiplex block onto every
// vless-family inbound (vless-in and ws-in) and onto nothing else. See
// muxInbound for why, for the compatibility evidence, and for why
// touching hy2-in/naive-in would brick the box.
//
// Idempotent, and it does not clobber an operator's hand-tuned block:
// an existing `multiplex` object is only forced to enabled+padded, so
// re-running this never flips a box from working to rejecting.
func ensureMultiplexInbounds(doc map[string]any) {
	inbounds, _ := doc["inbounds"].([]any)
	for _, raw := range inbounds {
		in, _ := raw.(map[string]any)
		if in == nil {
			continue
		}
		if t, _ := in["type"].(string); t != "vless" {
			continue
		}
		mux, _ := in["multiplex"].(map[string]any)
		if mux == nil {
			in["multiplex"] = muxInbound()
			continue
		}
		mux["enabled"] = true
		mux["padding"] = true
	}
}

// coverSNI returns the REALITY cover host this box actually advertises,
// read from the live config rather than from anything the caller
// remembers.
//
// The box is the single source of truth for this value: it is written
// once at provision time and moved only by /rotate-tls, and the client
// outbound's `tls.server_name` MUST equal it or REALITY fails. Echoing
// it back on every provision is what lets a pack carry a per-relay
// cover host instead of a compile-time constant shared by the fleet.
func coverSNI(doc map[string]any) string {
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return ""
	}
	t, _ := in["tls"].(map[string]any)
	if t == nil {
		return ""
	}
	s, _ := t["server_name"].(string)
	return s
}

// readCoverSNI loads the config and returns its advertised cover SNI,
// or "" when it cannot be determined.
func readCoverSNI(path string) string {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return ""
	}
	return coverSNI(doc)
}

// muxInboundEnabled reports whether EVERY vless-family inbound carries
// an enabled multiplex block.
//
// "Every", not "any", on purpose: the publisher gets one boolean and
// mints one pack covering both the vless-reality and websocket-tls
// routes. If only one of the two inbounds had the block, a true here
// would produce a pack with a mux outbound on a route the box cannot
// serve — one dead tier, silently. Under-reporting only costs the
// multiplexing benefit until the next provision runs
// ensureMultiplexInbounds again.
func muxInboundEnabled(doc map[string]any) bool {
	ins := 0
	for _, raw := range asSlice(doc["inbounds"]) {
		in, _ := raw.(map[string]any)
		if in == nil {
			continue
		}
		if t, _ := in["type"].(string); t != "vless" {
			continue
		}
		ins++
		mux, _ := in["multiplex"].(map[string]any)
		if mux == nil {
			return false
		}
		if on, _ := mux["enabled"].(bool); !on {
			return false
		}
	}
	return ins > 0
}

// readMuxInbound loads the config and reports the box's multiplex
// capability, false when it cannot be determined.
func readMuxInbound(path string) bool {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return false
	}
	return muxInboundEnabled(doc)
}

func asSlice(v any) []any {
	s, _ := v.([]any)
	return s
}

// removeUserFromSingbox removes the user across all four inbound
// types. Returns whether the user was present in any inbound.
func removeUserFromSingbox(path, name string, validate func(string) error) (bool, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return false, err
	}
	found := false
	if removeVLESSUser(doc, name) {
		found = true
	}
	if removeHy2User(doc, name) {
		found = true
	}
	if removeNaiveUser(doc, name) {
		found = true
	}
	if removeWSUser(doc, name) {
		found = true
	}
	if removeSSUser(doc, name) {
		found = true
	}
	if removeAnyTLSUser(doc, name) {
		found = true
	}
	if removeTUICUser(doc, name) {
		found = true
	}
	if !found {
		return false, nil
	}
	return true, writeSingboxDoc(path, doc, validate)
}

// listUsers walks the VLESS inbound users[] (canonical source of
// truth — every user appears there) and returns one userMeta per
// recipient. The provisioned_at timestamp is not stored on the box,
// so we return 0.
func listUsers(path string) ([]userMeta, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return nil, err
	}
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return nil, nil
	}
	users, _ := in["users"].([]any)
	out := make([]userMeta, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		name, _ := u["name"].(string)
		if name != "" && nameRegex.MatchString(name) {
			out = append(out, userMeta{Name: name})
		}
	}
	return out, nil
}

// countUsers returns the number of recipient rows in the VLESS
// inbound (canonical user count).
func countUsers(path string) (int, error) {
	users, err := listUsers(path)
	if err != nil {
		return 0, err
	}
	return len(users), nil
}

// userExists reports whether `name` is already present in the
// VLESS inbound users[].
func userExists(path, name string) (bool, error) {
	users, err := listUsers(path)
	if err != nil {
		return false, err
	}
	for _, u := range users {
		if u.Name == name {
			return true, nil
		}
	}
	return false, nil
}

// ----------------------------------------------------------------
// Per-inbound appenders / removers.
// ----------------------------------------------------------------

func appendVLESSUser(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return fmt.Errorf("sing-box config missing inbound with tag=%q", tagVLESS)
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"uuid": c.VLESSUUID,
		"name": c.Name,
		"flow": "xtls-rprx-vision",
	})
	in["users"] = users
	// Append the Reality short_id.
	tlsBlock, _ := in["tls"].(map[string]any)
	if tlsBlock == nil {
		return errors.New("vless-in inbound has no tls block")
	}
	reality, _ := tlsBlock["reality"].(map[string]any)
	if reality == nil {
		return errors.New("vless-in inbound has no reality block")
	}
	sids, _ := reality["short_id"].([]any)
	sids = append(sids, c.RealityShortID)
	reality["short_id"] = sids
	return nil
}

func removeVLESSUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	// Index correspondence is the whole mechanism: appendVLESSUser adds
	// the user and its REALITY short_id in the same call, in the same
	// order, so users[i] owns short_id[i]. Removing by index preserves
	// that invariant.
	//
	// Truncating the list to the new user count — what this used to do —
	// does not: revoking r1 (index 0) from [r1, r2] left short_id [A],
	// i.e. it revoked r2's credential and kept the revoked r1's. The
	// still-live recipient's vless-reality route, the primary 443/tcp
	// transport, then silently stopped working because someone *else*
	// was revoked.
	removed := make([]int, 0, 1)
	for i, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			removed = append(removed, i)
			continue
		}
		out = append(out, raw)
	}
	if len(removed) == 0 {
		return false
	}
	in["users"] = out

	tlsBlock, _ := in["tls"].(map[string]any)
	if tlsBlock != nil {
		reality, _ := tlsBlock["reality"].(map[string]any)
		if reality != nil {
			sids, _ := reality["short_id"].([]any)
			if len(sids) == len(users) {
				// Aligned: drop exactly the revoked user's entries.
				// Highest index first so earlier indices stay valid.
				for i := len(removed) - 1; i >= 0; i-- {
					j := removed[i]
					sids = append(sids[:j], sids[j+1:]...)
				}
				reality["short_id"] = sids
			} else if len(sids) > len(out) {
				// Not aligned (hand-edited config, or a box that
				// predates the paired append). There is no way to tell
				// which entry belongs to whom, so fall back to the old
				// truncation rather than leaving a stale credential
				// accepted — but never grow the list.
				reality["short_id"] = sids[:len(out)]
			}
		}
	}
	return true
}

func appendHy2User(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagHy2)
	if in == nil {
		// Hy2 inbound is optional — UDP families may be disabled
		// per the toolbox profile.
		return nil
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"name":     c.Name,
		"password": c.Hy2Password,
	})
	in["users"] = users
	return nil
}

func removeHy2User(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagHy2)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	in["users"] = out
	return true
}

func appendNaiveUser(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagNaive)
	if in == nil {
		// Create the naive inbound on first use. Unlike vless/hy2 it
		// cannot ship empty: sing-box FATALs "missing users" when a
		// naive inbound has no users (protocol/naive/inbound.go), so it
		// only exists once it has one. The cert is the box's shared
		// data-plane leaf; the client pins it by SPKI SHA-256.
		in = map[string]any{
			"type":        "naive",
			"tag":         tagNaive,
			"listen":      "0.0.0.0",
			"listen_port": naiveListenPort,
			"users":       []any{},
			"tls": map[string]any{
				"enabled":          true,
				"certificate_path": tlsCertPath,
				"key_path":         tlsKeyPath,
			},
		}
		inbounds, _ := doc["inbounds"].([]any)
		doc["inbounds"] = append(inbounds, in)
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"username": c.Name,
		"password": c.NaivePassword,
	})
	in["users"] = users
	return nil
}

func removeNaiveUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagNaive)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["username"].(string); n == name {
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	if len(out) == 0 {
		// A naive inbound with an empty users[] FATALs on the next
		// sing-box start, so drop the whole inbound when its last user
		// leaves; appendNaiveUser re-creates it on the next add.
		inbounds, _ := doc["inbounds"].([]any)
		kept := make([]any, 0, len(inbounds))
		for _, raw := range inbounds {
			ib, _ := raw.(map[string]any)
			if t, _ := ib["tag"].(string); t == tagNaive {
				continue
			}
			kept = append(kept, raw)
		}
		doc["inbounds"] = kept
		return true
	}
	in["users"] = out
	return true
}

// appendTUICUser adds the recipient to the optional tuic-in inbound.
//
// Optional in the hy2 sense and never created here: a relay serves tuic
// only if it was provisioned with the inbound in its cloud-init
// sing-box config (toolbox profile enabled the family). A missing
// inbound is the normal case, not an error.
//
// TUIC rows carry BOTH a uuid and a password — sing-box's TUICUser has
// `uuid`, `password` and `name`, and the protocol authenticates on the
// pair. They are minted independently of the VLESS uuid so a leaked
// tuic pack does not also disclose the recipient's identity on the
// REALITY tier.
//
// Reports whether a row was appended.
func appendTUICUser(doc map[string]any, c userCreds) bool {
	in := findInboundByTag(doc, tagTUIC)
	if in == nil {
		return false
	}
	// Drift guard. The listen port is decided by relayports (publisher
	// module) and written by cloud-init; this binary only mirrors the
	// number. If the two ever disagree, the client outbound the
	// publisher renders would dial a port nothing is listening on, so
	// refuse the row rather than hand back creds for a dead route — the
	// publisher then fails closed exactly as it does for an old binary.
	if port, ok := numericPort(in["listen_port"]); ok && port != tuicListenPort {
		return false
	}
	users, _ := in["users"].([]any)
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == c.Name {
			return true // already present; idempotent
		}
	}
	in["users"] = append(users, map[string]any{
		"name":     c.Name,
		"uuid":     c.TUICUUID,
		"password": c.TUICPassword,
	})
	return true
}

// numericPort reads a listen_port out of a generic JSON decode, where a
// number arrives as float64 (and, from a hand-edited config, possibly as
// a string). Returns ok=false when the field is absent or unreadable, in
// which case callers must not treat it as a mismatch.
func numericPort(v any) (int, bool) {
	switch n := v.(type) {
	case float64:
		return int(n), true
	case int:
		return n, true
	case json.Number:
		i, err := n.Int64()
		if err != nil {
			return 0, false
		}
		return int(i), true
	}
	return 0, false
}

func removeTUICUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagTUIC)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	// Unlike naive, a tuic inbound with an empty users[] starts fine
	// (protocol/tuic/inbound.go has no "missing users" fatal), so the
	// inbound stays: dropping it would silently un-provision the family
	// for the relay when its last recipient is revoked.
	in["users"] = out
	return true
}

// tuicUserPresent reports whether the LIVE config really carries a tuic
// row for this recipient.
//
// This is the box's positive signal that the tuic tier exists here, and
// it is read back from the file rather than inferred from what this
// function believed it wrote. The publisher blanks the tuic creds when
// it is false and then fails closed on minting a tuic route, which is
// the only interlock that survives the release coupling: cloud-init and
// cmd/daal-relay-mgmt are pinned separately, so a fresh relay can boot
// with a tuic-in inbound in its config and an OLDER mgmt binary that
// has never heard of tuic. That binary answers /users/provision
// happily, adds no tuic row, and — without this — would hand back creds
// the publisher would mint into a route no one can dial.
func tuicUserPresent(path, name string) bool {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return false
	}
	in := findInboundByTag(doc, tagTUIC)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n != name {
			continue
		}
		uuid, _ := u["uuid"].(string)
		pw, _ := u["password"].(string)
		return uuid != "" && pw != ""
	}
	return false
}

// appendWSUser adds the recipient to the single shared ws-in inbound
// (VLESS-over-WS on the WS-TLS port). Per-user ws inbounds would collide
// on the one shared port, so every recipient rides one inbound and is
// told apart by UUID (exactly like vless-in); they also share one ws
// path, fixed by the first recipient (see addUserToSingbox). Idempotent.
func appendWSUser(doc map[string]any, c userCreds) error {
	if in := findInboundByTag(doc, tagWS); in != nil {
		users, _ := in["users"].([]any)
		for _, raw := range users {
			u, _ := raw.(map[string]any)
			if n, _ := u["name"].(string); n == c.Name {
				return nil // already present
			}
		}
		in["users"] = append(users, map[string]any{
			"uuid": c.VLESSUUID,
			"name": c.Name,
		})
		return nil
	}
	// First ws recipient: create the shared inbound. Mirror the shared
	// TLS SNI from vless-in.
	sni := ""
	if vl := findInboundByTag(doc, tagVLESS); vl != nil {
		if t, _ := vl["tls"].(map[string]any); t != nil {
			if s, _ := t["server_name"].(string); s != "" {
				sni = s
			}
		}
	}
	inbound := map[string]any{
		"type":        "vless",
		"tag":         tagWS,
		"listen":      "0.0.0.0",
		"listen_port": wsListenPort,
		"users": []any{
			map[string]any{
				"uuid": c.VLESSUUID,
				"name": c.Name,
			},
		},
		"multiplex": muxInbound(),
		"transport": map[string]any{
			"type": "ws",
			"path": c.WSPath,
		},
		"tls": map[string]any{
			"enabled":          true,
			"server_name":      sni,
			"certificate_path": tlsCertPath,
			"key_path":         tlsKeyPath,
		},
	}
	inbounds, _ := doc["inbounds"].([]any)
	doc["inbounds"] = append(inbounds, inbound)
	return nil
}

// removeWSUser removes the recipient from the shared ws-in inbound,
// dropping the inbound entirely when the last user leaves (sing-box
// faults on a user-less inbound).
func removeWSUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagWS)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	removed := false
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			removed = true
			continue
		}
		out = append(out, raw)
	}
	if !removed {
		return false
	}
	if len(out) == 0 {
		inbounds, _ := doc["inbounds"].([]any)
		kept := make([]any, 0, len(inbounds))
		for _, raw := range inbounds {
			i, _ := raw.(map[string]any)
			if t, _ := i["tag"].(string); t == tagWS {
				continue
			}
			kept = append(kept, raw)
		}
		doc["inbounds"] = kept
		return true
	}
	in["users"] = out
	return true
}

// wsInboundPath returns the shared ws-in inbound's ws path, or "" when
// no ws inbound exists yet.
func wsInboundPath(doc map[string]any) string {
	in := findInboundByTag(doc, tagWS)
	if in == nil {
		return ""
	}
	t, _ := in["transport"].(map[string]any)
	if t == nil {
		return ""
	}
	p, _ := t["path"].(string)
	return p
}

// ----------------------------------------------------------------
// Helpers.
// ----------------------------------------------------------------

func findInboundByTag(doc map[string]any, tag string) map[string]any {
	inbounds, _ := doc["inbounds"].([]any)
	for _, raw := range inbounds {
		in, _ := raw.(map[string]any)
		if t, _ := in["tag"].(string); t == tag {
			return in
		}
	}
	return nil
}

func loadSingboxDoc(path string) (map[string]any, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, err
		}
		// Bootstrap: empty-users scaffold matching the v2 cloud-init template.
		// Keep the reality.handshake block here even though it is empty:
		// surgicalSetSNI has to have somewhere to put the dest, and a
		// REALITY inbound whose advertised name and handshake dest are set
		// independently is the exact mismatch the design forbids.
		body = []byte(`{
  "log": {"level": "info"},
  "inbounds": [
    {"type":"vless","tag":"` + tagVLESS + `","listen":"0.0.0.0","listen_port":443,
     "users":[],
     "multiplex":{"enabled":true,"padding":true},
     "tls":{"enabled":true,"server_name":"","reality":{"enabled":true,"private_key":"","short_id":[],
            "handshake":{"server":"","server_port":443}}}},
    {"type":"hysteria2","tag":"` + tagHy2 + `","listen":"0.0.0.0","listen_port":443,"users":[],
     "tls":{"enabled":true,"certificate_path":"` + tlsCertPath + `","key_path":"` + tlsKeyPath + `"}}
  ],
  "outbounds":[{"type":"direct"}]
}`)
	}
	var doc map[string]any
	if err := json.Unmarshal(body, &doc); err != nil {
		return nil, fmt.Errorf("sing-box config not JSON: %w", err)
	}
	return doc, nil
}

func writeSingboxDoc(path string, doc map[string]any, validate func(string) error) error {
	body, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return err
	}
	if validate != nil {
		if err := validate(tmp); err != nil {
			_ = os.Remove(tmp)
			return err
		}
	}
	return os.Rename(tmp, path)
}
