// FRP-14: surgical sing-box rewriter for the users[] table.
//
// The four supported transports each have a dedicated inbound
// (matched by `tag`):
//
//	tag = "vless-in"     → VLESS-Reality   (users[] + reality.short_id[])
//	tag = "hy2-in"       → Hysteria2       (users[])
//	tag = "naive-in"     → Naive           (users[])
//	tag = "ws-r<id>"     → per-user WS-TLS (entire inbound block per user)
//
// On `addUserToSingbox`, the rewriter appends the new user row to
// the first three inbounds (creating the inbound if absent — this
// covers the empty-users[] first-boot case) and adds a new ws-r<id>
// inbound. On `removeUserFromSingbox` the inverse runs, idempotently.
//
// We work over a generic map[string]any decode of the config so
// non-Daal sections (route tables, DNS, log levels) survive
// byte-equal across rewrites except where touched.
package main

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const (
	tagVLESS = "vless-in"
	tagHy2   = "hy2-in"
	tagNaive = "naive-in"
	tagWS    = "ws-in" // single shared VLESS-over-WS inbound (all recipients)

	// Data-plane self-signed TLS cert for the hy2/naive/ws inbounds
	// (TLS families that, unlike REALITY, need a cert). Generated by
	// cloud-init at first boot; equals main.go newServer's hardcoded
	// s.tlsCertPath. Keep the two in sync.
	tlsCertPath = "/etc/daal/tls-cert.pem"
	tlsKeyPath  = "/etc/daal/tls-key.pem"

	// wsListenPort / naiveListenPort are the WS-TLS and Naive inbound
	// ports. Local copies of publisher/deploy/relayports.For(...).Port
	// ("websocket-tls"=8445, "naive"=8444): relay-mgmt is a separate
	// module and importing the publisher package here would pull the
	// whole publisher dependency tree into the on-box binary, so we
	// mirror the single values with these pointers.
	wsListenPort    = 8445
	naiveListenPort = 8444
)

// addUserToSingbox loads /etc/sing-box/config.json, appends the
// user across all four inbound types, and atomically writes it back.
// It returns the effective ws path baked into the user's WS route:
// the first recipient's minted path becomes the shared ws-in path, and
// every later recipient reuses it (a single port can't host per-user ws
// inbounds), so the caller must persist the returned path in the creds
// it hands back to the client.
func addUserToSingbox(path string, c userCreds) (string, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return "", err
	}
	// Reuse the shared ws-in path if the inbound already exists so all
	// recipients land on one inbound with one consistent path.
	if existing := wsInboundPath(doc); existing != "" {
		c.WSPath = existing
	}
	if err := appendVLESSUser(doc, c); err != nil {
		return "", err
	}
	if err := appendHy2User(doc, c); err != nil {
		return "", err
	}
	if err := appendNaiveUser(doc, c); err != nil {
		return "", err
	}
	if err := appendWSUser(doc, c); err != nil {
		return "", err
	}
	if err := writeSingboxDoc(path, doc); err != nil {
		return "", err
	}
	return c.WSPath, nil
}

// removeUserFromSingbox removes the user across all four inbound
// types. Returns whether the user was present in any inbound.
func removeUserFromSingbox(path, name string) (bool, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return false, err
	}
	found := false
	if removeVLESSUser(doc, name) {
		found = true
	}
	if removeHy2User(doc, name) {
		found = true
	}
	if removeNaiveUser(doc, name) {
		found = true
	}
	if removeWSUser(doc, name) {
		found = true
	}
	if !found {
		return false, nil
	}
	return true, writeSingboxDoc(path, doc)
}

// listUsers walks the VLESS inbound users[] (canonical source of
// truth — every user appears there) and returns one userMeta per
// recipient. The provisioned_at timestamp is not stored on the box,
// so we return 0.
func listUsers(path string) ([]userMeta, error) {
	doc, err := loadSingboxDoc(path)
	if err != nil {
		return nil, err
	}
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return nil, nil
	}
	users, _ := in["users"].([]any)
	out := make([]userMeta, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		name, _ := u["name"].(string)
		if name != "" && nameRegex.MatchString(name) {
			out = append(out, userMeta{Name: name})
		}
	}
	return out, nil
}

// countUsers returns the number of recipient rows in the VLESS
// inbound (canonical user count).
func countUsers(path string) (int, error) {
	users, err := listUsers(path)
	if err != nil {
		return 0, err
	}
	return len(users), nil
}

// userExists reports whether `name` is already present in the
// VLESS inbound users[].
func userExists(path, name string) (bool, error) {
	users, err := listUsers(path)
	if err != nil {
		return false, err
	}
	for _, u := range users {
		if u.Name == name {
			return true, nil
		}
	}
	return false, nil
}

// ----------------------------------------------------------------
// Per-inbound appenders / removers.
// ----------------------------------------------------------------

func appendVLESSUser(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return fmt.Errorf("sing-box config missing inbound with tag=%q", tagVLESS)
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"uuid": c.VLESSUUID,
		"name": c.Name,
		"flow": "xtls-rprx-vision",
	})
	in["users"] = users
	// Append the Reality short_id.
	tlsBlock, _ := in["tls"].(map[string]any)
	if tlsBlock == nil {
		return errors.New("vless-in inbound has no tls block")
	}
	reality, _ := tlsBlock["reality"].(map[string]any)
	if reality == nil {
		return errors.New("vless-in inbound has no reality block")
	}
	sids, _ := reality["short_id"].([]any)
	sids = append(sids, c.RealityShortID)
	reality["short_id"] = sids
	return nil
}

func removeVLESSUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagVLESS)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	removedShortID := ""
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			// We don't have a stable name→short_id index on the
			// box; instead, we drop the same-index entry from the
			// short_id list below. Stash to log here.
			_ = removedShortID
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	in["users"] = out
	// Truncate or rebuild the short_id list to the new user count.
	tlsBlock, _ := in["tls"].(map[string]any)
	if tlsBlock != nil {
		reality, _ := tlsBlock["reality"].(map[string]any)
		if reality != nil {
			sids, _ := reality["short_id"].([]any)
			if len(sids) > len(out) {
				reality["short_id"] = sids[:len(out)]
			}
		}
	}
	return true
}

func appendHy2User(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagHy2)
	if in == nil {
		// Hy2 inbound is optional — UDP families may be disabled
		// per the toolbox profile.
		return nil
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"name":     c.Name,
		"password": c.Hy2Password,
	})
	in["users"] = users
	return nil
}

func removeHy2User(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagHy2)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	in["users"] = out
	return true
}

func appendNaiveUser(doc map[string]any, c userCreds) error {
	in := findInboundByTag(doc, tagNaive)
	if in == nil {
		// Create the naive inbound on first use. Unlike vless/hy2 it
		// cannot ship empty: sing-box FATALs "missing users" when a
		// naive inbound has no users (protocol/naive/inbound.go), so it
		// only exists once it has one. The cert is the box's shared
		// data-plane leaf; the client pins it by SPKI SHA-256.
		in = map[string]any{
			"type":        "naive",
			"tag":         tagNaive,
			"listen":      "0.0.0.0",
			"listen_port": naiveListenPort,
			"users":       []any{},
			"tls": map[string]any{
				"enabled":          true,
				"certificate_path": tlsCertPath,
				"key_path":         tlsKeyPath,
			},
		}
		inbounds, _ := doc["inbounds"].([]any)
		doc["inbounds"] = append(inbounds, in)
	}
	users, _ := in["users"].([]any)
	users = append(users, map[string]any{
		"username": c.Name,
		"password": c.NaivePassword,
	})
	in["users"] = users
	return nil
}

func removeNaiveUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagNaive)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["username"].(string); n == name {
			continue
		}
		out = append(out, raw)
	}
	if len(out) == len(users) {
		return false
	}
	if len(out) == 0 {
		// A naive inbound with an empty users[] FATALs on the next
		// sing-box start, so drop the whole inbound when its last user
		// leaves; appendNaiveUser re-creates it on the next add.
		inbounds, _ := doc["inbounds"].([]any)
		kept := make([]any, 0, len(inbounds))
		for _, raw := range inbounds {
			ib, _ := raw.(map[string]any)
			if t, _ := ib["tag"].(string); t == tagNaive {
				continue
			}
			kept = append(kept, raw)
		}
		doc["inbounds"] = kept
		return true
	}
	in["users"] = out
	return true
}

// appendWSUser adds the recipient to the single shared ws-in inbound
// (VLESS-over-WS on the WS-TLS port). Per-user ws inbounds would collide
// on the one shared port, so every recipient rides one inbound and is
// told apart by UUID (exactly like vless-in); they also share one ws
// path, fixed by the first recipient (see addUserToSingbox). Idempotent.
func appendWSUser(doc map[string]any, c userCreds) error {
	if in := findInboundByTag(doc, tagWS); in != nil {
		users, _ := in["users"].([]any)
		for _, raw := range users {
			u, _ := raw.(map[string]any)
			if n, _ := u["name"].(string); n == c.Name {
				return nil // already present
			}
		}
		in["users"] = append(users, map[string]any{
			"uuid": c.VLESSUUID,
			"name": c.Name,
		})
		return nil
	}
	// First ws recipient: create the shared inbound. Mirror the shared
	// TLS SNI from vless-in.
	sni := ""
	if vl := findInboundByTag(doc, tagVLESS); vl != nil {
		if t, _ := vl["tls"].(map[string]any); t != nil {
			if s, _ := t["server_name"].(string); s != "" {
				sni = s
			}
		}
	}
	inbound := map[string]any{
		"type":        "vless",
		"tag":         tagWS,
		"listen":      "0.0.0.0",
		"listen_port": wsListenPort,
		"users": []any{
			map[string]any{
				"uuid": c.VLESSUUID,
				"name": c.Name,
			},
		},
		"transport": map[string]any{
			"type": "ws",
			"path": c.WSPath,
		},
		"tls": map[string]any{
			"enabled":          true,
			"server_name":      sni,
			"certificate_path": tlsCertPath,
			"key_path":         tlsKeyPath,
		},
	}
	inbounds, _ := doc["inbounds"].([]any)
	doc["inbounds"] = append(inbounds, inbound)
	return nil
}

// removeWSUser removes the recipient from the shared ws-in inbound,
// dropping the inbound entirely when the last user leaves (sing-box
// faults on a user-less inbound).
func removeWSUser(doc map[string]any, name string) bool {
	in := findInboundByTag(doc, tagWS)
	if in == nil {
		return false
	}
	users, _ := in["users"].([]any)
	out := make([]any, 0, len(users))
	removed := false
	for _, raw := range users {
		u, _ := raw.(map[string]any)
		if n, _ := u["name"].(string); n == name {
			removed = true
			continue
		}
		out = append(out, raw)
	}
	if !removed {
		return false
	}
	if len(out) == 0 {
		inbounds, _ := doc["inbounds"].([]any)
		kept := make([]any, 0, len(inbounds))
		for _, raw := range inbounds {
			i, _ := raw.(map[string]any)
			if t, _ := i["tag"].(string); t == tagWS {
				continue
			}
			kept = append(kept, raw)
		}
		doc["inbounds"] = kept
		return true
	}
	in["users"] = out
	return true
}

// wsInboundPath returns the shared ws-in inbound's ws path, or "" when
// no ws inbound exists yet.
func wsInboundPath(doc map[string]any) string {
	in := findInboundByTag(doc, tagWS)
	if in == nil {
		return ""
	}
	t, _ := in["transport"].(map[string]any)
	if t == nil {
		return ""
	}
	p, _ := t["path"].(string)
	return p
}

// ----------------------------------------------------------------
// Helpers.
// ----------------------------------------------------------------

func findInboundByTag(doc map[string]any, tag string) map[string]any {
	inbounds, _ := doc["inbounds"].([]any)
	for _, raw := range inbounds {
		in, _ := raw.(map[string]any)
		if t, _ := in["tag"].(string); t == tag {
			return in
		}
	}
	return nil
}

func loadSingboxDoc(path string) (map[string]any, error) {
	body, err := os.ReadFile(path)
	if err != nil {
		if !os.IsNotExist(err) {
			return nil, err
		}
		// Bootstrap: empty-users scaffold matching the v2 cloud-init template.
		body = []byte(`{
  "log": {"level": "info"},
  "inbounds": [
    {"type":"vless","tag":"` + tagVLESS + `","listen":"0.0.0.0","listen_port":443,
     "users":[],
     "tls":{"enabled":true,"server_name":"","reality":{"enabled":true,"private_key":"","short_id":[]}}},
    {"type":"hysteria2","tag":"` + tagHy2 + `","listen":"0.0.0.0","listen_port":443,"users":[],
     "tls":{"enabled":true,"certificate_path":"` + tlsCertPath + `","key_path":"` + tlsKeyPath + `"}}
  ],
  "outbounds":[{"type":"direct"}]
}`)
	}
	var doc map[string]any
	if err := json.Unmarshal(body, &doc); err != nil {
		return nil, fmt.Errorf("sing-box config not JSON: %w", err)
	}
	return doc, nil
}

func writeSingboxDoc(path string, doc map[string]any) error {
	body, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
