// Command genregistry reads every specs/modifiers/<kind>.md file
// (excluding _template.md and README.md) and emits a Go file
// containing a literal map keyed by modifier kind. The output goes
// to publisher/deploy/modifiers/registry_gen.go and is committed.
//
// Usage:
//
//	go run daal/publisher/deploy/modifiers/cmd/genregistry \
//	    --specs ./specs/modifiers --out ./publisher/deploy/modifiers/registry_gen.go
//
// The generator refuses to write the output file when any input
// record fails Meta.validate() (locked invariant 43). It also fails
// the run if any input record carries pass_record.status=PASS unless
// --allow-pass is set explicitly — locked invariant 37 (zero PASS
// records ship at FRP-12).
package main

import (
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"daal/publisher/deploy/modifiers"
)

func main() {
	specsDir := flag.String("specs", "specs/modifiers", "directory containing per-modifier markdown")
	outFile := flag.String("out", "publisher/deploy/modifiers/registry_gen.go", "output file path")
	allowPass := flag.Bool("allow-pass", false, "permit PASS-status records (FRP-12 ships with this DISABLED)")
	flag.Parse()

	entries, err := os.ReadDir(*specsDir)
	if err != nil {
		log.Fatalf("read specs dir %s: %v", *specsDir, err)
	}

	var metas []modifiers.Meta
	for _, ent := range entries {
		if ent.IsDir() {
			continue
		}
		name := ent.Name()
		if !strings.HasSuffix(name, ".md") {
			continue
		}
		if name == "_template.md" || name == "README.md" {
			continue
		}
		full := filepath.Join(*specsDir, name)
		f, err := os.Open(full)
		if err != nil {
			log.Fatalf("open %s: %v", full, err)
		}
		m, err := modifiers.Parse(f)
		f.Close()
		if err != nil {
			log.Fatalf("parse %s: %v", full, err)
		}
		if err := m.ValidateExported(); err != nil {
			log.Fatalf("validate %s: %v", full, err)
		}
		if m.Status == modifiers.StatusPass && !*allowPass {
			log.Fatalf("%s carries pass_record.status=PASS but --allow-pass is not set; FRP-12 ships with zero PASS records (locked invariant 37)", full)
		}
		metas = append(metas, m)
	}

	sort.Slice(metas, func(i, j int) bool { return metas[i].Kind < metas[j].Kind })

	src, err := render(metas)
	if err != nil {
		log.Fatalf("render: %v", err)
	}
	formatted, err := format.Source(src)
	if err != nil {
		log.Fatalf("gofmt: %v\n--- source ---\n%s", err, src)
	}
	if err := os.WriteFile(*outFile, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", *outFile, err)
	}
	fmt.Printf("genregistry: wrote %d records to %s\n", len(metas), *outFile)
}

const tplText = `// Code generated by daal/publisher/deploy/modifiers/cmd/genregistry; DO NOT EDIT.
// Source: specs/modifiers/*.md
//
// FRP-12 locked invariant 37: zero pass_record.status=PASS records
// ship at FRP-12. The generator refuses PASS records unless invoked
// with --allow-pass, which the FRP-12 release MUST NOT use.

package modifiers

func registryFromGen() map[string]Meta {
	return map[string]Meta{
{{- range .Metas }}
		{{ printf "%q" .Kind }}: {
			Kind:       {{ printf "%q" .Kind }},
			Status:     Status({{ printf "%q" .Status }}),
			MinPhase:   Phase({{ printf "%q" .MinPhase }}),
			SingboxRef: {{ printf "%q" .SingboxRef }},
			Reviewer:   {{ printf "%q" .Reviewer }},
			Date:       {{ printf "%q" .Date }},
			Platforms: []Platform{
{{- range .Platforms }}
				Platform({{ printf "%q" . }}),
{{- end }}
			},
		},
{{- end }}
	}
}
`

func render(metas []modifiers.Meta) ([]byte, error) {
	tpl, err := template.New("registry").Parse(tplText)
	if err != nil {
		return nil, err
	}
	data := struct {
		Metas []modifiers.Meta
	}{Metas: metas}
	var buf strings.Builder
	if err := tpl.Execute(&buf, data); err != nil {
		return nil, err
	}
	return []byte(buf.String()), nil
}
