package relaypackvalidate

import (
	"bytes"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"daal/bundle-go/bundle"
)

// FRP-1 corpus replay: parse each .sbp under
// specs/test-vectors/relaypack/, run Validate against each phase
// recorded in <name>.expected.json, and assert the outcome matches.
//
// The corpus is generated by publisher/cmd/relaypack-fixtures/main.go.
// Regenerate after schema edits with `cd publisher && go run ./cmd/relaypack-fixtures`.
func TestCorpusReplay(t *testing.T) {
	dir, err := corpusDir()
	if err != nil {
		t.Skipf("locate corpus: %v (run `cd publisher && go run ./cmd/relaypack-fixtures` first)", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read dir %s: %v", dir, err)
	}
	count := 0
	for _, ent := range entries {
		name := ent.Name()
		if !hasSuffix(name, ".expected.json") {
			continue
		}
		count++
		base := name[:len(name)-len(".expected.json")]
		t.Run(base, func(t *testing.T) {
			expected := loadExpected(t, filepath.Join(dir, name))
			sbpPath := filepath.Join(dir, base+".sbp")
			data, err := os.ReadFile(sbpPath)
			if err != nil {
				t.Fatalf("read sbp: %v", err)
			}
			b, err := bundle.ParseSBP(bytes.NewReader(data), int64(len(data)))
			if err != nil {
				t.Fatalf("parse sbp: %v", err)
			}
			for _, want := range expected.Outcomes {
				want := want
				t.Run(want.Phase, func(t *testing.T) {
					opts := ValidateOpts{Phase: Phase(want.Phase)}
					if want.Phase == "PostV2" {
						opts.AllowedModifierKinds = map[string]bool{
							"client_desync": true,
							"tls_fragment":  true,
						}
					}
					rep, err := Validate(b, opts)
					gotPass := err == nil
					if gotPass != want.Pass {
						t.Fatalf("pass=%v want=%v (err=%v)", gotPass, want.Pass, err)
					}
					if !want.Pass {
						var ve *ValidationError
						if !errors.As(err, &ve) {
							t.Fatalf("expected *ValidationError, got %T", err)
						}
						if string(ve.Code) != want.ErrCode {
							t.Fatalf("error_code=%s want=%s", ve.Code, want.ErrCode)
						}
					}
					gotWarn := make([]string, 0, len(rep.Warnings))
					for _, w := range rep.Warnings {
						gotWarn = append(gotWarn, string(w.Code))
					}
					sort.Strings(gotWarn)
					sortedWant := append([]string(nil), want.Warnings...)
					sort.Strings(sortedWant)
					if !equalStringSlices(gotWarn, sortedWant) {
						t.Fatalf("warnings=%v want=%v", gotWarn, sortedWant)
					}
				})
			}
		})
	}
	if count == 0 {
		t.Fatalf("no .expected.json files found in %s", dir)
	}
	// FRP-1 seeded 6 vectors; FRP-2 expanded the corpus to 16.
	if count != 16 {
		t.Errorf("FRP-2 corpus must have 16 vectors; got %d", count)
	}
}

type expectedOutcome struct {
	Phase    string   `json:"phase"`
	Pass     bool     `json:"pass"`
	ErrCode  string   `json:"error_code,omitempty"`
	Warnings []string `json:"warnings,omitempty"`
}

type expectedFile struct {
	Vector   string            `json:"vector"`
	Purpose  string            `json:"purpose"`
	Outcomes []expectedOutcome `json:"outcomes"`
}

func loadExpected(t *testing.T, path string) expectedFile {
	t.Helper()
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read expected: %v", err)
	}
	var ef expectedFile
	if err := json.Unmarshal(body, &ef); err != nil {
		t.Fatalf("parse expected: %v", err)
	}
	return ef
}

// corpusDir locates the corpus relative to the test binary's
// working directory (the package directory).
func corpusDir() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	// bundle/go/relaypackvalidate -> ../../../specs/test-vectors/relaypack
	candidate := filepath.Join(wd, "..", "..", "..", "specs", "test-vectors", "relaypack")
	st, err := os.Stat(candidate)
	if err != nil {
		return "", err
	}
	if !st.IsDir() {
		return "", os.ErrNotExist
	}
	return candidate, nil
}

func hasSuffix(s, suffix string) bool {
	return len(s) >= len(suffix) && s[len(s)-len(suffix):] == suffix
}

func equalStringSlices(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
