// Code generated by daal/publisher/deploy/modifiers/cmd/genregistry; DO NOT EDIT.
// Source: specs/modifiers/*.md
//
// FRP-12 locked invariant 37: zero pass_record.status=PASS records
// ship at FRP-12. The generator refuses PASS records unless invoked
// with --allow-pass, which the FRP-12 release MUST NOT use.

package modifiers

func registryFromGen() map[string]Meta {
	return map[string]Meta{
		"client_desync": {
			Kind:       "client_desync",
			Status:     Status("PENDING"),
			MinPhase:   PhasePostV2,
			SingboxRef: "n/a (raw-socket modifier; below sing-box)",
			Reviewer:   "",
			Date:       "",
			Platforms: []Platform{
				Platform("linux-desktop"),
			},
		},
		"tls_fragment": {
			Kind:       "tls_fragment",
			Status:     Status("PENDING"),
			MinPhase:   PhasePostV2,
			SingboxRef: "TBD — finalised at censor-lab review.",
			Reviewer:   "",
			Date:       "",
			Platforms:  []Platform{},
		},
	}
}
