// Package cloudinit renders the supplement §9.3 cloud-init YAML
// against ProvisionOpts-derived inputs. Output is deterministic:
// same RenderInput → byte-identical YAML.
//
// The template is loaded from template.yaml.tmpl (Go text/template).
// The verifier shim is loaded from shim.sh.tmpl and indented into
// the YAML at render time.
//
// # Floating IPs: why nothing here configures one
//
// A Hetzner floating IP is ROUTED to the server at the provider's
// network layer and never ANSWERED by the guest OS until the address is
// configured on an interface (measured on real hardware 2026-08-17: the
// API showed the address attached with both ownership labels while a TLS
// probe to it timed out). Something has to do that step, and the
// candidates were cloud-init or a mgmt endpoint. It is the mgmt
// endpoint, deliberately. The four cases:
//
//  1. RELAY BORN WITHOUT A FLOATING IP — every relay today. Provision
//     creates the server and attaches no floating IP; rec.PublicIP is
//     the server's own primary address, which DHCP configures. There is
//     nothing for cloud-init to write. HANDLED (by having nothing to do).
//
//  2. RELAY GAINS ONE LATER (the L3 rung) — `daal-deploy floating-ip
//     assign` attaches the address and then calls POST /bind-address on
//     the box, between the provider attach and the reachability probe.
//     HANDLED. Cloud-init could not have helped here even in principle:
//     the address does not exist when the template is rendered, and it
//     changes on every subsequent swap, so anything baked in at birth is
//     stale after the first rotation.
//
//  3. RELAY REBOOTS HOLDING A FLOATING IP — the bind must survive. That
//     is the box's job and part of the pinned contract (/bind-address
//     persists; the response's `persisted` field reports whether it did,
//     and the publisher warns loudly when it says false). Cloud-init
//     runs once, at first boot, so it cannot own a fact that changes
//     later — and two writers of one interface config is the shape this
//     tree has already paid for twice.
//
//  4. RELAY REBUILT BY REPROVISION WHILE ITS RECORD NAMES A FLOATING IP
//     — NOT HANDLED, and stated rather than hidden. Reprovision deletes
//     the server (the provider detaches the address as a side effect)
//     and Provision builds a new one with a new primary address; the
//     record keeps its floating_ip_id while nothing is attached to it.
//     The operator's route back is to run `floating-ip assign` again
//     against the rebuilt relay, which reserves/attaches and binds. A
//     reprovision that re-attaches and re-binds automatically is its own
//     piece of work.
//
// So: ONE writer of the guest's address configuration, and it is the box
// endpoint the publisher can call at any time — not a template rendered
// before the address exists.
package cloudinit

import (
	"bytes"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
)

//go:embed template.yaml.tmpl
var templateBody string

//go:embed v2.yaml.tmpl
var templateBodyV2 string

//go:embed shim.sh.tmpl
var shimBody string

// RenderInput is the typed input to Render. Every field is required;
// callers (the Hetzner adapter at FRP-4a, the wizard at FRP-5) build
// this from ProvisionOpts + a sing-box config emitted by the
// toolbox-profile renderer.
type RenderInput struct {
	// EphemeralSSHPublicKey is the OpenSSH-formatted single-line
	// public key the box accepts during the 60 s provisioning window.
	EphemeralSSHPublicKey string

	// ProvisioningClientIP is the Helper's outbound IP. ufw rules
	// for ports 22 + 9876 are bound to this IP only.
	ProvisioningClientIP string

	// HealthToken is a 32-byte random token the Helper uses ONCE to
	// confirm sing-box is up. Generated by the caller per provision.
	HealthToken string

	// SingBoxConfigJSON is the rendered sing-box config (from the
	// toolbox profile + ProvisionOpts). Embedded verbatim into
	// /etc/sing-box/config.json on the box.
	SingBoxConfigJSON string

	// FRP-8 §11.7 cdn_fronted optional fields. All of these are
	// empty for plain direct_vps deployments; non-empty only when
	// the FRP elected a CDN front. They install the
	// Cloudflare-issued Origin CA cert + AOP client cert onto the
	// origin so the origin can present them back to Cloudflare's
	// edge under Authenticated Origin Pulls.
	//
	// The cert / key bytes are read from the Helper's local files
	// at render time (paths are tracked in V005's cdn_fronts
	// table); the bytes themselves embed verbatim here.

	// OriginCACertPEM is the Cloudflare Origin CA cert (public)
	// bundled into /etc/daal/cdn/origin_ca.pem. Empty for
	// non-CDN deployments.
	OriginCACertPEM string
	// OriginCAPrivPEM is the Origin CA private key bundled into
	// /etc/daal/cdn/origin_ca.key (mode 0600). Empty for non-CDN.
	OriginCAPrivPEM string
	// AOPClientCertPEM is the Cloudflare-signed client cert the
	// origin presents back under AOP, bundled into
	// /etc/daal/cdn/aop_client.pem (mode 0600). Empty for
	// non-CDN.
	AOPClientCertPEM string
}

// templateData is what reaches the text/template engine. Built from
// RenderInput + the package-level pinned-artefact manifest +
// release-pubkey constants + verifier shim body.
type templateData struct {
	EphemeralSSHPublicKey  string
	ProvisioningClientIP   string
	HealthToken            string
	SingBoxConfigJSON      string
	PinnedArtifactManifest string
	DaalReleasePubKey      string
	VerifierShim           string

	// FRP-8 cdn_fronted fields. CDN flag drives the conditional
	// write_files block in the template.
	CDNEnabled       bool
	OriginCACertPEM  string
	OriginCAPrivPEM  string
	AOPClientCertPEM string
}

// Render produces the rendered cloud-init YAML for the given input.
// Pure function: same input → byte-identical output.
func Render(in RenderInput) ([]byte, error) {
	if err := validate(in); err != nil {
		return nil, err
	}
	manifest, err := canonicalManifestJSON(V15Artifacts)
	if err != nil {
		return nil, err
	}
	cdnEnabled := in.OriginCACertPEM != "" || in.OriginCAPrivPEM != "" || in.AOPClientCertPEM != ""
	if cdnEnabled {
		// All three or none — half-state means the wizard built a
		// torn cert bundle.
		if in.OriginCACertPEM == "" || in.OriginCAPrivPEM == "" || in.AOPClientCertPEM == "" {
			return nil, fmt.Errorf("cdn_fronted: OriginCACertPEM + OriginCAPrivPEM + AOPClientCertPEM must be supplied together")
		}
	}
	td := templateData{
		EphemeralSSHPublicKey:  in.EphemeralSSHPublicKey,
		ProvisioningClientIP:   in.ProvisioningClientIP,
		HealthToken:            in.HealthToken,
		SingBoxConfigJSON:      in.SingBoxConfigJSON,
		PinnedArtifactManifest: manifest,
		DaalReleasePubKey:      DaalReleasePubKeyPEM,
		VerifierShim:           shimBody,
		CDNEnabled:             cdnEnabled,
		OriginCACertPEM:        in.OriginCACertPEM,
		OriginCAPrivPEM:        in.OriginCAPrivPEM,
		AOPClientCertPEM:       in.AOPClientCertPEM,
	}
	tmpl, err := template.New("cloudinit").Funcs(template.FuncMap{
		"indent": indent,
	}).Parse(templateBody)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, td); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}

// VerifierShimSource returns the embedded verifier shim bytes
// verbatim (no template substitution). Tests pin the SHA-256 of
// these bytes; FRP-7 / FRP-8 amendments must keep this stable.
func VerifierShimSource() []byte {
	return []byte(shimBody)
}

// VerifierShimLineCount returns the number of lines in shim.sh.tmpl.
// Phase doc invariant: the shim is meant to be ~50 lines (≤60 in
// practice). Test pins this.
func VerifierShimLineCount() int {
	return strings.Count(shimBody, "\n")
}

func validate(in RenderInput) error {
	if in.EphemeralSSHPublicKey == "" {
		return fmt.Errorf("RenderInput.EphemeralSSHPublicKey required")
	}
	if in.ProvisioningClientIP == "" {
		return fmt.Errorf("RenderInput.ProvisioningClientIP required")
	}
	if in.HealthToken == "" {
		return fmt.Errorf("RenderInput.HealthToken required")
	}
	if in.SingBoxConfigJSON == "" {
		return fmt.Errorf("RenderInput.SingBoxConfigJSON required")
	}
	return checkRealityCoverSNI(in.SingBoxConfigJSON)
}

// checkRealityCoverSNI refuses to render cloud-init for a box whose
// REALITY inbound advertises one name and falls back to another.
//
// This is a choke point, and that is the point: every provider adapter
// funnels its sing-box config through Render/RenderV2, so enforcing the
// invariant here makes the mismatch unshippable regardless of which
// adapter, profile or future template produced the config.
//
// Why it matters. tls.server_name is what the client puts in its
// ClientHello and what a censor reads. reality.handshake.server is the
// site this box actually completes a TLS handshake against when it
// cannot authenticate the client — i.e. when an active prober connects.
// If they differ, the prober asks for name A and is handed site B's
// certificate: a free, deterministic proxy detection, and precisely the
// failure REALITY exists to avoid. Both fields were the same hard-coded
// constant until Wave 2, so nothing enforced their agreement; now that
// the value is per-relay and rotatable, something must.
//
// Configs with no REALITY inbound (the Stark/Vultr placeholders, plain
// TLS profiles) pass untouched.
func checkRealityCoverSNI(configJSON string) error {
	var doc struct {
		Inbounds []struct {
			Tag string `json:"tag"`
			TLS *struct {
				ServerName string `json:"server_name"`
				Reality    *struct {
					Enabled   bool `json:"enabled"`
					Handshake *struct {
						Server string `json:"server"`
					} `json:"handshake"`
				} `json:"reality"`
			} `json:"tls"`
		} `json:"inbounds"`
	}
	if err := json.Unmarshal([]byte(configJSON), &doc); err != nil {
		return fmt.Errorf("RenderInput.SingBoxConfigJSON is not valid JSON: %w", err)
	}
	for i, inb := range doc.Inbounds {
		if inb.TLS == nil || inb.TLS.Reality == nil || !inb.TLS.Reality.Enabled {
			continue
		}
		name := inb.Tag
		if name == "" {
			name = fmt.Sprintf("inbounds[%d]", i)
		}
		if inb.TLS.ServerName == "" {
			return fmt.Errorf("cover sni: inbound %s has a REALITY block with an empty tls.server_name", name)
		}
		if inb.TLS.Reality.Handshake == nil || inb.TLS.Reality.Handshake.Server == "" {
			return fmt.Errorf("cover sni: inbound %s has no reality.handshake.server", name)
		}
		if inb.TLS.Reality.Handshake.Server != inb.TLS.ServerName {
			return fmt.Errorf(
				"cover sni: inbound %s advertises %q but falls back to %q — an active prober would get the wrong site's certificate",
				name, inb.TLS.ServerName, inb.TLS.Reality.Handshake.Server)
		}
	}
	return nil
}

// canonicalManifestJSON returns the pinned-artefact manifest as
// indented JSON. Stable across runs (json.MarshalIndent with sorted
// struct fields).
func canonicalManifestJSON(manifest ArtifactManifest) (string, error) {
	body, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return "", err
	}
	return string(body), nil
}

// RenderInputV2 extends RenderInput with the V2 mgmt-plane fields
// (FRP-10 §9.5.2). Same byte-for-byte shape as RenderInput plus
// MgmtPubKeyHex (per-deploy publisher pubkey for mgmt-token
// verification, hex-encoded) and MgmtPort (the random port chosen
// by the wizard at provision time, in [10000, 65000]).
type RenderInputV2 struct {
	RenderInput

	// MgmtPubKeyHex is the hex-encoded Ed25519 public key written
	// to /etc/daal/mgmt/pubkey. The mgmt-plane service verifies
	// every Authorization: Daal-Mgmt-Token header against this
	// key. FRP-10 invariant 19.
	MgmtPubKeyHex string

	// MgmtPort is the random port in [10000, 65000] the wizard
	// chose at provision time. Stamped into
	// OperatorRecord.MgmtPort (FRP-10 invariant 27) and written
	// to /etc/daal/mgmt/port for the mgmt service to read at
	// boot. Empty/zero values fail closed.
	MgmtPort int

	// CoverSNI is the per-relay REALITY cover host the provider chose
	// (publisher/deploy/sni). It is already inside SingBoxConfigJSON —
	// this field writes it to /etc/daal/cover-sni as well, so the box
	// itself can state what it is advertising without anyone parsing
	// sing-box's config: the mgmt plane's /rotate-tls needs a source of
	// truth to rewrite, and an operator on the box needs one to read.
	//
	// Empty is allowed (V1.5-era boxes, and non-REALITY profiles); the
	// file is then not written at all rather than written blank.
	CoverSNI string
}

// RenderV2 produces the V2 cloud-init YAML. Same determinism
// contract as Render: same input → byte-identical output.
//
// Selection between Render and RenderV2 happens at the wizard
// layer; provider adapters never see it. V1.5 deploys still use
// Render; V2 deploys use RenderV2.
func RenderV2(in RenderInputV2) ([]byte, error) {
	if err := validate(in.RenderInput); err != nil {
		return nil, err
	}
	if in.MgmtPubKeyHex == "" {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex required")
	}
	mgmtPub, err := hex.DecodeString(strings.TrimSpace(in.MgmtPubKeyHex))
	if err != nil {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex not hex: %w", err)
	}
	if len(mgmtPub) != 32 {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex wrong size %d (want 32 bytes)", len(mgmtPub))
	}
	if in.MgmtPort < 10000 || in.MgmtPort > 65000 {
		return nil, fmt.Errorf("RenderInputV2.MgmtPort %d outside [10000, 65000]", in.MgmtPort)
	}
	// The box may only declare a cover host it actually serves. A
	// /etc/daal/cover-sni that disagrees with the config would send
	// /rotate-tls rewriting the wrong value, which is a slower version
	// of the same probe mismatch.
	if err := checkDeclaredCoverSNI(in.CoverSNI, in.SingBoxConfigJSON); err != nil {
		return nil, err
	}
	manifest, err := canonicalManifestJSON(V2Artifacts)
	if err != nil {
		return nil, err
	}
	cdnEnabled := in.OriginCACertPEM != "" || in.OriginCAPrivPEM != "" || in.AOPClientCertPEM != ""
	if cdnEnabled {
		if in.OriginCACertPEM == "" || in.OriginCAPrivPEM == "" || in.AOPClientCertPEM == "" {
			return nil, fmt.Errorf("cdn_fronted: OriginCACertPEM + OriginCAPrivPEM + AOPClientCertPEM must be supplied together")
		}
	}
	td := struct {
		EphemeralSSHPublicKey  string
		ProvisioningClientIP   string
		HealthToken            string
		SingBoxConfigJSON      string
		PinnedArtifactManifest string
		DaalReleasePubKey      string
		VerifierShim           string
		CDNEnabled             bool
		OriginCACertPEM        string
		OriginCAPrivPEM        string
		AOPClientCertPEM       string
		MgmtPubKeyHex          string
		MgmtPort               int
		CoverSNI               string
	}{
		EphemeralSSHPublicKey:  in.EphemeralSSHPublicKey,
		ProvisioningClientIP:   in.ProvisioningClientIP,
		HealthToken:            in.HealthToken,
		SingBoxConfigJSON:      in.SingBoxConfigJSON,
		PinnedArtifactManifest: manifest,
		DaalReleasePubKey:      DaalReleasePubKeyPEM,
		VerifierShim:           shimBody,
		CDNEnabled:             cdnEnabled,
		OriginCACertPEM:        in.OriginCACertPEM,
		OriginCAPrivPEM:        in.OriginCAPrivPEM,
		AOPClientCertPEM:       in.AOPClientCertPEM,
		MgmtPubKeyHex:          in.MgmtPubKeyHex,
		MgmtPort:               in.MgmtPort,
		CoverSNI:               in.CoverSNI,
	}
	tmpl, err := template.New("cloudinit-v2").Funcs(template.FuncMap{
		"indent": indent,
	}).Parse(templateBodyV2)
	if err != nil {
		return nil, fmt.Errorf("parse v2 template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, td); err != nil {
		return nil, fmt.Errorf("execute v2 template: %w", err)
	}
	return buf.Bytes(), nil
}

// checkDeclaredCoverSNI verifies RenderInputV2.CoverSNI against the
// REALITY inbounds in the config. Empty declares nothing and is fine;
// a non-empty declaration must match every REALITY inbound's
// server_name, which checkRealityCoverSNI has already proven equals its
// handshake.server.
func checkDeclaredCoverSNI(declared, configJSON string) error {
	if declared == "" {
		return nil
	}
	var doc struct {
		Inbounds []struct {
			Tag string `json:"tag"`
			TLS *struct {
				ServerName string `json:"server_name"`
				Reality    *struct {
					Enabled bool `json:"enabled"`
				} `json:"reality"`
			} `json:"tls"`
		} `json:"inbounds"`
	}
	if err := json.Unmarshal([]byte(configJSON), &doc); err != nil {
		return fmt.Errorf("RenderInputV2.SingBoxConfigJSON is not valid JSON: %w", err)
	}
	for i, inb := range doc.Inbounds {
		if inb.TLS == nil || inb.TLS.Reality == nil || !inb.TLS.Reality.Enabled {
			continue
		}
		if inb.TLS.ServerName != declared {
			name := inb.Tag
			if name == "" {
				name = fmt.Sprintf("inbounds[%d]", i)
			}
			return fmt.Errorf("cover sni: RenderInputV2.CoverSNI is %q but inbound %s serves %q", declared, name, inb.TLS.ServerName)
		}
	}
	return nil
}

// indent prefixes each line of `s` with `n` spaces. Used by
// template.yaml.tmpl to embed multi-line content under YAML keys.
func indent(n int, s string) string {
	pad := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		// Don't indent empty trailing lines (preserves YAML clean).
		if l == "" && i == len(lines)-1 {
			continue
		}
		lines[i] = pad + l
	}
	return strings.Join(lines, "\n")
}
