// Package cloudinit renders the supplement §9.3 cloud-init YAML
// against ProvisionOpts-derived inputs. Output is deterministic:
// same RenderInput → byte-identical YAML.
//
// The template is loaded from template.yaml.tmpl (Go text/template).
// The verifier shim is loaded from shim.sh.tmpl and indented into
// the YAML at render time.
package cloudinit

import (
	"bytes"
	_ "embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"strings"
	"text/template"
)

//go:embed template.yaml.tmpl
var templateBody string

//go:embed v2.yaml.tmpl
var templateBodyV2 string

//go:embed shim.sh.tmpl
var shimBody string

// RenderInput is the typed input to Render. Every field is required;
// callers (the Hetzner adapter at FRP-4a, the wizard at FRP-5) build
// this from ProvisionOpts + a sing-box config emitted by the
// toolbox-profile renderer.
type RenderInput struct {
	// EphemeralSSHPublicKey is the OpenSSH-formatted single-line
	// public key the box accepts during the 60 s provisioning window.
	EphemeralSSHPublicKey string

	// ProvisioningClientIP is the Helper's outbound IP. ufw rules
	// for ports 22 + 9876 are bound to this IP only.
	ProvisioningClientIP string

	// HealthToken is a 32-byte random token the Helper uses ONCE to
	// confirm sing-box is up. Generated by the caller per provision.
	HealthToken string

	// SingBoxConfigJSON is the rendered sing-box config (from the
	// toolbox profile + ProvisionOpts). Embedded verbatim into
	// /etc/sing-box/config.json on the box.
	SingBoxConfigJSON string

	// FRP-8 §11.7 cdn_fronted optional fields. All of these are
	// empty for plain direct_vps deployments; non-empty only when
	// the FRP elected a CDN front. They install the
	// Cloudflare-issued Origin CA cert + AOP client cert onto the
	// origin so the origin can present them back to Cloudflare's
	// edge under Authenticated Origin Pulls.
	//
	// The cert / key bytes are read from the Helper's local files
	// at render time (paths are tracked in V005's cdn_fronts
	// table); the bytes themselves embed verbatim here.

	// OriginCACertPEM is the Cloudflare Origin CA cert (public)
	// bundled into /etc/daal/cdn/origin_ca.pem. Empty for
	// non-CDN deployments.
	OriginCACertPEM string
	// OriginCAPrivPEM is the Origin CA private key bundled into
	// /etc/daal/cdn/origin_ca.key (mode 0600). Empty for non-CDN.
	OriginCAPrivPEM string
	// AOPClientCertPEM is the Cloudflare-signed client cert the
	// origin presents back under AOP, bundled into
	// /etc/daal/cdn/aop_client.pem (mode 0600). Empty for
	// non-CDN.
	AOPClientCertPEM string
}

// templateData is what reaches the text/template engine. Built from
// RenderInput + the package-level pinned-artefact manifest +
// release-pubkey constants + verifier shim body.
type templateData struct {
	EphemeralSSHPublicKey  string
	ProvisioningClientIP   string
	HealthToken            string
	SingBoxConfigJSON      string
	PinnedArtifactManifest string
	DaalReleasePubKey      string
	VerifierShim           string

	// FRP-8 cdn_fronted fields. CDN flag drives the conditional
	// write_files block in the template.
	CDNEnabled       bool
	OriginCACertPEM  string
	OriginCAPrivPEM  string
	AOPClientCertPEM string
}

// Render produces the rendered cloud-init YAML for the given input.
// Pure function: same input → byte-identical output.
func Render(in RenderInput) ([]byte, error) {
	if err := validate(in); err != nil {
		return nil, err
	}
	manifest, err := canonicalManifestJSON()
	if err != nil {
		return nil, err
	}
	cdnEnabled := in.OriginCACertPEM != "" || in.OriginCAPrivPEM != "" || in.AOPClientCertPEM != ""
	if cdnEnabled {
		// All three or none — half-state means the wizard built a
		// torn cert bundle.
		if in.OriginCACertPEM == "" || in.OriginCAPrivPEM == "" || in.AOPClientCertPEM == "" {
			return nil, fmt.Errorf("cdn_fronted: OriginCACertPEM + OriginCAPrivPEM + AOPClientCertPEM must be supplied together")
		}
	}
	td := templateData{
		EphemeralSSHPublicKey:  in.EphemeralSSHPublicKey,
		ProvisioningClientIP:   in.ProvisioningClientIP,
		HealthToken:            in.HealthToken,
		SingBoxConfigJSON:      in.SingBoxConfigJSON,
		PinnedArtifactManifest: manifest,
		DaalReleasePubKey:      DaalReleasePubKeyPEM,
		VerifierShim:           shimBody,
		CDNEnabled:             cdnEnabled,
		OriginCACertPEM:        in.OriginCACertPEM,
		OriginCAPrivPEM:        in.OriginCAPrivPEM,
		AOPClientCertPEM:       in.AOPClientCertPEM,
	}
	tmpl, err := template.New("cloudinit").Funcs(template.FuncMap{
		"indent": indent,
	}).Parse(templateBody)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, td); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	return buf.Bytes(), nil
}

// VerifierShimSource returns the embedded verifier shim bytes
// verbatim (no template substitution). Tests pin the SHA-256 of
// these bytes; FRP-7 / FRP-8 amendments must keep this stable.
func VerifierShimSource() []byte {
	return []byte(shimBody)
}

// VerifierShimLineCount returns the number of lines in shim.sh.tmpl.
// Phase doc invariant: the shim is meant to be ~50 lines (≤60 in
// practice). Test pins this.
func VerifierShimLineCount() int {
	return strings.Count(shimBody, "\n")
}

func validate(in RenderInput) error {
	if in.EphemeralSSHPublicKey == "" {
		return fmt.Errorf("RenderInput.EphemeralSSHPublicKey required")
	}
	if in.ProvisioningClientIP == "" {
		return fmt.Errorf("RenderInput.ProvisioningClientIP required")
	}
	if in.HealthToken == "" {
		return fmt.Errorf("RenderInput.HealthToken required")
	}
	if in.SingBoxConfigJSON == "" {
		return fmt.Errorf("RenderInput.SingBoxConfigJSON required")
	}
	return nil
}

// canonicalManifestJSON returns the pinned-artefact manifest as
// indented JSON. Stable across runs (json.MarshalIndent with sorted
// struct fields).
func canonicalManifestJSON() (string, error) {
	body, err := json.MarshalIndent(V15Artifacts, "", "  ")
	if err != nil {
		return "", err
	}
	return string(body), nil
}

// RenderInputV2 extends RenderInput with the V2 mgmt-plane fields
// (FRP-10 §9.5.2). Same byte-for-byte shape as RenderInput plus
// MgmtPubKeyHex (per-deploy publisher pubkey for mgmt-token
// verification, hex-encoded) and MgmtPort (the random port chosen
// by the wizard at provision time, in [10000, 65000]).
type RenderInputV2 struct {
	RenderInput

	// MgmtPubKeyHex is the hex-encoded Ed25519 public key written
	// to /etc/daal/mgmt/pubkey. The mgmt-plane service verifies
	// every Authorization: Daal-Mgmt-Token header against this
	// key. FRP-10 invariant 19.
	MgmtPubKeyHex string

	// MgmtPort is the random port in [10000, 65000] the wizard
	// chose at provision time. Stamped into
	// OperatorRecord.MgmtPort (FRP-10 invariant 27) and written
	// to /etc/daal/mgmt/port for the mgmt service to read at
	// boot. Empty/zero values fail closed.
	MgmtPort int
}

// RenderV2 produces the V2 cloud-init YAML. Same determinism
// contract as Render: same input → byte-identical output.
//
// Selection between Render and RenderV2 happens at the wizard
// layer; provider adapters never see it. V1.5 deploys still use
// Render; V2 deploys use RenderV2.
func RenderV2(in RenderInputV2) ([]byte, error) {
	if err := validate(in.RenderInput); err != nil {
		return nil, err
	}
	if in.MgmtPubKeyHex == "" {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex required")
	}
	mgmtPub, err := hex.DecodeString(strings.TrimSpace(in.MgmtPubKeyHex))
	if err != nil {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex not hex: %w", err)
	}
	if len(mgmtPub) != 32 {
		return nil, fmt.Errorf("RenderInputV2.MgmtPubKeyHex wrong size %d (want 32 bytes)", len(mgmtPub))
	}
	if in.MgmtPort < 10000 || in.MgmtPort > 65000 {
		return nil, fmt.Errorf("RenderInputV2.MgmtPort %d outside [10000, 65000]", in.MgmtPort)
	}
	manifest, err := canonicalManifestJSON()
	if err != nil {
		return nil, err
	}
	cdnEnabled := in.OriginCACertPEM != "" || in.OriginCAPrivPEM != "" || in.AOPClientCertPEM != ""
	if cdnEnabled {
		if in.OriginCACertPEM == "" || in.OriginCAPrivPEM == "" || in.AOPClientCertPEM == "" {
			return nil, fmt.Errorf("cdn_fronted: OriginCACertPEM + OriginCAPrivPEM + AOPClientCertPEM must be supplied together")
		}
	}
	td := struct {
		EphemeralSSHPublicKey  string
		ProvisioningClientIP   string
		HealthToken            string
		SingBoxConfigJSON      string
		PinnedArtifactManifest string
		DaalReleasePubKey      string
		VerifierShim           string
		CDNEnabled             bool
		OriginCACertPEM        string
		OriginCAPrivPEM        string
		AOPClientCertPEM       string
		MgmtPubKeyHex          string
		MgmtPort               int
	}{
		EphemeralSSHPublicKey:  in.EphemeralSSHPublicKey,
		ProvisioningClientIP:   in.ProvisioningClientIP,
		HealthToken:            in.HealthToken,
		SingBoxConfigJSON:      in.SingBoxConfigJSON,
		PinnedArtifactManifest: manifest,
		DaalReleasePubKey:      DaalReleasePubKeyPEM,
		VerifierShim:           shimBody,
		CDNEnabled:             cdnEnabled,
		OriginCACertPEM:        in.OriginCACertPEM,
		OriginCAPrivPEM:        in.OriginCAPrivPEM,
		AOPClientCertPEM:       in.AOPClientCertPEM,
		MgmtPubKeyHex:          in.MgmtPubKeyHex,
		MgmtPort:               in.MgmtPort,
	}
	tmpl, err := template.New("cloudinit-v2").Funcs(template.FuncMap{
		"indent": indent,
	}).Parse(templateBodyV2)
	if err != nil {
		return nil, fmt.Errorf("parse v2 template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, td); err != nil {
		return nil, fmt.Errorf("execute v2 template: %w", err)
	}
	return buf.Bytes(), nil
}

// indent prefixes each line of `s` with `n` spaces. Used by
// template.yaml.tmpl to embed multi-line content under YAML keys.
func indent(n int, s string) string {
	pad := strings.Repeat(" ", n)
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		// Don't indent empty trailing lines (preserves YAML clean).
		if l == "" && i == len(lines)-1 {
			continue
		}
		lines[i] = pad + l
	}
	return strings.Join(lines, "\n")
}
