package trust_test

import (
	"errors"
	"os"
	"path/filepath"
	"runtime"
	"testing"
	"time"

	"daal/bundle-go/bundle"
	"daal/bundle-go/importer"
	"daal/bundle-go/publisher"
	"daal/core/internal/selection"
	"daal/core/routestore"
	"daal/core/trust"
)

// samplesDir is generated by Phase 1A's sample harness. Derived from
// this test file's location so it works on any checkout path (CI
// workspaces are not /home/daal).
var samplesDir = filepath.Join(testRepoRoot(), "specs", "test-vectors", "bundles", "samples")

func testRepoRoot() string {
	_, file, _, _ := runtime.Caller(0)
	// .../core/trust/importer_test.go → repo root.
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func openStore(t *testing.T) *routestore.Store {
	t.Helper()
	s, err := routestore.Open(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { s.Close() })
	return s
}

func wordlists() bundle.Wordlists { return publisher.DefaultWordlists() }

func TestImportSignedASample_TOFUFlow(t *testing.T) {
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	// First import → trust prompt expected.
	body := mustReadFile(t, filepath.Join(samplesDir, "signed-A.sbp"))
	v, err := importer.ImportBytes(body, a, wordlists(), now)
	if err != nil {
		t.Fatalf("first import error: %v (verdict %+v)", err, v)
	}
	if v.Kind != importer.VerdictTrustPromptNeeded {
		t.Fatalf("expected trust prompt, got %v reason=%q", v.Kind, v.Reason)
	}
	if v.RouteCount != 1 || v.HexEN == "" || v.HexFA == "" {
		t.Fatalf("unexpected verdict: %+v", v)
	}

	// User trusts the publisher → silent import on the second call.
	v2, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now)
	if err != nil || v2.Kind != importer.VerdictImported {
		t.Fatalf("accept-trust failed: kind=%v err=%v", v2.Kind, err)
	}
	routes, err := s.ListRoutes()
	if err != nil || len(routes) != 1 {
		t.Fatalf("routes after import: %v %v", routes, err)
	}
	if routes[0].TrustState != "tofu" {
		t.Fatalf("trust_state %q, want tofu", routes[0].TrustState)
	}
	if got, err := s.GetSecret("route:" + routes[0].RouteID); err != nil || len(got) == 0 {
		t.Fatalf("profile secret missing: %v", err)
	}

	// Re-importing the same bundle is silent (already pinned).
	v3, err := importer.ImportBytes(body, a, wordlists(), now)
	if err != nil || v3.Kind != importer.VerdictImported {
		t.Fatalf("re-import expected silent: kind=%v err=%v", v3.Kind, err)
	}
}

func TestUnknownPublisherReprompts(t *testing.T) {
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(samplesDir, "unknown-publisher-B.sbp"))
	v, _ := importer.ImportBytes(body, a, wordlists(), now)
	if v.Kind != importer.VerdictTrustPromptNeeded {
		t.Fatalf("unknown-publisher expected prompt, got %v", v.Kind)
	}
}

func TestRevocationMarksRouteRevoked(t *testing.T) {
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	signedA := mustReadFile(t, filepath.Join(samplesDir, "signed-A.sbp"))
	if _, err := importer.AcceptTrustPrompt("trust", signedA, a, wordlists(), now); err != nil {
		t.Fatal(err)
	}

	revoked := mustReadFile(t, filepath.Join(samplesDir, "revoked-A.sbp"))
	v, err := importer.ImportBytes(revoked, a, wordlists(), now)
	if err != nil || v.Kind != importer.VerdictImported {
		t.Fatalf("revoked-A import: kind=%v err=%v", v.Kind, err)
	}

	row, err := s.GetRoute("sample-route-1")
	if err != nil {
		t.Fatal(err)
	}
	if row.TrustState != "revoked" {
		t.Fatalf("route revocation not applied: trust_state=%s", row.TrustState)
	}
}

// FRP-2 (Phase 30): RelayPack import end-to-end tests. The corpus
// at specs/test-vectors/relaypack/ is the contract; FRP-2 binds
// against it. These tests use the FRP-1 seed vectors that V1.5
// accepts.

var relayPackCorpusDir = filepath.Join(testRepoRoot(), "specs", "test-vectors", "relaypack")

// TestImportRelayPackBundle_FieldsLandInRouteRow verifies that all
// 9 RouteRow RelayPack fields are populated after importing a
// V1.5-positive RelayPack bundle. Per RP021 the FreshnessURL must
// be empty at V1.5.
func TestImportRelayPackBundle_FieldsLandInRouteRow(t *testing.T) {
	if _, err := readFileOptional(filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp")); err != nil {
		t.Skipf("corpus fixture missing (regenerate with `cd publisher && go run ./cmd/relaypack-fixtures`): %v", err)
	}
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp"))
	// First import → trust prompt (publisher not pinned).
	v, err := importer.ImportBytes(body, a, wordlists(), now)
	if err != nil {
		t.Fatalf("import: err=%v verdict=%+v", err, v)
	}
	if v.Kind != importer.VerdictTrustPromptNeeded {
		t.Fatalf("expected trust prompt; got %+v", v)
	}
	v2, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now)
	if err != nil || v2.Kind != importer.VerdictImported {
		t.Fatalf("accept trust: err=%v verdict=%+v", err, v2)
	}

	all, err := s.ListRoutes()
	if err != nil {
		t.Fatal(err)
	}
	if len(all) == 0 {
		t.Fatal("no routes imported")
	}
	row := all[0]
	if row.ExposureMode != "direct_vps" {
		t.Errorf("ExposureMode = %q want direct_vps", row.ExposureMode)
	}
	if row.FamilyClass != "vps-native" {
		t.Errorf("FamilyClass = %q want vps-native", row.FamilyClass)
	}
	if row.ProbingRiskClass == "" {
		t.Errorf("ProbingRiskClass must be populated; got empty")
	}
	if len(row.PublicRiskTags) == 0 {
		t.Errorf("PublicRiskTags must be populated; got empty")
	}
	if row.RelayPackID == "" {
		t.Errorf("RelayPackID (bundle-level) must be populated on every per-route row")
	}
	if row.FreshnessURL != "" {
		t.Errorf("FreshnessURL must be empty at V1.5 (RP021 enforces); got %q", row.FreshnessURL)
	}
	if row.SharedRiskGraphJSON == "" || row.SharedRiskGraphJSON == "[]" {
		t.Errorf("SharedRiskGraphJSON must be populated (bundle-level); got %q", row.SharedRiskGraphJSON)
	}
	if row.ModifiersJSON != "" {
		t.Errorf("ModifiersJSON must be empty at V1.5 (RP013 enforces); got %q", row.ModifiersJSON)
	}
}

// TestImportRelayPackBundle_ReimportIdempotent verifies invariant 20:
// re-importing the same .sbp produces equal row sets including all
// RelayPack columns.
func TestImportRelayPackBundle_ReimportIdempotent(t *testing.T) {
	if _, err := readFileOptional(filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp")); err != nil {
		t.Skipf("corpus fixture missing: %v", err)
	}
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp"))
	// AcceptTrustPrompt the first import.
	if _, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now); err != nil {
		t.Fatalf("first accept: %v", err)
	}
	first, err := s.ListRoutes()
	if err != nil {
		t.Fatal(err)
	}

	// Re-import (silent — publisher already pinned).
	v, err := importer.ImportBytes(body, a, wordlists(), now)
	if err != nil || v.Kind != importer.VerdictImported {
		t.Fatalf("re-import: err=%v verdict=%+v", err, v)
	}
	second, err := s.ListRoutes()
	if err != nil {
		t.Fatal(err)
	}
	if len(first) != len(second) {
		t.Errorf("row count drift: first=%d second=%d", len(first), len(second))
	}
	for i := range first {
		if first[i].ExposureMode != second[i].ExposureMode ||
			first[i].FamilyClass != second[i].FamilyClass ||
			first[i].RelayPackID != second[i].RelayPackID ||
			first[i].SharedRiskGraphJSON != second[i].SharedRiskGraphJSON {
			t.Errorf("RelayPack field drift on re-import [%d]:\nfirst=%+v\nsecond=%+v", i, first[i], second[i])
		}
	}
}

// TestImportRelayPackBundle_CDNFrontedImportsAtCurrentPhase is the
// end-to-end proof that the phase gate is open on the path that
// actually matters: a REAL signed corpus bundle, through the real
// importer, into the real SQLite route store.
//
// `cdn-fronted-minimal.sbp` is the corpus vector whose expected
// outcomes are "V1.5 → RP004, V1.6 → pass". The recipient used to
// validate at V1.5, so this bundle — which the publisher CLI signs at
// V1.6 by default — was unimportable. It now imports, and the
// cdn_fronted candidate reaches the store with its exposure_mode and
// origin tags intact (the selector reads both).
func TestImportRelayPackBundle_CDNFrontedImportsAtCurrentPhase(t *testing.T) {
	if _, err := readFileOptional(filepath.Join(relayPackCorpusDir, "cdn-fronted-minimal.sbp")); err != nil {
		t.Skipf("corpus fixture missing: %v", err)
	}
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(relayPackCorpusDir, "cdn-fronted-minimal.sbp"))
	// First call hits the trust prompt (publisher unpinned) — and must
	// reach it, rather than being rejected by the validator first.
	v, err := importer.ImportBytes(body, a, wordlists(), now)
	if err != nil {
		t.Fatalf("ImportBytes: %v (verdict=%+v)", err, v)
	}
	if v.Kind != importer.VerdictTrustPromptNeeded {
		t.Fatalf("expected VerdictTrustPromptNeeded; got %v (reason %q)", v.Kind, v.Reason)
	}
	v2, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now)
	if err != nil {
		t.Fatalf("AcceptTrustPrompt: %v (verdict=%+v)", err, v2)
	}
	if v2.Kind != importer.VerdictImported {
		t.Fatalf("expected VerdictImported; got %v (reason %q)", v2.Kind, v2.Reason)
	}

	rows, err := s.ListRoutes()
	if err != nil {
		t.Fatal(err)
	}
	var cdn int
	for _, r := range rows {
		if r.ExposureMode == "cdn_fronted" {
			cdn++
			if len(r.OriginRiskTags) == 0 {
				t.Errorf("cdn_fronted route %s lost its origin_* tags", r.RouteID)
			}
		}
	}
	if cdn == 0 {
		t.Errorf("no cdn_fronted route reached the store; rows=%d", len(rows))
	}
}

// TestImportRelayPackBundle_FreshnessURLImportsAtCurrentPhase is the
// same proof for RP021, through the same real path. The corpus vector
// is literally named "...-v15-rejected" because V1.5 is the only phase
// that rejects it.
func TestImportRelayPackBundle_FreshnessURLImportsAtCurrentPhase(t *testing.T) {
	const fixture = "bundle-with-freshness-url-v15-rejected.sbp"
	if _, err := readFileOptional(filepath.Join(relayPackCorpusDir, fixture)); err != nil {
		t.Skipf("corpus fixture missing: %v", err)
	}
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(relayPackCorpusDir, fixture))
	v, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now)
	if err != nil {
		t.Fatalf("AcceptTrustPrompt: %v (verdict=%+v)", err, v)
	}
	if v.Kind != importer.VerdictImported {
		t.Fatalf("expected VerdictImported; got %v (reason %q)", v.Kind, v.Reason)
	}

	rows, err := s.ListRoutes()
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) == 0 {
		t.Fatal("no routes imported")
	}
	for _, r := range rows {
		if r.FreshnessURL == "" {
			t.Errorf("route %s: freshness_url did not survive the import", r.RouteID)
		}
	}
}

// TestImportRelayPackBundle_SharedRiskGraphRoundTrip verifies the
// bundle-level shared_risk_graph survives the importer round-trip
// onto every per-route RouteRow.
func TestImportRelayPackBundle_SharedRiskGraphRoundTrip(t *testing.T) {
	if _, err := readFileOptional(filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp")); err != nil {
		t.Skipf("corpus fixture missing: %v", err)
	}
	s := openStore(t)
	a := &trust.StoreAdapter{S: s}
	now := time.Now().UTC()

	body := mustReadFile(t, filepath.Join(relayPackCorpusDir, "direct-vps-minimal.sbp"))
	if _, err := importer.AcceptTrustPrompt("trust", body, a, wordlists(), now); err != nil {
		t.Fatalf("import: %v", err)
	}
	all, err := s.ListRoutes()
	if err != nil || len(all) == 0 {
		t.Fatalf("list routes: %v rows=%d", err, len(all))
	}
	// All routes share the same bundle-level SharedRiskGraphJSON.
	want := all[0].SharedRiskGraphJSON
	if want == "" || want == "[]" {
		t.Errorf("SharedRiskGraphJSON must be non-trivial JSON; got %q", want)
	}
	for i, r := range all {
		if r.SharedRiskGraphJSON != want {
			t.Errorf("row[%d] SharedRiskGraphJSON = %q want %q (must be denormalised same value across routes)", i, r.SharedRiskGraphJSON, want)
		}
	}
}

func TestStoreAdapter_ModifierPlatformGateRejectsBeforePersist(t *testing.T) {
	s := openStore(t)
	a := &trust.StoreAdapter{
		S:                   s,
		ModifierRuntimeGOOS: "linux",
		ModifierDesktopHint: true,
	}

	err := a.SaveImport(testPublisherInput(), []importer.RouteInput{testRouteInputWithModifiers(
		`[{"kind":"client_desync"}]`,
	)})
	if err == nil {
		t.Fatal("SaveImport with modifier-bearing route should fail closed at FRP-12")
	}
	if !errors.Is(err, selection.ErrModifierPlatform) {
		t.Fatalf("SaveImport error = %v, want ErrModifierPlatform", err)
	}
	routes, listErr := s.ListRoutes()
	if listErr != nil {
		t.Fatal(listErr)
	}
	if len(routes) != 0 {
		t.Fatalf("modifier rejection must happen before route persistence; got %d routes", len(routes))
	}
}

func TestStoreAdapter_ModifierPlatformGateAllowsFuturePassPolicy(t *testing.T) {
	s := openStore(t)
	a := &trust.StoreAdapter{
		S:                   s,
		ModifierRuntimeGOOS: "linux",
		ModifierDesktopHint: true,
		ModifierPlatformPolicy: func(kind string) trust.ModifierPlatformAllow {
			if kind == "client_desync" {
				return trust.ModifierPlatformAllow{Pass: true, Platforms: []string{"linux-desktop"}}
			}
			return trust.ModifierPlatformAllow{}
		},
	}

	err := a.SaveImport(testPublisherInput(), []importer.RouteInput{testRouteInputWithModifiers(
		`[{"kind":"client_desync"}]`,
	)})
	if err != nil {
		t.Fatalf("SaveImport with allowed future PASS policy: %v", err)
	}
	row, err := s.GetRoute("route-modifier-gate")
	if err != nil {
		t.Fatal(err)
	}
	if row.ModifiersJSON == "" {
		t.Fatal("ModifiersJSON should persist when platform policy allows the route")
	}
}

func testPublisherInput() importer.PublisherInput {
	return importer.PublisherInput{
		Fingerprint:    "publisher-modifier-gate",
		DisplayName:    "Modifier Gate Test",
		TrustLevel:     "tofu_friend",
		KeyStatus:      "active",
		FirstSeen:      "2026-05-05T00",
		LastSeenBundle: "2026-05-05T00",
	}
}

func testRouteInputWithModifiers(modifiersJSON string) importer.RouteInput {
	return importer.RouteInput{
		RouteID:         "route-modifier-gate",
		TransportFamily: "vless-reality",
		ScarcityClass:   "normal",
		Engine:          "sing-box",
		SourceType:      "bundle",
		ModesAllowed:    []string{"normal"},
		ExpiresAt:       "2026-12-31T00:00:00Z",
		ImportedAt:      "2026-05-05T00",
		TrustState:      "tofu",
		Profile:         []byte("profile"),
		RelayPack: &importer.RelayPackMeta{
			ExposureMode:        "direct_vps",
			FamilyClass:         "vps-native",
			ProbingRiskClass:    "moderate",
			PublicRiskTags:      []string{"public_ip:203.0.113.9"},
			OriginRiskTags:      []string{},
			ModifiersJSON:       modifiersJSON,
			RelayPackID:         "rp-modifier-gate",
			SharedRiskGraphJSON: "[]",
		},
	}
}

func readFileOptional(path string) ([]byte, error) {
	return os.ReadFile(path)
}
